PLATFORMID=12973
PLATFORMOS=dryos
PLATFORMOSVER=55


# start of firmware
ROMBASEADDR=0xFF810000


# points to the start of the memory pool used by the firmware
MEMISOSTART=0x001bdf3c

# type of FI2 encoding
KEYSYS = d4g
# type of diskboot encoding
NEED_ENCODED_DISKBOOT = 13

