# SX270HS - uses SX280HS as source camera

# mandatory for DIGIC 6
THUMB_FW=1

# next line is for the compatibility check, as comment
# PLATFORMID @ 0xfff60040
# below 2 commented lines are used by tools/compatbuilder.sh
# BLINK_LED_CONTROL=4
# BLINK_LED_GPIO=0xd20b0994

DIGIC = 60
