#include "stubs_asm.h"

// Found manually

DEF(canon_play_menu_active                  ,0x0000e784)

DEF(touch_screen_x							,0x000028f0)
DEF(touch_screen_y							,0x000028f2)
DEF(touch_screen_active						,0x000028c4)

DEF(cds_gain_value							,0x0000abd0)

DEF(viewport_buffers, 0xFF3D0428)			// 1.00a sub_FF0435C8 (FF043978)
DEF(active_viewport_buffer, 0x2104)			// 1.00a sub_FF0435C8 (FF0435CC & FF043A28)
