//Auto generated file. Do not edit the contents of this file.
//Update the core/module_exportlist.c

#ifndef MODULE_EXPORTLIST_H
#define MODULE_EXPORTLIST_H

#define CHDK_BUILD_NUM 9


//Section: exported defines
extern int CAM_CHDK_BLACK_LEVEL ;
extern int CAM_CHDK_WHITE_LEVEL ;
extern int CAM_CHDK_RAW_ROWS    ;
extern int CAM_CHDK_RAW_ROWPIX  ;
extern int RAW_CHDK_ROWLEN      ;



//Section: ids of exported symbols
#define MODULESYM_MODULE_ASYNC_UNLOAD 2
#define MODULESYM_MODULE_SET_FLAGS 3
#define MODULESYM_CONF_GETVALUE 4
#define MODULESYM_MODULE_RUN 5
#define MODULESYM_MALLOC 6
#define MODULESYM_FREE 7
#define MODULESYM_UMALLOC 8
#define MODULESYM_UFREE 9
#define MODULESYM_OPEN 10
#define MODULESYM_WRITE 11
#define MODULESYM_LSEEK 12
#define MODULESYM_CLOSE 13
#define MODULESYM_READ 14
#define MODULESYM_REMOVE 15
#define MODULESYM_RENAME 16
#define MODULESYM_FOPEN 17
#define MODULESYM_FCLOSE 18
#define MODULESYM_FSEEK 19
#define MODULESYM_FREAD 20
#define MODULESYM_FWRITE 21
#define MODULESYM_STAT 22
#define MODULESYM_OPENDIR 23
#define MODULESYM_READDIR 24
#define MODULESYM_CLOSEDIR 25
#define MODULESYM_GET_TICK_COUNT 26
#define MODULESYM_TIME 27
#define MODULESYM_UTIME 28
#define MODULESYM_LOCALTIME 29
#define MODULESYM_RAND 30
#define MODULESYM_SRAND 31
#define MODULESYM_LANG_STR 32
#define MODULESYM_SPRINTF 33
#define MODULESYM_STRLEN 34
#define MODULESYM_STRCPY 35
#define MODULESYM_STRNCMP 36
#define MODULESYM_STRPBRK 37
#define MODULESYM_STRCHR 38
#define MODULESYM_STRCMP 39
#define MODULESYM_MEMCPY 40
#define MODULESYM_DRAW_TXT_STRING 41
#define MODULESYM_DRAW_STRING 42
#define MODULESYM_DRAW_RECT 43
#define MODULESYM_DRAW_FILLED_RECT 44
#define MODULESYM_DRAW_FILLED_ELLIPSE 45
#define MODULESYM_DRAW_FILLED_ROUND_RECT 46
#define MODULESYM_DRAW_LINE 47
#define MODULESYM_DRAW_CHAR 48
#define MODULESYM_GUI_GET_MODE 49
#define MODULESYM_GUI_SET_MODE 50
#define MODULESYM_GUI_DEFAULT_KBD_PROCESS_MENU_BTN 51
#define MODULESYM_SCREEN_WIDTH 52
#define MODULESYM_SCREEN_HEIGHT 53
#define MODULESYM_SCREEN_BUFFER_SIZE 54
#define MODULESYM_VID_GET_VIEWPORT_FB 55
#define MODULESYM_VID_GET_VIEWPORT_HEIGHT 56
#define MODULESYM_VID_GET_BITMAP_FB 57
#define MODULESYM_HOOK_RAW_IMAGE_ADDR 58
#define MODULESYM_HOOK_RAW_SIZE 59
#define MODULESYM_KBD_GET_AUTOCLICKED_KEY 60
#define MODULESYM_GET_BATT_PERC 61
#define MODULESYM_GUI_OSD_DRAW_CLOCK 62
#define MODULESYM_GUI_MBOX_INIT 63
#define MODULESYM_CAM_CHDK_BLACK_LEVEL 64
#define MODULESYM_CAM_CHDK_WHITE_LEVEL 65
#define MODULESYM_CAM_CHDK_RAW_ROWS 66
#define MODULESYM_CAM_CHDK_RAW_ROWPIX 67
#define MODULESYM_RAW_CHDK_ROWLEN 68
#define MODULESYM_GETFREECARDSPACEKB 69
#define MODULESYM_DEBUG_LED 70
#define MODULESYM_GUI_BROWSER_PROGRESS_SHOW 71
#define MODULESYM_VID_GET_VIEWPORT_WIDTH 72
#define MODULESYM_VID_GET_VIEWPORT_BUFFER_WIDTH 73
#define MODULESYM_VID_GET_VIEWPORT_XOFFSET 74
#define MODULESYM_VID_GET_VIEWPORT_YOFFSET 75
#define MODULESYM_VID_GET_VIEWPORT_FB_D 76
#define MODULESYM_KBD_IS_KEY_PRESSED 77
#define MODULESYM_BV_CREATE 78
#define MODULESYM_BV_GET 79
#define MODULESYM_BV_SET 80
#define MODULESYM_BV_FREE 81
#define MODULESYM_DRAW_GET_PIXEL 82
#define MODULESYM_DRAW_PIXEL 83
#define MODULESYM_DRAW_RESTORE 84
#define MODULESYM_MEMSET 85
#define MODULESYM_MODE_GET 86
#define MODULESYM_SHOOTING_GET_ZOOM 87
#define MODULESYM_SHOOTING_SET_ZOOM 88
#define MODULESYM_DRAW_TXT_CHAR 89
#define MODULESYM_RBF_CHAR_WIDTH 90
#define MODULESYM_RBF_FONT_HEIGHT 91
#define MODULESYM_RBF_DRAW_CHAR 92
#define MODULESYM_RBF_LOAD 93
#define MODULESYM_CURRENT_FONT 94
#define MODULESYM_RBF_LOAD_FROM_8X16 95
#define MODULESYM_RBF_SET_CODEPAGE 96
#define MODULESYM_GET_JOGDIAL_DIRECTION 97
#define MODULESYM_DRAW_RECT_THICK 98
#define MODULESYM_DRAW_FILLED_RECT_THICK 99
#define MODULESYM_MODULE_GET_ADR 100
#define MODULESYM_MODULE_ASYNC_UNLOAD_ALLRUNNED 101
#define MODULESYM_GETMEMINFO 102
#define MODULESYM_MODULE_RAWOP_LOAD 103
#define MODULESYM_MODULE_RAWOP_UNLOAD 104
#define MODULESYM_MODULE_MPOPUP_INIT 105
#define MODULESYM_QSORT 106
#define MODULESYM_IMG_PREFIXES 107
#define MODULESYM_IMG_EXTS 108
#define MODULESYM_STRRCHR 109
#define MODULESYM_STRNCPY 110
#define MODULESYM_MSLEEP 111
#define MODULESYM_GETTOTALCARDSPACEKB 112
#define MODULESYM_CONVERT_DNG_TO_CHDK_RAW 113
#define MODULESYM_RAW_PREPARE_DEVELOP 114
#define MODULESYM_GET_RAW_IMAGE_ADDR 115
#define MODULESYM_SHOOTING_GET_EV_CORRECTION1 116
#define MODULESYM_DRAW_RECT_SHADOW 117
#define MODULESYM_KBD_GET_CLICKED_KEY 118
#define MODULESYM_KBD_RESET_AUTOCLICKED_KEY 119
#define MODULESYM_TURNONBACKLIGHT 120
#define MODULESYM_TURNOFFBACKLIGHT 121
#define MODULESYM_MKDIR 122
#define MODULESYM_GUI_BIND_MODE 123
#define MODULESYM_0 124

#define EXPORTLIST_LAST_IDX 124

#endif
