#3193
PLATFORMID=12691

PLATFORMOS=dryos

MEMISOSTART=0xE8B40
ROMBASEADDR=0xff810000

# type of diskboot encoding: undefined = none; 1 = original; 2 = sx200
NEED_ENCODED_DISKBOOT=1
# type of FI2 encoding
KEYSYS=d4

PLATFORMOSVER=31
