#include "lolevel.h"
#include "platform.h"
#include "core.h"

#define USE_STUBS_NRFLAG 1
#define NR_AUTO (-1) // default value if NRTBL.SetDarkSubType not used is -1 (0 probalby works the same), set to enable auto

#include "../../../generic/capt_seq.c"

// first parameter matches active_raw_buffer
// second is pointer to structure
extern int _captseq_raw_addr_init (int raw_index, char **ptr);
char *current_raw_addr;

void
captseq_raw_addr_init_my (int raw_index, char **ptr)
{
    _captseq_raw_addr_init (raw_index, ptr);
    current_raw_addr = *(ptr + 0x5c / 4); // @0xfc09bf88, ptr+0x5c
}

void
clear_current_raw_addr (void)
{
    current_raw_addr = NULL;
}

// capt_seq_task 0xfc07498c

void __attribute__((naked,noinline))
capt_seq_task ()
{
    asm volatile (
            //capdis -f=chdk -s=0xfc07498d -c=31 -stubs PRIMARY.BIN 0xfc000000
            "    push    {r3, r4, r5, r6, r7, lr}\n"
            "    ldr     r4, =0x00046ee4\n"
            "    movs    r6, #0\n"
            "    ldr     r5, =0x0000c368\n"
            "loc_fc074994:\n"
            "    movs    r2, #0\n"
            "    mov     r1, sp\n"
            "    ldr     r0, [r5, #8]\n"
            "    blx     sub_fc34d054\n"
            "    lsls    r0, r0, #0x1f\n"
            "    beq     loc_fc0749b6\n"
            "    movw    r2, #0x428\n"
            "    ldr     r1, =0xfc07459c\n" //  *"SsShootTask.c"
            "    movs    r0, #0\n"
            "    blx     sub_fc34d264\n"
            "    blx     sub_fc34d0f4\n"
            "    pop     {r3, r4, r5, r6, r7, pc}\n"
            "loc_fc0749b6:\n"
            "    ldr     r0, [sp]\n"
            "    ldr     r0, [r0]\n"
            "    cmp     r0, #1\n"
            "    beq     loc_fc0749ce\n"
            "    cmp     r0, #0x2b\n"
            "    beq     loc_fc0749ce\n"
            "    cmp     r0, #0x1f\n"
            "    beq     loc_fc0749ce\n"
            "    cmp     r0, #0x23\n"
            "    beq     loc_fc0749ce\n"
            "    bl      sub_fc09df5c\n"
            "loc_fc0749ce:\n"
            "    ldr     r0, [sp]\n"
            "    ldr     r1, [r0]\n"
            "    cmp     r1, #0x34\n"
            "    bhs     loc_fc074ab8\n"

            //capdis -f=chdk -s=0xfc0749e9 -c=157 -stubs PRIMARY.BIN 0xfc000000
            "    tbb     [pc, r1]\n" // (jumptable r1 52 elements)
            "branchtable_fc0749ec:\n"
            "    .byte((loc_fc074a20 - branchtable_fc0749ec) / 2)\n" // (case 0)
            "    .byte((loc_fc074a36 - branchtable_fc0749ec) / 2)\n" // (case 1)
            "    .byte((loc_fc074a3e - branchtable_fc0749ec) / 2)\n" // (case 2)
            "    .byte((loc_fc074a4c - branchtable_fc0749ec) / 2)\n" // (case 3)
            "    .byte((loc_fc074a46 - branchtable_fc0749ec) / 2)\n" // (case 4)
            "    .byte((loc_fc074a56 - branchtable_fc0749ec) / 2)\n" // (case 5)
            "    .byte((loc_fc074a5c - branchtable_fc0749ec) / 2)\n" // (case 6)
            "    .byte((loc_fc074a66 - branchtable_fc0749ec) / 2)\n" // (case 7)
            "    .byte((loc_fc074a6e - branchtable_fc0749ec) / 2)\n" // (case 8)
            "    .byte((loc_fc074a7e - branchtable_fc0749ec) / 2)\n" // (case 9)
            "    .byte((loc_fc074a86 - branchtable_fc0749ec) / 2)\n" // (case 10)
            "    .byte((loc_fc074a8c - branchtable_fc0749ec) / 2)\n" // (case 11)
            "    .byte((loc_fc074ba8 - branchtable_fc0749ec) / 2)\n" // (case 12)
            "    .byte((loc_fc074a94 - branchtable_fc0749ec) / 2)\n" // (case 13)
            "    .byte((loc_fc074a9a - branchtable_fc0749ec) / 2)\n" // (case 14)
            "    .byte((loc_fc074aa0 - branchtable_fc0749ec) / 2)\n" // (case 15)
            "    .byte((loc_fc074aa6 - branchtable_fc0749ec) / 2)\n" // (case 16)
            "    .byte((loc_fc074aac - branchtable_fc0749ec) / 2)\n" // (case 17)
            "    .byte((loc_fc074ba8 - branchtable_fc0749ec) / 2)\n" // (case 18)
            "    .byte((loc_fc074ab2 - branchtable_fc0749ec) / 2)\n" // (case 19)
            "    .byte((loc_fc074aba - branchtable_fc0749ec) / 2)\n" // (case 20)
            "    .byte((loc_fc074ac0 - branchtable_fc0749ec) / 2)\n" // (case 21)
            "    .byte((loc_fc074ac4 - branchtable_fc0749ec) / 2)\n" // (case 22)
            "    .byte((loc_fc074aca - branchtable_fc0749ec) / 2)\n" // (case 23)
            "    .byte((loc_fc074ad0 - branchtable_fc0749ec) / 2)\n" // (case 24)
            "    .byte((loc_fc074ad6 - branchtable_fc0749ec) / 2)\n" // (case 25)
            "    .byte((loc_fc074adc - branchtable_fc0749ec) / 2)\n" // (case 26)
            "    .byte((loc_fc074ae2 - branchtable_fc0749ec) / 2)\n" // (case 27)
            "    .byte((loc_fc074aea - branchtable_fc0749ec) / 2)\n" // (case 28)
            "    .byte((loc_fc074af0 - branchtable_fc0749ec) / 2)\n" // (case 29)
            "    .byte((loc_fc074af6 - branchtable_fc0749ec) / 2)\n" // (case 30)
            "    .byte((loc_fc074afa - branchtable_fc0749ec) / 2)\n" // (case 31)
            "    .byte((loc_fc074b02 - branchtable_fc0749ec) / 2)\n" // (case 32)
            "    .byte((loc_fc074b08 - branchtable_fc0749ec) / 2)\n" // (case 33)
            "    .byte((loc_fc074b32 - branchtable_fc0749ec) / 2)\n" // (case 34)
            "    .byte((loc_fc074b38 - branchtable_fc0749ec) / 2)\n" // (case 35)
            "    .byte((loc_fc074b3e - branchtable_fc0749ec) / 2)\n" // (case 36)
            "    .byte((loc_fc074b44 - branchtable_fc0749ec) / 2)\n" // (case 37)
            "    .byte((loc_fc074b4a - branchtable_fc0749ec) / 2)\n" // (case 38)
            "    .byte((loc_fc074b52 - branchtable_fc0749ec) / 2)\n" // (case 39)
            "    .byte((loc_fc074b58 - branchtable_fc0749ec) / 2)\n" // (case 40)
            "    .byte((loc_fc074ba8 - branchtable_fc0749ec) / 2)\n" // (case 41)
            "    .byte((loc_fc074b84 - branchtable_fc0749ec) / 2)\n" // (case 42)
            "    .byte((loc_fc074b8a - branchtable_fc0749ec) / 2)\n" // (case 43)
            "    .byte((loc_fc074b78 - branchtable_fc0749ec) / 2)\n" // (case 44)
            "    .byte((loc_fc074bb6 - branchtable_fc0749ec) / 2)\n" // (case 45)
            "    .byte((loc_fc074ba8 - branchtable_fc0749ec) / 2)\n" // (case 46)
            "    .byte((loc_fc074ba8 - branchtable_fc0749ec) / 2)\n" // (case 47)
            "    .byte((loc_fc074ba8 - branchtable_fc0749ec) / 2)\n" // (case 48)
            "    .byte((loc_fc074b9c - branchtable_fc0749ec) / 2)\n" // (case 49)
            "    .byte((loc_fc074ba2 - branchtable_fc0749ec) / 2)\n" // (case 50)
            "    .byte((loc_fc074b96 - branchtable_fc0749ec) / 2)\n" // (case 51)
            ".align 1\n"
            "loc_fc074a20:\n"
            "    ldr     r0, [r0, #0xc]\n"
            "    bl      sub_fc082d96\n"
            "    BL      clear_current_raw_addr\n" // +
            "    BL      shooting_expo_param_override\n" // +
            "    bl      sub_fc08fbe8\n"
            "    ldr     r0, [r4, #0x28]\n"
            "    cmp     r0, #0\n"
            "    beq     loc_fc074a34\n"
            "    bl      sub_fc08ec20_my\n" // -> nr?, remote hook, raw hook (quick, no half press)
            "loc_fc074a34:\n"
            "    b       loc_fc074bb6\n"
            "loc_fc074a36:\n"
            "    ldr     r0, [r0, #0x10]\n"
            "    bl      sub_fc08ebd4_my\n" // -> nr?, remote hook, raw hook
            "    b       loc_fc074bb6\n"
            "loc_fc074a3e:\n"
            "    movs    r0, #1\n"
            "    bl      sub_fc0830ca\n"
            "    b       loc_fc074bb6\n"
            "loc_fc074a46:\n"
            "    bl      sub_fc082aec\n"
            "    b       loc_fc074a52\n"
            "loc_fc074a4c:\n"
            "    ldr     r0, [r0, #0xc]\n"
            "    bl      sub_fc082d7e\n"
            "loc_fc074a52:\n"
            "    str     r6, [r4, #0x28]\n"
            "    b       loc_fc074bb6\n"
            "loc_fc074a56:\n"
            "    bl      sub_fc082d84\n"
            "    b       loc_fc074bb6\n"
            "loc_fc074a5c:\n"
            "    bl      sub_fc082fec\n"
            "    bl      sub_fc08fbe8\n"
            "    b       loc_fc074bb6\n"
            "loc_fc074a66:\n"
            "    ldr     r0, [r0, #0x10]\n"
            "    bl      sub_fc08ecce\n"
            "    b       loc_fc074bb6\n"
            "loc_fc074a6e:\n"
            "    bl      sub_fc08306a\n"
            "    bl      sub_fc08fbe8\n"
            "    movs    r0, #0\n"
            "    bl      sub_fc2d27d8\n"
            "    b       loc_fc074bb6\n"
            "loc_fc074a7e:\n"
            "    ldr     r0, [r4, #0x54]\n"
            "    bl      sub_fc083732\n"
            "    b       loc_fc074bb6\n"
            "loc_fc074a86:\n"
            "    bl      sub_fc0839ce\n"
            "    b       loc_fc074bb6\n"
            "loc_fc074a8c:\n"
            "    ldr     r0, [r0, #0xc]\n"
            "    bl      sub_fc083a1a\n"
            "    b       loc_fc074bb6\n"
            "loc_fc074a94:\n"
            "    bl      sub_fc083bfc\n"
            "    b       loc_fc074bb6\n"
            "loc_fc074a9a:\n"
            "    bl      sub_fc083fe4\n"
            "    b       loc_fc074bb6\n"
            "loc_fc074aa0:\n"
            "    bl      sub_fc08407a\n"
            "    b       loc_fc074bb6\n"
            "loc_fc074aa6:\n"
            "    bl      sub_fc086d00\n"
            "    b       loc_fc074bb6\n"
            "loc_fc074aac:\n"
            "    bl      sub_fc086ede\n"
            "    b       loc_fc074bb6\n"
            "loc_fc074ab2:\n"
            "    bl      sub_fc086f7c\n"
            "    b       loc_fc074bb6\n"
            "loc_fc074ab8:\n"
            "    b       loc_fc074ba8\n"
            "loc_fc074aba:\n"
            "    bl      sub_fc086ff8\n"
            "    b       loc_fc074bb6\n"
            "loc_fc074ac0:\n"
            "    movs    r0, #0\n"
            "    b       loc_fc074ae4\n"
            "loc_fc074ac4:\n"
            "    bl      sub_fc08719c\n"
            "    b       loc_fc074bb6\n"
            "loc_fc074aca:\n"
            "    bl      sub_fc0871fc\n"
            "    b       loc_fc074bb6\n"
            "loc_fc074ad0:\n"
            "    bl      sub_fc087200\n"
            "    b       loc_fc074bb6\n"
            "loc_fc074ad6:\n"
            "    bl      sub_fc087210\n"
            "    b       loc_fc074bb6\n"
            "loc_fc074adc:\n"
            "    bl      sub_fc08729a\n"
            "    b       loc_fc074bb6\n"
            "loc_fc074ae2:\n"
            "    movs    r0, #1\n"
            "loc_fc074ae4:\n"
            "    bl      sub_fc08707c\n"
            "    b       loc_fc074bb6\n"
            "loc_fc074aea:\n"
            "    bl      sub_fc087344\n"
            "    b       loc_fc074bb6\n"
            "loc_fc074af0:\n"
            "    bl      sub_fc0831ba\n"
            "    b       loc_fc074bb6\n"
            "loc_fc074af6:\n"
            "    movs    r0, #0\n"
            "    b       loc_fc074afc\n"
            "loc_fc074afa:\n"
            "    ldr     r0, [r0, #0xc]\n"
            "loc_fc074afc:\n"
            "    bl      sub_fc0831ee\n"
            "    b       loc_fc074bb6\n"
            "loc_fc074b02:\n"
            "    bl      sub_fc08b514\n"
            "    b       loc_fc074bb6\n"
            "loc_fc074b08:\n"
            "    ldr     r1, =0x00046f46\n"
            "    movs    r2, #2\n"
            "    movs    r0, #0x77\n"
            "    bl      sub_fc3b835e\n"
            "    lsls    r0, r0, #0x1f\n"
            "    beq     loc_fc074b24\n"
            "    movw    r2, #0x4ee\n"
            "    ldr     r1, =0xfc07459c\n" //  *"SsShootTask.c"
            "    movs    r0, #0\n"
            "    blx     sub_fc34d264\n"
            "loc_fc074b24:\n"
            "    ldrh.w  r0, [r4, #0x62]\n"
            "    cmp     r0, #1\n"
            "    bne     loc_fc074bb6\n"
            "    bl      sub_fc08b50e\n"
            "    b       loc_fc074bb6\n"
            "loc_fc074b32:\n"
            "    bl      sub_fc08b598\n"
            "    b       loc_fc074bb6\n"
            "loc_fc074b38:\n"
            "    bl      sub_fc091c38\n"
            "    b       loc_fc074bb6\n"
            "loc_fc074b3e:\n"
            "    bl      sub_fc084504\n"
            "    b       loc_fc074bb6\n"
            "loc_fc074b44:\n"
            "    bl      sub_fc0845be\n"
            "    b       loc_fc074bb6\n"
            "loc_fc074b4a:\n"
            "    ldr     r0, [r0, #0xc]\n"
            "    bl      sub_fc0873f8\n"
            "    b       loc_fc074bb6\n"
            "loc_fc074b52:\n"
            "    bl      sub_fc08744a\n"
            "    b       loc_fc074bb6\n"
            "loc_fc074b58:\n"
            "    bl      sub_fc07d1ea\n"
            "    ldrh.w  r0, [r4, #0x19c]\n"
            "    cmp     r0, #4\n"
            "    beq     loc_fc074b6e\n"
            "    ldrh    r0, [r4]\n"
            "    sub.w   r1, r0, #0x8200\n"
            "    subs    r1, #0x36\n"
            "    bne     loc_fc074bb6\n"
            "loc_fc074b6e:\n"
            "    bl      sub_fc0845be\n"
            "    bl      sub_fc084a2e\n"
            "    b       loc_fc074bb6\n"
            "loc_fc074b78:\n"
            "    bl      sub_fc08427e\n"
            "    movs    r0, #1\n"
            "    bl      sub_fc07ce46\n"
            "    b       loc_fc074bb6\n"
            "loc_fc074b84:\n"
            "    movs    r2, #0\n"
            "    movs    r1, #0x11\n"
            "    b       loc_fc074b8e\n"
            "loc_fc074b8a:\n"
            "    movs    r2, #0\n"
            "    movs    r1, #0x10\n"
            "loc_fc074b8e:\n"
            "    movs    r0, #0\n"
            "    bl      sub_fc090918\n"
            "    b       loc_fc074bb6\n"
            "loc_fc074b96:\n"
            "    bl      sub_fc08367e\n"
            "    b       loc_fc074bb6\n"
            "loc_fc074b9c:\n"
            "    bl      sub_fc087cf0\n"
            "    b       loc_fc074bb6\n"
            "loc_fc074ba2:\n"
            "    bl      sub_fc087cf2\n"
            "    b       loc_fc074bb6\n"
            "loc_fc074ba8:\n"
            "    movw    r2, #0x557\n"
            "    ldr     r1, =0xfc07459c\n" //  *"SsShootTask.c"
            "    movs    r0, #0\n"
            "    blx     sub_fc34d264\n"
            "loc_fc074bb6:\n"
            "    BL      capt_seq_hook_set_nr\n" //  dark frame control
            "    ldr     r0, [sp]\n"
            "    ldr     r1, [r0, #4]\n"
            "    ldr     r0, [r5, #4]\n"
            "    blx     sub_fc34d10c\n"
            "    ldr     r7, [sp]\n"
            "    ldr     r0, [r7, #8]\n"
            "    cbnz    r0, loc_fc074bd2\n"
            "    movs    r2, #0xff\n"
            "    ldr     r1, =0xfc07459c\n" //  *"SsShootTask.c"
            "    movs    r0, #0\n"
            "    blx     sub_fc34d264\n"
            "loc_fc074bd2:\n"
            "    str     r6, [r7, #8]\n"
            "    b       loc_fc074994\n"
    );
}

//fc08ec20
void __attribute__((naked,noinline))
sub_fc08ec20_my ()
{
    asm volatile (
            //capdis -f=chdk -s=0xfc08ec21 -c=58 -stubs PRIMARY.BIN 0xfc000000
            "    push    {r3, r4, r5, r6, r7, lr}\n"
            "    bl      sub_fc0932c2\n"
            "    mov     r4, r0\n"
            "    movs    r0, #0xc\n"
            "    bl      sub_fc318e68\n"
            "    ldr     r6, =0x000156a4\n"
            "    lsls    r0, r0, #0x1f\n"
            "    mov.w   r5, #1\n"
            "    bne     loc_fc08ecbe\n"
            "    movs    r2, #2\n"
            "    mov     r1, sp\n"
            "    movw    r0, #0x112\n"
            "    bl      sub_fc3b835e\n"
            "    lsls    r0, r0, #0x1f\n"
            "    beq     loc_fc08ec54\n"
            "    movs    r0, #0\n"
            "    movw    r2, #0x189\n"
            "    ldr     r1, =0xfc08eda4\n" //  *"SsCaptureCtrl.c"
            "    blx     sub_fc34d264\n"
            "loc_fc08ec54:\n"
            "    ldrsh.w r0, [sp]\n"
            "    bl      sub_fc0c296a\n"
            "    bl      sub_fc0c2702\n"
            "    cmp     r0, #1\n"
            "    bls     loc_fc08ecc2\n"
            "    movs    r0, #0\n"
            "    bl      sub_fc0c283a\n"
            "    bl      sub_fc0b9ef8\n"
            "    bl      sub_fc082d8a\n"
            "    bl      sub_fc09bef4\n"
            "    mov     r1, r4\n"
            //"    bl      sub_fc09bf48\n" // -
            "    bl      captseq_raw_addr_init_my\n" // Replace above call
            "    movs    r2, #4\n"
            "    movw    r0, #0x118\n"
            "    add.w   r1, r4, #0x58\n"
            "    bl      sub_fc3b822a\n"
            "    movs    r2, #4\n"
            "    movs    r0, #0x32\n"
            "    add.w   r1, r4, #0x5c\n"
            "    bl      sub_fc3b822a\n"
            "    movs    r2, #4\n"
            "    movs    r0, #0x46\n"
            "    add.w   r1, r4, #8\n"
            "    bl      sub_fc3b822a\n"
            "    bl      sub_fc0991aa\n"
            "    mvn     r1, #0x1000\n"
            "    blx     sub_fc34d1e4\n"
            "    mov     r0, r4\n"
            "    bl      sub_fc091984\n"
            "    mov     r0, r4\n"
            "    bl      sub_fc0a009e_my\n" // -> remote hook, raw hook
            "    lsls    r0, r0, #0x1f\n"
            "    beq     loc_fc08ecc0\n"
            "loc_fc08ecbe:\n"
            "    str     r5, [r6]\n"
            "loc_fc08ecc0:\n"
            "    pop     {r3, r4, r5, r6, r7, pc}\n"
            "loc_fc08ecc2:\n"
            "    str     r5, [r6]\n"
            "    bl      sub_fc090634\n"
            "    bl      sub_fc318ea8\n"
            "    pop     {r3, r4, r5, r6, r7, pc}\n"
    );
}

//fc08ebd4
void __attribute__((naked,noinline))
sub_fc08ebd4_my ()
{
    asm volatile (
            //capdis -f=chdk -s=0xfc08ebd5 -c=33 -stubs PRIMARY.BIN 0xfc000000
            "    push    {r4, r5, r6, lr}\n"
            "    ldr     r5, =0x00046ee4\n"
            "    mov     r6, r0\n"
            "    movs    r4, #0\n"
            "    ldr     r0, [r5, #0x28]\n"
            "    cbz     r0, loc_fc08ebfc\n"
            "    ldr     r0, =0x000156a4\n"
            "    ldr     r0, [r0]\n"
            "    cbz     r0, loc_fc08ebe8\n"
            "    movs    r4, #0x1d\n"
            "loc_fc08ebe8:\n"
            "    mov     r2, r6\n"
            "    movs    r1, #2\n"
            "    mov     r0, r4\n"
            "    bl      sub_fc090918\n"
            "    mov     r1, r4\n"
            "    mov     r0, r6\n"
            "    bl      sub_fc09ddb8\n"
            "    b       loc_fc08ec1a\n"
            "loc_fc08ebfc:\n"
            "    mov     r0, r6\n"
            "    bl      sub_fc08e9e6_my\n" // Patched
            "    mov     r4, r0\n"
            "    lsls    r0, r0, #0x1f\n"
            "    beq     loc_fc08ec1a\n"
            "    movs    r1, #2\n"
            "    mov     r2, r6\n"
            "    mov     r0, r4\n"
            "    bl      sub_fc090918\n"
            "    mov     r1, r4\n"
            "    mov     r0, r6\n"
            "    bl      sub_fc09deee\n"
            "loc_fc08ec1a:\n"
            "    movs    r0, #0\n"
            "    str     r0, [r5, #0x28]\n"
            "    pop     {r4, r5, r6, pc}\n"
    );
}

//fc08e9e6
void __attribute__((naked,noinline))
sub_fc08e9e6_my ()
{
    asm volatile (
            //capdis -f=chdk -s=0xfc08e9e7 -c=180 -stubs PRIMARY.BIN 0xfc000000
            "    push.w  {r2, r3, r4, r5, r6, r7, r8, lr}\n"
            "    mov     r4, r0\n"
            "    bl      sub_fc09bef4\n"
            "    mov     r1, r4\n"
            //"    bl      sub_fc09bf48\n" // -
            "    bl      captseq_raw_addr_init_my\n" // Replace above call
            "    movs    r2, #4\n"
            "    movw    r0, #0x118\n"
            "    add.w   r1, r4, #0x58\n"
            "    bl      sub_fc3b822a\n"
            "    movs    r2, #4\n"
            "    movs    r0, #0x32\n"
            "    add.w   r1, r4, #0x5c\n"
            "    bl      sub_fc3b822a\n"
            "    ldr     r6, =0x00046ee4\n"
            "    ldr.w   r0, [r6, #0x104]\n"
            "    cbnz    r0, loc_fc08ea28\n"
            "    ldrh.w  r0, [r6, #0x19a]\n"
            "    cmp     r0, #3\n"
            "    beq     loc_fc08ea2e\n"
            "    ldr     r0, [r4, #8]\n"
            "    cmp     r0, #1\n"
            "    bhi     loc_fc08ea3e\n"
            "    b       loc_fc08ea2e\n"
            "loc_fc08ea28:\n"
            "    ldr     r0, [r4, #0xc]\n"
            "    cmp     r0, #1\n"
            "    bne     loc_fc08ea3e\n"
            "loc_fc08ea2e:\n"
            "    movs    r0, #0xc\n"
            "    bl      sub_fc318e68\n"
            "    lsls    r0, r0, #0x1f\n"
            "    beq     loc_fc08ea3e\n"
            "loc_fc08ea38:\n"
            "    bl      sub_fc090634\n"
            "    b       loc_fc08eb52\n"
            "loc_fc08ea3e:\n"
            "    ldr.w   r0, [r6, #0xe4]\n"
            "    cbz     r0, loc_fc08ea5e\n"
            "    ldrh.w  r0, [r6, #0x19a]\n"
            "    cmp     r0, #3\n"
            "    beq     loc_fc08ea52\n"
            "    ldr     r0, [r4, #8]\n"
            "    cmp     r0, #1\n"
            "    bhi     loc_fc08ea8e\n"
            "loc_fc08ea52:\n"
            "    ldr.w   r0, [r6, #0x104]\n"
            "    cbz     r0, loc_fc08ea5e\n"
            "    ldr     r0, [r4, #0xc]\n"
            "    cmp     r0, #1\n"
            "    bhi     loc_fc08ea8e\n"
            "loc_fc08ea5e:\n"
            "    movs    r2, #2\n"
            "    movw    r0, #0x112\n"
            "    add     r1, sp, #4\n"
            "    bl      sub_fc3b835e\n"
            "    lsls    r0, r0, #0x1f\n"
            "    beq     loc_fc08ea78\n"
            "    movs    r2, #0xc1\n"
            "    movs    r0, #0\n"
            "    ldr     r1, =0xfc08eda4\n" //  *"SsCaptureCtrl.c"
            "    blx     sub_fc34d264\n"
            "loc_fc08ea78:\n"
            "    ldrsh.w r0, [sp, #4]\n"
            "    bl      sub_fc0c296a\n"
            "    bl      sub_fc0c2702\n"
            "    cmp     r0, #1\n"
            "    bls     loc_fc08eb4a\n"
            "    movs    r0, #0\n"
            "    bl      sub_fc0c283a\n"
            "loc_fc08ea8e:\n"
            "    ldr.w   r0, [r6, #0x1c4]\n"
            "    cbz     r0, loc_fc08eaa4\n"
            "    ldr     r0, [r4, #8]\n"
            "    cmp     r0, #1\n"
            "    beq     loc_fc08eaa4\n"
            "    movs    r0, #1\n"
            "    bl      sub_fc07ce46\n"
            "    lsls    r0, r0, #0x1f\n"
            "    bne     loc_fc08ea38\n"
            "loc_fc08eaa4:\n"
            "    mov     r0, r4\n"
            "    bl      sub_fc091c78\n"
            "    lsls    r1, r0, #0x1f\n"
            "    bne     loc_fc08eb54\n"
            "    bl      sub_fc0991aa\n"
            "    mvn     r1, #0x1000\n"
            "    blx     sub_fc34d1e4\n"
            "    mov     r0, r4\n"
            "    bl      sub_fc08f226\n"
            "    mov     r5, r0\n"
            "    lsls    r0, r0, #0x1f\n"
            "    bne     loc_fc08ebac\n"
            "    bl      sub_fc0b9ef8\n"
            "    bl      sub_fc082d8a\n"
            "    mov     r0, r4\n"
            "    bl      sub_fc091984\n"
            "    ldr.w   r0, [r6, #0x128]\n"
            "    cbnz    r0, loc_fc08eae8\n"
            "    ldrh.w  r0, [r6, #0x19a]\n"
            "    cmp     r0, #3\n"
            "    beq     loc_fc08eae8\n"
            "    ldr     r0, [r4, #8]\n"
            "    cmp     r0, #1\n"
            "    bhi     loc_fc08eaee\n"
            "loc_fc08eae8:\n"
            "    movs    r0, #2\n"
            "    bl      sub_fc089502\n"
            "loc_fc08eaee:\n"
            "    ldr.w   r0, [r6, #0xa0]\n"
            "    cmp     r0, #0\n"
            "    beq     loc_fc08eb6e\n"
            "    ldrh.w  r0, [r6, #0x19a]\n"
            "    movw    r7, #0x1000\n"
            "    cmp     r0, #3\n"
            "    beq     loc_fc08eb1e\n"
            "    ldr     r0, [r4, #8]\n"
            "    cmp     r0, #1\n"
            "    bls     loc_fc08eb1e\n"
            "    bl      sub_fc0991aa\n"
            "    movw    r3, #0x111\n"
            "    movw    r2, #0x3a98\n"
            "    mov     r1, r7\n"
            "    str     r3, [sp]\n"
            "    ldr     r3, =0xfc08eda4\n" //  *"SsCaptureCtrl.c"
            "    bl      sub_fc319020\n"
            "loc_fc08eb1e:\n"
            "    movs    r2, #4\n"
            "    movw    r0, #0x18a\n"
            "    add     r1, sp, #4\n"
            "    bl      sub_fc3b835e\n"
            "    lsls    r0, r0, #0x1f\n"
            "    beq     loc_fc08eb3a\n"
            "    movs    r0, #0\n"
            "    movw    r2, #0x115\n"
            "    ldr     r1, =0xfc08eda4\n" //  *"SsCaptureCtrl.c"
            "    blx     sub_fc34d264\n"
            "loc_fc08eb3a:\n"
            "    ldr     r0, [sp, #4]\n"
            "    cbnz    r0, loc_fc08eb58\n"
            "    bl      sub_fc0991aa\n"
            "    mov     r1, r7\n"
            "    blx     sub_fc34d10c\n"
            "    b       loc_fc08eb6e\n"
            "loc_fc08eb4a:\n"
            "    bl      sub_fc090634\n"
            "    bl      sub_fc318ea8\n"
            "loc_fc08eb52:\n"
            "    movs    r0, #1\n"
            "loc_fc08eb54:\n"
            "    pop.w   {r2, r3, r4, r5, r6, r7, r8, pc}\n"
            "loc_fc08eb58:\n"
            "    bl      sub_fc0991aa\n"
            "    mov     r1, r7\n"
            "    blx     sub_fc34d1e4\n"
            "    ldr     r2, =0xfc08e9d5\n"
            "    mov     r3, r7\n"
            "    ldr     r0, [sp, #4]\n"
            "    mov     r1, r2\n"
            "    bl      sub_fc3ba99a\n"
            "loc_fc08eb6e:\n"
            "    ldr.w   r0, [r6, #0xa8]\n"
            "    cbz     r0, loc_fc08eb7c\n"
            "    mov     r0, r4\n"
            "    bl      sub_fc0a093c\n"
            "    b       loc_fc08ebc2\n"
            "loc_fc08eb7c:\n"
            "    ldr.w   r0, [r6, #0xac]\n"
            "    cbz     r0, loc_fc08eb8a\n"
            "    mov     r0, r4\n"
            "    bl      sub_fc0a05b2\n"
            "    b       loc_fc08ebc2\n"
            "loc_fc08eb8a:\n"
            "    ldr.w   r0, [r6, #0xb0]\n"
            "    cbz     r0, loc_fc08eb98\n"
            "    mov     r0, r4\n"
            "    bl      sub_fc0a0c40\n"
            "    b       loc_fc08ebc2\n"
            "loc_fc08eb98:\n"
            "    ldr.w   r0, [r6, #0xb4]\n"
            "    cbz     r0, loc_fc08ebae\n"
            "    ldr     r0, =0x000470e8\n"
            "    ldr     r0, [r0]\n"
            "    cbz     r0, loc_fc08ebae\n"
            "    mov     r0, r4\n"
            "    bl      sub_fc0a0f3a\n"
            "    b       loc_fc08ebc2\n"
            "loc_fc08ebac:\n"
            "    b       loc_fc08ebd0\n"
            "loc_fc08ebae:\n"
            "    ldr.w   r0, [r6, #0xb8]\n"
            "    cmp     r0, #0\n"
            "    mov     r0, r4\n"
            "    beq     loc_fc08ebbe\n"
            "    bl      sub_fc0a122e\n"
            "    b       loc_fc08ebc2\n"
            "loc_fc08ebbe:\n"
            "    bl      sub_fc0a009e_my\n" // -> remote hook, raw hook
            "loc_fc08ebc2:\n"
            "    ldr.w   r0, [r6, #0x1c4]\n"
            "    cbz     r0, loc_fc08ebd0\n"
            "    movs    r1, #0\n"
            "    movs    r0, #1\n"
            "    bl      sub_fc07ce8c\n"
            "loc_fc08ebd0:\n"
            "    mov     r0, r5\n"
            "    b       loc_fc08eb54\n"
    );
}

//fc0a009e
void __attribute__((naked,noinline))
sub_fc0a009e_my ()
{
    asm volatile (
            //capdis -f=chdk -s=0xfc0a009f -c=249 -stubs PRIMARY.BIN 0xfc000000
            "    push.w  {r0, r1, r2, r3, r4, r5, r6, r7, r8, sb, sl, lr}\n"
            "    ldr     r7, =0x00046ee4\n"
            "    mov     r4, r0\n"
            "    ldr.w   r0, [r7, #0x164]\n"
            "    cbz     r0, loc_fc0a00ba\n"
            "    ldrh.w  r0, [r7, #0x19a]\n"
            "    cmp     r0, #3\n"
            "    beq     loc_fc0a00ba\n"
            "    ldr     r0, [r4, #8]\n"
            "    cmp     r0, #1\n"
            "    bhi     loc_fc0a00c4\n"
            "loc_fc0a00ba:\n"
            "    mov     r0, r4\n"
            "    bl      sub_fc09191a\n"
            "    bl      sub_fc087912\n"
            "loc_fc0a00c4:\n"
            "    ldr.w   r0, [r7, #0x9c]\n"
            "    cbnz    r0, loc_fc0a00e0\n"
            "    ldrh.w  r0, [r7, #0x19a]\n"
            "    cmp     r0, #3\n"
            "    beq     loc_fc0a00d8\n"
            "    ldr     r0, [r4, #8]\n"
            "    cmp     r0, #1\n"
            "    bhi     loc_fc0a00e0\n"
            "loc_fc0a00d8:\n"
            "    bl      sub_fc0831dc\n"
            "    bl      sub_fc0874de\n"
            "loc_fc0a00e0:\n"
            "    movs    r2, #4\n"
            "    movw    r0, #0x139\n"
            "    add     r1, sp, #0xc\n"
            "    bl      sub_fc3b835e\n"
            "    lsls    r0, r0, #0x1f\n"
            "    beq     loc_fc0a00fc\n"
            "    movs    r0, #0\n"
            "    movw    r2, #0x153\n"
            "    ldr     r1, =0xfc0a0474\n" //  *"SsStandardCaptureSeq.c"
            "    blx     sub_fc34d264\n"
            "loc_fc0a00fc:\n"
            "    ldr     r0, [sp, #0xc]\n"
            "    ubfx    r0, r0, #8, #8\n"
            "    cmp     r0, #6\n"
            "    bne     loc_fc0a010c\n"
            "    ldr     r0, =0xfc0a0055\n"
            "    movs    r1, #0\n"
            "    b       loc_fc0a0110\n"
            "loc_fc0a010c:\n"
            "    ldr     r0, =0xfc09159d\n"
            "    mov     r1, r4\n"
            "loc_fc0a0110:\n"
            "    bl      sub_fc0ace52\n"
            "    movs    r2, #2\n"
            "    movw    r0, #0x114\n"
            "    add     r1, sp, #8\n"
            "    bl      sub_fc3b835e\n"
            "    lsls    r0, r0, #0x1f\n"
            "    beq     loc_fc0a0130\n"
            "    movs    r0, #0\n"
            "    movw    r2, #0x15c\n"
            "    ldr     r1, =0xfc0a0474\n" //  *"SsStandardCaptureSeq.c"
            "    blx     sub_fc34d264\n"
            "loc_fc0a0130:\n"
            "    ldr.w   r0, [r7, #0x184]\n"
            "    cbz     r0, loc_fc0a013a\n"
            "    bl      sub_fc091852\n"
            "loc_fc0a013a:\n"
            "    movs    r0, #0\n"
            "    bl      sub_fc07ce3e\n"
            "    mov     r0, r4\n"
            "    bl      sub_fc091a4a\n"
            "    movs    r2, #4\n"
            "    movs    r0, #0x92\n"
            "    add     r1, sp, #4\n"
            "    bl      sub_fc3b835e\n"
            "    lsls    r0, r0, #0x1f\n"
            "    beq     loc_fc0a0160\n"
            "    movs    r0, #0\n"
            "    movw    r2, #0x171\n"
            "    ldr     r1, =0xfc0a0474\n" //  *"SsStandardCaptureSeq.c"
            "    blx     sub_fc34d264\n"
            "loc_fc0a0160:\n"
            "    ldr     r1, =0x00027fe0\n"
            "    ldr     r0, [sp, #4]\n"
            "    str     r0, [r1]\n"
            "    bl      sub_fc07cef8\n"
            "    bl      sub_fc091adc\n"
            "    movs    r1, #0\n"
            "    mov     r0, r4\n"
            "    bl      sub_fc0a0056\n"
            "    mov     r6, r0\n"
            "    BL      wait_until_remote_button_is_released\n" // + remote hook
            "    ldr     r0, [sp, #0xc]\n"
            "    ubfx    r0, r0, #8, #8\n"
            "    cmp     r0, #6\n"
            "    bne     loc_fc0a0186\n"
            "    ldr     r2, =0xfc09181d\n"
            "    b       loc_fc0a0188\n"
            "loc_fc0a0186:\n"
            "    ldr     r2, =0xfc091833\n"
            "loc_fc0a0188:\n"
            "    ldrh    r0, [r4, #0x18]\n"
            "    ldr.w   r8, =0xfffff3a0\n"
            "    cbz     r0, loc_fc0a0198\n"
            "    cmp     r0, #1\n"
            "    beq     loc_fc0a01ae\n"
            "    cmp     r0, #4\n"
            "    bne     loc_fc0a021c\n"
            "loc_fc0a0198:\n"
            "    str     r6, [sp]\n"
            "    mov     r3, r2\n"
            "    ldr     r1, [r4, #0x5c]\n"
            "    mov     r0, r4\n"
            "    ldr     r2, [sp, #4]\n"
            "    bl      sub_fc0913c4\n"
            "    mov     r5, r0\n"
            "    bl      sub_fc0feba4\n"
            "    b       loc_fc0a022a\n"
            "loc_fc0a01ae:\n"
            "    str     r6, [sp]\n"
            "    mov     r3, r2\n"
            "    ldr     r1, [r4, #0x5c]\n"
            "    mov     r0, r4\n"
            "    ldr     r2, [sp, #4]\n"
            "    bl      sub_fc091432\n"
            "    mov     r5, r0\n"
            "    ldrsh.w r0, [sp, #8]\n"
            "    cmp     r0, r8\n"
            "    beq     loc_fc0a01cc\n"
            "    bl      sub_fc0ace20\n"
            "    cbnz    r0, loc_fc0a01d6\n"
            "loc_fc0a01cc:\n"
            "    movs    r2, #1\n"
            "    movs    r1, #0\n"
            "    movs    r0, #0x45\n"
            "    bl      sub_fc2d4488\n"
            "loc_fc0a01d6:\n"
            "    lsls    r0, r5, #0x1f\n"
            "    bne     loc_fc0a022a\n"
            "    ldr.w   r0, [r7, #0xf8]\n"
            "    cbz     r0, loc_fc0a01f0\n"
            "    ldr     r1, [r4, #8]\n"
            "    ldr     r2, =0x001e3538\n"
            "    ldr     r0, [r4, #0x5c]\n"
            "    add.w   r1, r2, r1, lsl #2\n"
            "    str     r0, [r1, #-0x4]\n"
            "    b       loc_fc0a0216\n"
            "loc_fc0a01f0:\n"
            "    ldr     r0, =0xfc0a0055\n"
            "    movs    r1, #0\n"
            "    bl      sub_fc0ace52\n"
            "    movs    r1, #1\n"
            "    mov     r0, r4\n"
            "    bl      sub_fc0a0056\n"
            "    mov     r6, r0\n"
            "    ldr     r0, [sp, #4]\n"
            "    bl      sub_fc0918bc\n"
            "    ldr     r1, [r4, #0x5c]\n"
            "    mov     r3, r6\n"
            "    ldr     r2, [sp, #4]\n"
            "    mov     r0, r4\n"
            "    bl      sub_fc0914aa\n"
            "    mov     r5, r0\n"
            "loc_fc0a0216:\n"
            "    bl      sub_fc09136c\n"
            "    b       loc_fc0a022a\n"
            "loc_fc0a021c:\n"
            "    movs    r0, #0\n"
            "    movw    r2, #0x1ad\n"
            "    ldr     r1, =0xfc0a0474\n" //  *"SsStandardCaptureSeq.c"
            "    blx     sub_fc34d264\n"
            "    movs    r5, #0x1d\n"
            "loc_fc0a022a:\n"
            "    ldrsh.w r0, [sp, #8]\n"
            "    cmp     r0, r8\n"
            "    beq     loc_fc0a0244\n"
            "    bl      sub_fc0ace20\n"
            "    cbz     r0, loc_fc0a0244\n"
            "    movs    r2, #1\n"
            "    movs    r1, #0\n"
            "    movs    r0, #0x46\n"
            "    bl      sub_fc2d4488\n"
            "    movs    r5, #1\n"
            "loc_fc0a0244:\n"
            "    bl      sub_fc091ae0\n"
            "    ldr.w   r8, =0xfc0a0055\n"
            "    lsls    r0, r5, #0x1f\n"
            "    bne     loc_fc0a02be\n"
            "    ldr.w   r0, [r7, #0x100]\n"
            "    cbnz    r0, loc_fc0a028a\n"
            "    ldr.w   r0, [r7, #0x1c4]\n"
            "    cbz     r0, loc_fc0a0274\n"
            "    ldrh.w  r0, [r7, #0x1e4]\n"
            "    cmp     r0, #1\n"
            "    bne     loc_fc0a028a\n"
            "    mov     r0, r4\n"
            "    bl      sub_fc0922ba\n"
            "    lsls    r0, r0, #0x1f\n"
            "    beq     loc_fc0a028a\n"
            "    movw    r2, #0x1c9\n"
            "    b       loc_fc0a0282\n"
            "loc_fc0a0274:\n"
            "    mov     r0, r4\n"
            "    bl      sub_fc0922ba\n"
            "    lsls    r0, r0, #0x1f\n"
            "    beq     loc_fc0a028a\n"
            "    movw    r2, #0x1cc\n"
            "loc_fc0a0282:\n"
            "    movs    r0, #0\n"
            "    ldr     r1, =0xfc0a0474\n" //  *"SsStandardCaptureSeq.c"
            "    blx     sub_fc34d264\n"
            "loc_fc0a028a:\n"
            "    BL      capt_seq_hook_raw_here\n" // +
            "    BL      clear_current_raw_addr\n" // +
            "    mov     r0, r4\n"
            "    bl      sub_fc091acc\n"
            "    mov     r0, r4\n"
            "    bl      sub_fc091aa0\n"
            "    cmp     r6, r8\n"
            "    beq     loc_fc0a02be\n"
            "    bl      sub_fc0991aa\n"
            "    movs    r1, #4\n"
            "    movw    sb, #0x1dc\n"
            "    ldr     r3, =0xfc0a0474\n" //  *"SsStandardCaptureSeq.c"
            "    movw    r2, #0x3a98\n"
            "    str.w   sb, [sp]\n"
            "    bl      sub_fc319020\n"
            "    cbz     r0, loc_fc0a02be\n"
            "    movs    r0, #0\n"
            "    mov     r2, sb\n"
            "    ldr     r1, =0xfc0a0474\n" //  *"SsStandardCaptureSeq.c"
            "    blx     sub_fc34d264\n"
            "loc_fc0a02be:\n"
            "    ldrh    r0, [r7]\n"
            "    sub.w   r1, r0, #0x4000\n"
            "    subs    r1, #0x44\n"
            "    bne     loc_fc0a02e0\n"
            "    bl      sub_fc0991aa\n"
            "    movw    r1, #0x8000\n"
            "    blx     sub_fc34d1e4\n"
            "    ldr     r0, =0xfc0a008d\n"
            "    movs    r1, #0\n"
            "    bl      sub_fc2d4b54\n"
            "    bl      sub_fc2d4b46\n"
            "loc_fc0a02e0:\n"
            "    ldr.w   r0, [r7, #0x184]\n"
            "    cbz     r0, loc_fc0a02f0\n"
            "    movs    r2, #1\n"
            "    movs    r1, #0\n"
            "    movs    r0, #0x46\n"
            "    bl      sub_fc2d4488\n"
            "loc_fc0a02f0:\n"
            "    movs    r1, #2\n"
            "    mov     r2, r4\n"
            "    mov     r0, r5\n"
            "    bl      sub_fc090918\n"
            "    ldr     r0, [r7, #0x28]\n"
            "    cmp     r0, #0\n"
            "    mov     r0, r8\n"
            "    beq     loc_fc0a0316\n"
            "    cmp     r6, r0\n"
            "    beq     loc_fc0a030a\n"
            "    movs    r1, #1\n"
            "    b       loc_fc0a030c\n"
            "loc_fc0a030a:\n"
            "    movs    r1, #0\n"
            "loc_fc0a030c:\n"
            "    mov     r2, r5\n"
            "    mov     r0, r4\n"
            "    bl      sub_fc09dd76\n"
            "    b       loc_fc0a0328\n"
            "loc_fc0a0316:\n"
            "    cmp     r6, r0\n"
            "    beq     loc_fc0a031e\n"
            "    movs    r1, #1\n"
            "    b       loc_fc0a0320\n"
            "loc_fc0a031e:\n"
            "    movs    r1, #0\n"
            "loc_fc0a0320:\n"
            "    mov     r2, r5\n"
            "    mov     r0, r4\n"
            "    bl      sub_fc09dd30\n"
            "loc_fc0a0328:\n"
            "    add     sp, #0x10\n"
            "    mov     r0, r5\n"
            "    pop.w   {r4, r5, r6, r7, r8, sb, sl, pc}\n"
    );
}

// TODO:
// task_DvlpSeq 0xfc091e67
void __attribute__((naked,noinline))
developseq_task ()
{
    asm volatile (
            "    nop\n"
    );
}

// exp_drv_task 0xfc2f63ef
void __attribute__((naked,noinline))
exp_drv_task ()
{
    asm volatile (
            //capdis -f=chdk -s=0xfc2f63ef -c=258 -stubs PRIMARY.BIN 0xfc000000
            "    push.w  {r4, r5, r6, r7, r8, sb, sl, fp, lr}\n"
            "    sub     sp, #0x2c\n"
            "    ldr.w   sl, =0x0000e89c\n"
            "    ldr.w   fp, =0xfffff400\n"
            "    movs    r0, #0\n"
            "    ldr.w   r8, =0x0006ee40\n"
            "    movs    r4, #0x3e\n"
            "    add.w   sb, sp, #0x1c\n"
            "    str     r0, [sp, #0xc]\n"
            "loc_fc2f640a:\n"
            "    ldr.w   r0, [sl, #0x20]\n"
            "    movs    r2, #0\n"
            "    add     r1, sp, #0x28\n"
            "    mov     r5, sl\n"
            "    blx     sub_fc34d054\n"
            "    ldr     r0, [sp, #0x28]\n"
            "    movs    r1, #0\n"
            "    cmp     r4, #0x15\n"
            "    ldr     r0, [r0]\n"
            "    beq     loc_fc2f6436\n"
            "    cmp     r4, #0x16\n"
            "    beq     loc_fc2f6436\n"
            "    cmp     r4, #0x17\n"
            "    beq     loc_fc2f6436\n"
            "    cmp     r4, #0x18\n"
            "    beq     loc_fc2f6436\n"
            "    cmp     r4, #0x19\n"
            "    beq     loc_fc2f6436\n"
            "    cmp     r4, #0x1a\n"
            "    bne     loc_fc2f6458\n"
            "loc_fc2f6436:\n"
            "    cmp     r0, #0x15\n"
            "    beq     loc_fc2f6458\n"
            "    cmp     r0, #0x16\n"
            "    beq     loc_fc2f6458\n"
            "    cmp     r0, #0x17\n"
            "    beq     loc_fc2f6458\n"
            "    cmp     r0, #0x18\n"
            "    beq     loc_fc2f6458\n"
            "    cmp     r0, #0x19\n"
            "    beq     loc_fc2f6458\n"
            "    cmp     r0, #0x1a\n"
            "    beq     loc_fc2f6458\n"
            "    cmp     r0, #0x3b\n"
            "    beq     loc_fc2f6458\n"
            "    cmp     r0, #0x36\n"
            "    beq     loc_fc2f6458\n"
            "    movs    r1, #1\n"
            "loc_fc2f6458:\n"
            "    cmp     r1, #1\n"
            "    bne     loc_fc2f6464\n"
            "    movs    r0, #0\n"
            "    add     r1, sp, #0xc\n"
            "    bl      sub_fc2f63aa\n"
            "loc_fc2f6464:\n"
            "    ldr     r0, [sp, #0x28]\n"
            "    ldr     r1, [r0]\n"
            "    cmp     r1, #0x3b\n"
            "    beq     loc_fc2f6516\n"
            "    cmp     r1, #0x3e\n"
            "    mov     r4, r1\n"
            "    bne     loc_fc2f6488\n"
            "    bl      sub_fc2f74dc\n"
            "    ldr.w   r0, [sl, #0x1c]\n"
            "    movs    r1, #1\n"
            "    blx     sub_fc34d10c\n"
            "    blx     sub_fc34d0f4\n"
            "    add     sp, #0x2c\n"
            "    b       sub_fc2f612e\n"
            "loc_fc2f6488:\n"
            "    cmp     r1, #0x3d\n"
            "    bne     loc_fc2f649a\n"
            "    add.w   r0, r0, #0xac\n"
            "    ldrd    r2, r1, [r0]\n"
            "    mov     r0, r1\n"
            "    blx     r2\n"
            "    b       loc_fc2f68e8\n"
            "loc_fc2f649a:\n"
            "    cmp     r1, #0x34\n"
            "    bne     loc_fc2f64d2\n"
            "    ldr     r0, [r5, #0x1c]\n"
            "    movs    r1, #0x80\n"
            "    blx     sub_fc34d1e4\n"
            "    ldr     r0, =0xfc2f1e7d\n"
            "    movs    r1, #0x80\n"
            "    bl      sub_fc163e1a\n"
            "    ldr     r0, [r5, #0x1c]\n"
            "    movs    r1, #0x80\n"
            "    movw    r2, #0xbb8\n"
            "    blx     sub_fc34d0cc\n"
            "    lsls    r0, r0, #0x1f\n"
            "    beq     loc_fc2f64c4\n"
            "    movw    r2, #0x1934\n"
            "    b       loc_fc2f6558\n"
            "loc_fc2f64c4:\n"
            "    ldr     r1, [sp, #0x28]\n"
            "    add.w   r1, r1, #0xac\n"
            "    ldrd    r1, r0, [r1]\n"
            "    blx     r1\n"
            "    b       loc_fc2f68e8\n"
            "loc_fc2f64d2:\n"
            "    cmp     r1, #0x35\n"
            "    bne     loc_fc2f6506\n"
            "    add     r1, sp, #0xc\n"
            "    bl      sub_fc2f63aa\n"
            "    movw    r6, #0x100\n"
            "    ldr     r0, [r5, #0x1c]\n"
            "    mov     r1, r6\n"
            "    blx     sub_fc34d1e4\n"
            "    ldr     r0, =0xfc2f1e87\n"
            "    mov     r1, r6\n"
            "    bl      sub_fc1647b8\n"
            "    ldr     r0, [r5, #0x1c]\n"
            "    movw    r2, #0xbb8\n"
            "    mov     r1, r6\n"
            "    blx     sub_fc34d0cc\n"
            "    lsls    r0, r0, #0x1f\n"
            "    beq     loc_fc2f64c4\n"
            "    movw    r2, #0x193e\n"
            "    b       loc_fc2f6558\n"
            "loc_fc2f6506:\n"
            "    cmp     r1, #0x36\n"
            "    bne     loc_fc2f6512\n"
            "    add     r1, sp, #0xc\n"
            "    bl      sub_fc2f63aa\n"
            "    b       loc_fc2f64c4\n"
            "loc_fc2f6512:\n"
            "    cmp     r1, #0x3b\n"
            "    bne     loc_fc2f6524\n"
            "loc_fc2f6516:\n"
            "    bl      sub_fc470fc8\n"
            "    bl      sub_fc198d24\n"
            "    bl      sub_fc469df6\n"
            "    b       loc_fc2f64c4\n"
            "loc_fc2f6524:\n"
            "    cmp     r1, #0x3c\n"
            "    bne     loc_fc2f6562\n"
            "    ldr     r0, [r5, #0x1c]\n"
            "    movs    r1, #4\n"
            "    blx     sub_fc34d1e4\n"
            "    movs    r3, #1\n"
            "    ldr     r2, =0xfc2f1e9b\n"
            "    movs    r1, #0\n"
            "    mov     r0, fp\n"
            "    str     r3, [sp]\n"
            "    movs    r3, #4\n"
            "    bl      sub_fc2f752c\n"
            "    bl      sub_fc470ce8\n"
            "    ldr     r0, [r5, #0x1c]\n"
            "    movs    r1, #4\n"
            "    movw    r2, #0xbb8\n"
            "    blx     sub_fc34d22c\n"
            "    lsls    r0, r0, #0x1f\n"
            "    beq     loc_fc2f64c4\n"
            "    movw    r2, #0x1a2d\n"
            "loc_fc2f6558:\n"
            "    ldr     r1, =0xfc2f26f8\n" //  **"ExpDrv.c"
            "    movs    r0, #0\n"
            "    blx     sub_fc34d264\n"
            "    b       loc_fc2f64c4\n"
            "loc_fc2f6562:\n"
            "    movs    r6, #1\n"
            "    cmp     r1, #0x13\n"
            "    beq     loc_fc2f656c\n"
            "    cmp     r1, #0x14\n"
            "    bne     loc_fc2f65aa\n"
            "loc_fc2f656c:\n"
            "    ldr.w   r1, [r0, #0x94]\n"
            "    mov     r5, sb\n"
            "    add.w   r1, r1, r1, lsl #1\n"
            "    add.w   r1, r0, r1, lsl #2\n"
            "    subs    r1, #8\n"
            "    ldm     r1!, {r2, r3, r7}\n"
            "    stm     r5!, {r2, r3, r7}\n"
            "    bl      sub_fc2f4bba\n"
            "    ldr     r0, [sp, #0x28]\n"
            "    add.w   r0, r0, #0x94\n"
            "    ldrd    r3, r2, [r0, #0x18]\n"
            "    ldr     r1, [r0]\n"
            "    sub.w   r0, r0, #0x90\n"
            "    blx     r3\n"
            "    ldr     r0, [sp, #0x28]\n"
            "    bl      sub_fc2f76ea\n"
            "    ldr     r0, [sp, #0x28]\n"
            "    add.w   r0, r0, #0x94\n"
            "    ldr     r1, [r0]\n"
            "    ldrd    r3, r2, [r0, #0x20]\n"
            "    b       loc_fc2f6808\n"
            "loc_fc2f65aa:\n"
            "    cmp     r1, #0x15\n"
            "    beq     loc_fc2f65c2\n"
            "    cmp     r1, #0x16\n"
            "    beq     loc_fc2f65c2\n"
            "    cmp     r1, #0x17\n"
            "    beq     loc_fc2f65c2\n"
            "    cmp     r1, #0x18\n"
            "    beq     loc_fc2f65c2\n"
            "    cmp     r1, #0x19\n"
            "    beq     loc_fc2f65c2\n"
            "    cmp     r1, #0x1a\n"
            "    bne     loc_fc2f6634\n"
            "loc_fc2f65c2:\n"
            "    add     r3, sp, #0xc\n"
            "    mov     r2, sp\n"
            "    add     r1, sp, #0x1c\n"
            "    bl      sub_fc2f4da2\n"
            "    cmp     r0, #1\n"
            "    mov     r5, r0\n"
            "    beq     loc_fc2f65d6\n"
            "    cmp     r5, #5\n"
            "    bne     loc_fc2f65ec\n"
            "loc_fc2f65d6:\n"
            "    ldr     r0, [sp, #0x28]\n"
            "    mov     r2, r5\n"
            "    add.w   r0, r0, #0x94\n"
            "    ldrd    r7, r3, [r0, #0x18]\n"
            "    ldr     r1, [r0]\n"
            "    sub.w   r0, r0, #0x90\n"
            "    blx     r7\n"
            "    b       loc_fc2f6612\n"
            "loc_fc2f65ec:\n"
            "    cmp     r5, #2\n"
            "    beq     loc_fc2f65f4\n"
            "    cmp     r5, #6\n"
            "    bne     loc_fc2f661e\n"
            "loc_fc2f65f4:\n"
            "    ldr     r0, [sp, #0x28]\n"
            "    mov     r2, r5\n"
            "    add.w   r0, r0, #0x94\n"
            "    ldrd    r7, r3, [r0, #0x18]\n"
            "    ldr     r1, [r0]\n"
            "    sub.w   r0, r0, #0x90\n"
            "    blx     r7\n"
            "    ldr     r0, [sp, #0x28]\n"
            "    add     r1, sp, #0x1c\n"
            "    mov     r2, sp\n"
            "    bl      sub_fc2f6132\n"
            "loc_fc2f6612:\n"
            "    ldr     r2, [sp, #0xc]\n"
            "    mov     r1, r5\n"
            "    ldr     r0, [sp, #0x28]\n"
            "    bl      sub_fc2f635a\n"
            "    b       loc_fc2f680e\n"
            "loc_fc2f661e:\n"
            "    ldr     r0, [sp, #0x28]\n"
            "    mov     r2, r5\n"
            "    add.w   r0, r0, #0x94\n"
            "    ldrd    r7, r3, [r0, #0x18]\n"
            "    ldr     r1, [r0]\n"
            "    sub.w   r0, r0, #0x90\n"
            "    blx     r7\n"
            "    b       loc_fc2f680e\n"
            "loc_fc2f6634:\n"
            "    cmp     r1, #0x2d\n"
            "    beq     loc_fc2f663c\n"
            "    cmp     r1, #0x2e\n"
            "    bne     loc_fc2f666e\n"
            "loc_fc2f663c:\n"
            "    ldr.w   r1, [r0, #0x94]\n"
            "    mov     r5, sb\n"
            "    add.w   r1, r1, r1, lsl #1\n"
            "    add.w   r1, r0, r1, lsl #2\n"
            "    subs    r1, #8\n"
            "    ldm     r1!, {r2, r3, r7}\n"
            "    stm     r5!, {r2, r3, r7}\n"
            "    bl      sub_fc2f3c68\n"
            "    ldr     r0, [sp, #0x28]\n"
            "    add.w   r0, r0, #0x94\n"
            "    ldrd    r3, r2, [r0, #0x18]\n"
            "    ldr     r1, [r0]\n"
            "    sub.w   r0, r0, #0x90\n"
            "    blx     r3\n"
            "    ldr     r0, [sp, #0x28]\n"
            "    bl      sub_fc2f406c\n"
            "    b       loc_fc2f680e\n"
            "loc_fc2f666e:\n"
            "    adds    r1, r0, #4\n"
            "    mov     r5, sb\n"
            "    ldm     r1!, {r2, r3, r7}\n"
            "    stm     r5!, {r2, r3, r7}\n"
            "    ldr     r1, [r0]\n"
            "    cmp     r1, #0x34\n"
            "    bhs     loc_fc2f66e4\n"

            //capdis -f=chdk -s=0xfc2f66a9 -c=179 -stubs PRIMARY.BIN 0xfc000000
            "    tbb     [pc, r1]\n" // (jumptable r1 52 elements)
            "branchtable_fc2f66ac:\n"
            "    .byte((loc_fc2f66e0 - branchtable_fc2f66ac) / 2)\n" // (case 0)
            "    .byte((loc_fc2f66e0 - branchtable_fc2f66ac) / 2)\n" // (case 1)
            "    .byte((loc_fc2f66e6 - branchtable_fc2f66ac) / 2)\n" // (case 2)
            "    .byte((loc_fc2f66ec - branchtable_fc2f66ac) / 2)\n" // (case 3)
            "    .byte((loc_fc2f66ec - branchtable_fc2f66ac) / 2)\n" // (case 4)
            "    .byte((loc_fc2f66ec - branchtable_fc2f66ac) / 2)\n" // (case 5)
            "    .byte((loc_fc2f66e0 - branchtable_fc2f66ac) / 2)\n" // (case 6)
            "    .byte((loc_fc2f66e6 - branchtable_fc2f66ac) / 2)\n" // (case 7)
            "    .byte((loc_fc2f66ec - branchtable_fc2f66ac) / 2)\n" // (case 8)
            "    .byte((loc_fc2f66ec - branchtable_fc2f66ac) / 2)\n" // (case 9)
            "    .byte((loc_fc2f66fe - branchtable_fc2f66ac) / 2)\n" // (case 10)
            "    .byte((loc_fc2f66fe - branchtable_fc2f66ac) / 2)\n" // (case 11)
            "    .byte((loc_fc2f66fe - branchtable_fc2f66ac) / 2)\n" // (case 12)
            "    .byte((loc_fc2f67ec - branchtable_fc2f66ac) / 2)\n" // (case 13)
            "    .byte((loc_fc2f67f2 - branchtable_fc2f66ac) / 2)\n" // (case 14)
            "    .byte((loc_fc2f67f2 - branchtable_fc2f66ac) / 2)\n" // (case 15)
            "    .byte((loc_fc2f67f2 - branchtable_fc2f66ac) / 2)\n" // (case 16)
            "    .byte((loc_fc2f67f2 - branchtable_fc2f66ac) / 2)\n" // (case 17)
            "    .byte((loc_fc2f67f8 - branchtable_fc2f66ac) / 2)\n" // (case 18)
            "    .byte((loc_fc2f67fc - branchtable_fc2f66ac) / 2)\n" // (case 19)
            "    .byte((loc_fc2f67fc - branchtable_fc2f66ac) / 2)\n" // (case 20)
            "    .byte((loc_fc2f67fc - branchtable_fc2f66ac) / 2)\n" // (case 21)
            "    .byte((loc_fc2f67fc - branchtable_fc2f66ac) / 2)\n" // (case 22)
            "    .byte((loc_fc2f67fc - branchtable_fc2f66ac) / 2)\n" // (case 23)
            "    .byte((loc_fc2f67fc - branchtable_fc2f66ac) / 2)\n" // (case 24)
            "    .byte((loc_fc2f67fc - branchtable_fc2f66ac) / 2)\n" // (case 25)
            "    .byte((loc_fc2f67fc - branchtable_fc2f66ac) / 2)\n" // (case 26)
            "    .byte((loc_fc2f66f2 - branchtable_fc2f66ac) / 2)\n" // (case 27)
            "    .byte((loc_fc2f66f8 - branchtable_fc2f66ac) / 2)\n" // (case 28)
            "    .byte((loc_fc2f66f8 - branchtable_fc2f66ac) / 2)\n" // (case 29)
            "    .byte((loc_fc2f66f8 - branchtable_fc2f66ac) / 2)\n" // (case 30)
            "    .byte((loc_fc2f6706 - branchtable_fc2f66ac) / 2)\n" // (case 31)
            "    .byte((loc_fc2f6706 - branchtable_fc2f66ac) / 2)\n" // (case 32)
            "    .byte((loc_fc2f6706 - branchtable_fc2f66ac) / 2)\n" // (case 33)
            "    .byte((loc_fc2f6706 - branchtable_fc2f66ac) / 2)\n" // (case 34)
            "    .byte((loc_fc2f6706 - branchtable_fc2f66ac) / 2)\n" // (case 35)
            "    .byte((loc_fc2f6706 - branchtable_fc2f66ac) / 2)\n" // (case 36)
            "    .byte((loc_fc2f670c - branchtable_fc2f66ac) / 2)\n" // (case 37)
            "    .byte((loc_fc2f673e - branchtable_fc2f66ac) / 2)\n" // (case 38)
            "    .byte((loc_fc2f67fc - branchtable_fc2f66ac) / 2)\n" // (case 39)
            "    .byte((loc_fc2f67fc - branchtable_fc2f66ac) / 2)\n" // (case 40)
            "    .byte((loc_fc2f6772 - branchtable_fc2f66ac) / 2)\n" // (case 41)
            "    .byte((loc_fc2f67a6 - branchtable_fc2f66ac) / 2)\n" // (case 42)
            "    .byte((loc_fc2f67da - branchtable_fc2f66ac) / 2)\n" // (case 43)
            "    .byte((loc_fc2f67da - branchtable_fc2f66ac) / 2)\n" // (case 44)
            "    .byte((loc_fc2f67fc - branchtable_fc2f66ac) / 2)\n" // (case 45)
            "    .byte((loc_fc2f67fc - branchtable_fc2f66ac) / 2)\n" // (case 46)
            "    .byte((loc_fc2f67e0 - branchtable_fc2f66ac) / 2)\n" // (case 47)
            "    .byte((loc_fc2f67e0 - branchtable_fc2f66ac) / 2)\n" // (case 48)
            "    .byte((loc_fc2f67e0 - branchtable_fc2f66ac) / 2)\n" // (case 49)
            "    .byte((loc_fc2f67e6 - branchtable_fc2f66ac) / 2)\n" // (case 50)
            "    .byte((loc_fc2f67e6 - branchtable_fc2f66ac) / 2)\n" // (case 51)
            ".align 1\n"
            "loc_fc2f66e0:\n"
            "    bl      sub_fc2f255a\n"
            "loc_fc2f66e4:\n"
            "    b       loc_fc2f67fc\n"
            "loc_fc2f66e6:\n"
            "    bl      sub_fc2f280a\n"
            "    b       loc_fc2f67fc\n"
            "loc_fc2f66ec:\n"
            "    bl      sub_fc2f2a1e\n"
            "    b       loc_fc2f67fc\n"
            "loc_fc2f66f2:\n"
            "    bl      sub_fc2f2ce0\n"
            "    b       loc_fc2f67fc\n"
            "loc_fc2f66f8:\n"
            "    bl      sub_fc2f2ea4\n"
            "    b       loc_fc2f67fc\n"
            "loc_fc2f66fe:\n"
            "    bl      sub_fc2f32fa_my\n" // Patched
            "    movs    r6, #0\n"
            "    b       loc_fc2f67fc\n"
            "loc_fc2f6706:\n"
            "    bl      sub_fc2f33f4\n"
            "    b       loc_fc2f67fc\n"
            "loc_fc2f670c:\n"
            "    ldrh    r1, [r0, #4]\n"
            "    strh.w  r1, [sp, #0x1c]\n"
            "    ldrh.w  r2, [r8, #2]\n"
            "    strh.w  r2, [sp, #0x1e]\n"
            "    ldrh.w  r2, [r8, #4]\n"
            "    strh.w  r2, [sp, #0x20]\n"
            "    ldrh.w  r2, [r8, #6]\n"
            "    strh.w  r2, [sp, #0x22]\n"
            "    ldrh    r2, [r0, #0xc]\n"
            "    strh.w  r2, [sp, #0x24]\n"
            "    ldrh.w  r1, [r8, #0xa]\n"
            "    strh.w  r1, [sp, #0x26]\n"
            "    bl      sub_fc2f39b6\n"
            "    b       loc_fc2f67fc\n"
            "loc_fc2f673e:\n"
            "    ldrh    r1, [r0, #4]\n"
            "    strh.w  r1, [sp, #0x1c]\n"
            "    ldrh.w  r2, [r8, #2]\n"
            "    strh.w  r2, [sp, #0x1e]\n"
            "    ldrh.w  r2, [r8, #4]\n"
            "    strh.w  r2, [sp, #0x20]\n"
            "    ldrh.w  r2, [r8, #6]\n"
            "    strh.w  r2, [sp, #0x22]\n"
            "    ldrh.w  r2, [r8, #8]\n"
            "    strh.w  r2, [sp, #0x24]\n"
            "    ldrh.w  r1, [r8, #0xa]\n"
            "    strh.w  r1, [sp, #0x26]\n"
            "    bl      sub_fc2f7576\n"
            "    b       loc_fc2f67fc\n"
            "loc_fc2f6772:\n"
            "    ldrh.w  r2, [r8]\n"
            "    strh.w  r2, [sp, #0x1c]\n"
            "    ldrh    r2, [r0, #6]\n"
            "    strh.w  r2, [sp, #0x1e]\n"
            "    ldrh.w  r2, [r8, #4]\n"
            "    strh.w  r2, [sp, #0x20]\n"
            "    ldrh.w  r2, [r8, #6]\n"
            "    strh.w  r2, [sp, #0x22]\n"
            "    ldrh.w  r2, [r8, #8]\n"
            "    strh.w  r2, [sp, #0x24]\n"
            "    ldrh.w  r1, [r8, #0xa]\n"
            "    strh.w  r1, [sp, #0x26]\n"
            "    bl      sub_fc2f75fc\n"
            "    b       loc_fc2f67fc\n"
            "loc_fc2f67a6:\n"
            "    ldrh.w  r2, [r8]\n"
            "    strh.w  r2, [sp, #0x1c]\n"
            "    ldrh.w  r2, [r8, #2]\n"
            "    strh.w  r2, [sp, #0x1e]\n"
            "    ldrh.w  r2, [r8, #4]\n"
            "    strh.w  r2, [sp, #0x20]\n"
            "    ldrh.w  r2, [r8, #6]\n"
            "    strh.w  r2, [sp, #0x22]\n"
            "    ldrh    r2, [r0, #0xc]\n"
            "    strh.w  r2, [sp, #0x24]\n"
            "    ldrh.w  r1, [r8, #0xa]\n"
            "    strh.w  r1, [sp, #0x26]\n"
            "    bl      sub_fc2f767a\n"
            "    b       loc_fc2f67fc\n"
            "loc_fc2f67da:\n"
            "    bl      sub_fc2f3a70\n"
            "    b       loc_fc2f67fc\n"
            "loc_fc2f67e0:\n"
            "    bl      sub_fc2f4134\n"
            "    b       loc_fc2f67fc\n"
            "loc_fc2f67e6:\n"
            "    bl      sub_fc2f4528\n"
            "    b       loc_fc2f67fc\n"
            "loc_fc2f67ec:\n"
            "    bl      sub_fc2f476e\n"
            "    b       loc_fc2f67fc\n"
            "loc_fc2f67f2:\n"
            "    bl      sub_fc2f48d4\n"
            "    b       loc_fc2f67fc\n"
            "loc_fc2f67f8:\n"
            "    bl      sub_fc2f49ee\n"
            "loc_fc2f67fc:\n"
            "    ldr     r0, [sp, #0x28]\n"
            "    add.w   r0, r0, #0x94\n"
            "    ldrd    r3, r2, [r0, #0x18]\n"
            "    ldr     r1, [r0]\n"
            "loc_fc2f6808:\n"
            "    sub.w   r0, r0, #0x90\n"
            "    blx     r3\n"
            "loc_fc2f680e:\n"
            "    ldr     r0, [sp, #0x28]\n"
            "    ldr     r0, [r0]\n"
            "    cmp     r0, #0x11\n"
            "    beq     loc_fc2f6832\n"
            "    bgt     loc_fc2f6826\n"
            "    cmp     r0, #1\n"
            "    beq     loc_fc2f6832\n"
            "    cmp     r0, #4\n"
            "    beq     loc_fc2f6832\n"
            "    cmp     r0, #0xf\n"
            "    bne     loc_fc2f6866\n"
            "    b       loc_fc2f6832\n"
            "loc_fc2f6826:\n"
            "    cmp     r0, #0x14\n"
            "    beq     loc_fc2f6832\n"
            "    cmp     r0, #0x1a\n"
            "    beq     loc_fc2f6832\n"
            "    cmp     r0, #0x1d\n"
            "    bne     loc_fc2f6866\n"
            "loc_fc2f6832:\n"
            "    ldrsh.w r0, [r8]\n"
            "    mov     r1, r8\n"
            "    mov     r2, fp\n"
            "    cmp     r0, fp\n"
            "    beq     loc_fc2f6846\n"
            "    ldrsh.w r1, [r1, #8]\n"
            "    cmp     r1, r2\n"
            "    bne     loc_fc2f685e\n"
            "loc_fc2f6846:\n"
            "    add     r0, sp, #0x10\n"
            "    bl      sub_fc3af9ee\n"
            "    ldrh.w  r0, [sp, #0x10]\n"
            "    strh.w  r0, [sp, #0x1c]\n"
            "    ldrh.w  r0, [sp, #0x18]\n"
            "    strh.w  r0, [sp, #0x24]\n"
            "    b       loc_fc2f6866\n"
            "loc_fc2f685e:\n"
            "    strh.w  r0, [sp, #0x1c]\n"
            "    strh.w  r1, [sp, #0x24]\n"
            "loc_fc2f6866:\n"
            "    cmp     r6, #1\n"
            "    ldr     r0, [sp, #0x28]\n"
            "    bne     loc_fc2f689e\n"
            "    movs    r2, #0xc\n"
            "    ldr.w   r1, [r0, #0x94]\n"
            "    add.w   r1, r1, r1, lsl #1\n"
            "    add.w   r5, r0, r1, lsl #2\n"
            "    ldr     r0, =0x0006ee40\n"
            "    subs    r5, #8\n"
            "    add     r1, sp, #0x1c\n"
            "    blx     sub_fc34d21c\n"
            "    ldr     r0, =0x0006ee40\n"
            "    movs    r2, #0xc\n"
            "    add     r1, sp, #0x1c\n"
            "    adds    r0, #0xc\n"
            "    blx     sub_fc34d21c\n"
            "    ldr     r0, =0x0006ee40\n"
            "    movs    r2, #0xc\n"
            "    mov     r1, r5\n"
            "    adds    r0, #0x18\n"
            "    blx     sub_fc34d21c\n"
            "    b       loc_fc2f68e8\n"
            "loc_fc2f689e:\n"
            "    ldr     r0, [r0]\n"
            "    mov.w   r3, #1\n"
            "    cmp     r0, #0xc\n"
            "    bne     loc_fc2f68c8\n"
            "    movs    r2, #0\n"
            "    mov     r1, r3\n"
            "    strd    r2, r3, [sp]\n"
            "    movs    r0, #0\n"
            "    mov     r2, r3\n"
            "    bl      sub_fc2f23b2\n"
            "    movs    r3, #1\n"
            "    movs    r2, #0\n"
            "    mov     r1, r3\n"
            "    movs    r0, #0\n"
            "    strd    r2, r3, [sp]\n"
            "    mov     r2, r3\n"
            "    b       loc_fc2f68e4\n"
            "loc_fc2f68c8:\n"
            "    movs    r2, #1\n"
            "    strd    r2, r3, [sp]\n"
            "    mov     r3, r2\n"
            "    mov     r1, r2\n"
            "    mov     r0, r2\n"
            "    bl      sub_fc2f23b2\n"
            "    movs    r3, #1\n"
            "    str     r3, [sp]\n"
            "    mov     r2, r3\n"
            "    mov     r1, r3\n"
            "    mov     r0, r3\n"
            "    str     r3, [sp, #4]\n"
            "loc_fc2f68e4:\n"
            "    bl      sub_fc2f24d8\n"
            "loc_fc2f68e8:\n"
            "    ldr     r0, [sp, #0x28]\n"
            "    bl      sub_fc2f74dc\n"
            "    b       loc_fc2f640a\n"
    );
}

//fc2f32fa
void __attribute__((naked,noinline))
sub_fc2f32fa_my ()
{
    asm volatile (
            //capdis -f=chdk -s=0xfc2f32fb -c=52 -jfw -stubs PRIMARY.BIN 0xfc000000
            "    push.w  {r4, r5, r6, r7, r8, lr}\n"
            "    ldr     r7, =0x0000e89c\n"
            "    movs    r1, #0x3e\n"
            "    mov     r4, r0\n"
            "    ldr     r0, [r7, #0x1c]\n"
            "    blx     sub_fc34d1e4\n"
            "    movs    r2, #0\n"
            "    ldrsh.w r0, [r4, #4]\n"
            "    movs    r3, #1\n"
            "    mov     r1, r2\n"
            "    bl      sub_fc2f1edc\n"
            "    mov     r6, r0\n"
            "    ldrsh.w r0, [r4, #6]\n"
            "    bl      sub_fc2f2076\n"
            "    ldrsh.w r0, [r4, #8]\n"
            "    bl      sub_fc2f20bc\n"
            "    ldrsh.w r0, [r4, #0xa]\n"
            "    bl      sub_fc2f2102\n"
            "    ldrsh.w r0, [r4, #0xc]\n"
            "    movs    r1, #0\n"
            "    bl      sub_fc2f2148\n"
            "    mov     r5, r0\n"
            "    ldr     r0, [r4]\n"
            "    ldr.w   r8, =0x0006ee58\n"
            "    cmp     r0, #0xc\n"
            "    bne     loc_fc2f334e\n"
            "    movs    r6, #0\n"
            "    mov     r5, r6\n"
            "    b       loc_fc2f3366\n"
            "loc_fc2f334e:\n"
            "    cmp     r6, #1\n"
            "    bne     loc_fc2f3366\n"
            "    ldrsh.w r0, [r4, #4]\n"
            "    movs    r2, #2\n"
            "    ldr     r1, =0xfc2f1e73\n"
            "    bl      sub_fc16402a\n"
            "    strh    r0, [r4, #4]\n"
            "    movs    r0, #0\n"
            "    str     r0, [r7, #0x28]\n"
            "    b       loc_fc2f336c\n"
            "loc_fc2f3366:\n"
            "    ldrh.w  r0, [r8]\n"
            "    strh    r0, [r4, #4]\n"
            "loc_fc2f336c:\n"
            "    cmp     r5, #1\n"
            "    bne     loc_fc2f337e\n"
            "    ldrsh.w r0, [r4, #0xc]\n"
            "    movs    r2, #0x20\n"
            "    ldr     r1, =0xfc2f1ec7\n"
            "    bl      sub_fc2f754c\n"
            "    b       loc_fc2f3382\n"
            "loc_fc2f337e:\n"
            "    ldrh.w  r0, [r8, #8]\n"
            "loc_fc2f3382:\n"
            "    strh    r0, [r4, #0xc]\n"
            "    ldrsh.w r0, [r4, #6]\n"
            "    bl      sub_fc470d42_my\n" // Patched
            "    ldr     pc, =0xfc2f338d\n" // Continue in firmware
    );
}

//fc470d42
void __attribute__((naked,noinline))
sub_fc470d42_my ()
{
    asm volatile (
            //capdis -f=chdk -s=0xfc470d43 -c=35 -stubs PRIMARY.BIN 0xfc000000
            "    push    {r4, r5, r6, lr}\n"
            "    ldr     r5, =0x0000fd5c\n"
            "    mov     r4, r0\n"
            "    ldr     r0, [r5, #4]\n"
            "    cmp     r0, #1\n"
            "    beq     loc_fc470d5a\n"
            "    movs    r0, #0\n"
            "    movw    r2, #0x16b\n"
            "    ldr     r1, =0xfc470da4\n" //  *"Shutter.c"
            "    blx     sub_fc34d264\n"
            "loc_fc470d5a:\n"
            "    ldr     r0, =0xfffff400\n"
            "    cmp     r4, r0\n"
            "    bne     loc_fc470d64\n"
            "    ldrsh.w r4, [r5, #2]\n"
            "loc_fc470d64:\n"
            "    strh    r4, [r5, #2]\n"
            "    cmp     r4, r0\n"
            "    bne     loc_fc470d76\n"
            "    movs    r0, #0\n"
            "    movw    r2, #0x171\n"
            "    ldr     r1, =0xfc470da4\n" //  *"Shutter.c"
            "    blx     sub_fc34d264\n"
            "loc_fc470d76:\n"
            "    mov     r0, r4\n"
            //"    bl      sub_fc25f5ca\n"      // -
            "    bl      apex2us\n" // +
            "    mov     r4, r0\n"
            "    bl      sub_fc198752\n"
            "    mov     r0, r4\n"
            "    bl      sub_fc19a8f6\n"
            "    lsls    r0, r0, #0x1f\n"
            "    beq     loc_fc470d9c\n"
            "    pop.w   {r4, r5, r6, lr}\n"
            "    movs    r0, #0\n"
            "    movw    r2, #0x176\n"
            "    ldr     r1, =0xfc470da4\n" //  *"Shutter.c"
            "    b.w     sub_fc34c718\n" // continue in firmware
            "loc_fc470d9c:\n"
            "    pop     {r4, r5, r6, pc}\n"
    );
}

