# next line is for the compatibility check, as comment
# PLATFORMID @ 0xfffe0130
# below 2 commented lines are used by tools/compatbuilder.sh
# BLINK_LED_CONTROL=1
# BLINK_LED_GPIO=0

DIGIC = 30# DIGIC III

