PLATFORMID=12956
PLATFORMOS=dryos
PLATFORMOSVER=55

# points to the start of the memory pool used by the firmware
MEMISOSTART=0x1BADE8

# start of firmware
ROMBASEADDR=0xFF810000

# type of diskboot encoding
NEED_ENCODED_DISKBOOT=14 
# type of FI2 encoding
KEYSYS=d4h
