/*
 * movie_rec.c - auto-generated by CHDK code_gen.
 */
#include "conf.h"

void change_video_tables(int a, int b){
}

void  set_quality(int *x){ // -17 highest; +12 lowest
 if (conf.video_mode) *x=12-((conf.video_quality-1)*(12+17)/(99-1));
}

/*************************************************************/
//** movie_record_task @ 0xFF921108 - 0xFF92120C, length=66
void __attribute__((naked,noinline)) movie_record_task() {
asm volatile (
"    STMFD   SP!, {R2-R8,LR} \n"
"    LDR     R8, =0x442 \n"
"    LDR     R7, =0x2710 \n"
"    LDR     R4, =0x5FC8 \n"
"    MOV     R6, #0 \n"
"    MOV     R5, #1 \n"

"loc_FF921120:\n"
"    LDR     R0, [R4, #0x18] \n"
"    MOV     R2, #0 \n"
"    ADD     R1, SP, #4 \n"
"    BL      sub_FF8269D4 /*_ReceiveMessageQueue*/ \n"
"    LDR     R0, [R4, #0x20] \n"
"    CMP     R0, #0 \n"
"    BNE     loc_FF9211F0 \n"
"    LDR     R0, [SP, #4] \n"
"    LDR     R1, [R0] \n"
"    SUB     R1, R1, #2 \n"
"    CMP     R1, #9 \n"
"    ADDLS   PC, PC, R1, LSL#2 \n"
"    B       loc_FF9211F0 \n"
"    B       loc_FF9211A4 \n"
"    B       loc_FF9211C4 \n"
"    B       loc_FF9211D4 \n"
"    B       loc_FF9211DC \n"
"    B       loc_FF9211AC \n"
"    B       loc_FF9211E4 \n"
"    B       loc_FF9211B4 \n"
"    B       loc_FF9211F0 \n"
"    B       loc_FF9211EC \n"
"    B       loc_FF92117C \n"

"loc_FF92117C:\n"
"    LDR     R0, =0xFF920E2C \n"
"    STR     R6, [R4, #0x34] \n"
"    STR     R0, [R4, #0x9C] \n"
"    LDR     R0, =0xFF920454 \n"
"    LDR     R2, =0xFF920370 \n"
"    LDR     R1, =0x2CC28 \n"
"    STR     R6, [R4, #0x24] \n"
"    BL      sub_FF8B6290 \n"
"    STR     R5, [R4, #0x38] \n"
"    B       loc_FF9211F0 \n"

"loc_FF9211A4:\n"
"    BL      unlock_optical_zoom\n"          // added
"    BL      sub_FF920F24 \n"
"    B       loc_FF9211F0 \n"

"loc_FF9211AC:\n"
"    BL      sub_FF920AD0 \n"
"    LDR     R0, =video_compression_rate \n" // added
"    BL      set_quality \n"                 // added
"    B       loc_FF9211F0 \n"

"loc_FF9211B4:\n"
"    LDR     R1, [R0, #0x18] \n"
"    LDR     R0, [R0, #4] \n"
"    BL      sub_FFA51CC4 \n"
"    B       loc_FF9211F0 \n"

"loc_FF9211C4:\n"
"    LDR     R0, [R4, #0x38] \n"
"    CMP     R0, #5 \n"
"    STRNE   R5, [R4, #0x28] \n"
"    B       loc_FF9211F0 \n"

"loc_FF9211D4:\n"
"    BL      sub_FF9207BC \n"
"    B       loc_FF9211F0 \n"

"loc_FF9211DC:\n"
"    BL      sub_FF9204A0 \n"
"    B       loc_FF9211F0 \n"

"loc_FF9211E4:\n"
"    BL      sub_FF9202FC \n"
"    B       loc_FF9211F0 \n"

"loc_FF9211EC:\n"
"    BL      sub_FF921358 \n"

"loc_FF9211F0:\n"
"    LDR     R1, [SP, #4] \n"
"    LDR     R3, =0xFF920160 /*'MovieRecorder.c'*/ \n"
"    STR     R6, [R1] \n"
"    STR     R8, [SP] \n"
"    LDR     R0, [R4, #0x1C] \n"
"    MOV     R2, R7 \n"
"    BL      sub_FF827328 /*_PostMessageQueueStrictly*/ \n"
"    B       loc_FF921120 \n"
);
}
