#include "lolevel.h"
#include "platform.h"
#include "core.h"
#include "conf.h"
#include "stdlib.h"

static long *nrflag = (long*)(0x8744+0x00);  // Found @ ff9df4d8 & ff9df538
#define NR_AUTO (0)                          // have to explictly reset value back to 0 to enable auto

#define PAUSE_FOR_FILE_COUNTER 250           // Enable delay in capt_seq_hook_raw_here to ensure file counter is updated

typedef struct {
    unsigned int address;
    unsigned int length;
} cam_ptp_data_chunk; //camera specific structure

#define MAX_CHUNKS_FOR_JPEG 7 // filewritetask is prepared for this many chunks
/*
 * fwt_data_struct: defined here as it's camera dependent
 * unneeded members are designated with unkn
 * file_offset, full_size, seek_flag only needs to be defined for DryOS>=r50 generation cameras
 * pdc and name are always needed
 */
typedef struct
{
    int unkn1;
    int file_offset;    // needed for DryOS>=r50
    int full_size;      // needed for DryOS>=r50
    int unkn2, unkn3, unkn4;
    cam_ptp_data_chunk pdc[MAX_CHUNKS_FOR_JPEG];
    int seek_flag;      // needed for DryOS>=r50
    char name[32];
} fwt_data_struct;
#define FWT_MUSTSEEK    2   // value of seek_flag indicating seek is required
#define FWT_CONDSEEK    3   // value of seek_flag indicating seek is required when file_offset not 0

#include "../../../generic/capt_seq.c"

//** capt_seq_task  @ 0xFF86ECA8 

void __attribute__((naked,noinline)) capt_seq_task() {
asm volatile (
      "STMFD   SP!, {R3-R7,LR} \n"
      "LDR     R5, =0x36C34 \n"
      "LDR     R6, =0x2ACC \n"
"loc_FF86ECB4:\n"
      "MOV     R2, #0 \n"
      "LDR     R0, [R6, #4] \n"
      "MOV     R1, SP \n"
      "BL      sub_003F7218 \n" // RAM
      "TST     R0, #1 \n"
      "BEQ     loc_FF86ECE0 \n"
      "LDR     R1, =0x493 \n"
      "LDR     R0, =0xFF86E814 \n" // **"SsShootTask.c"
      "BL      _DebugAssert \n"
      "BL      _ExitTask \n"
      "LDMFD   SP!, {R3-R7,PC} \n"
"loc_FF86ECE0:\n"
      "LDR     R0, [SP] \n"
      "LDR     R1, [R0] \n"
      "CMP     R1, #0x20 \n"
      "ADDCC   PC, PC, R1, LSL #2 \n"
      "B       loc_FF86EF20 \n"
      "B       loc_FF86ED74 \n"
      "B       loc_FF86ED7C \n"
      "B       loc_FF86EDE0 \n"
      "B       loc_FF86EDF4 \n"
      "B       loc_FF86EDEC \n"
      "B       loc_FF86EDFC \n"
      "B       loc_FF86EE04 \n"
      "B       loc_FF86EE10 \n"
      "B       loc_FF86EE2C \n"
      "B       loc_FF86EDF4 \n"
      "B       loc_FF86EE34 \n"
      "B       loc_FF86EE40 \n"
      "B       loc_FF86EE48 \n"
      "B       loc_FF86EE54 \n"
      "B       loc_FF86EE5C \n"
      "B       loc_FF86EE64 \n"
      "B       loc_FF86EE6C \n"
      "B       loc_FF86EE74 \n"
      "B       loc_FF86EE80 \n"
      "B       loc_FF86EE88 \n"
      "B       loc_FF86EE90 \n"
      "B       loc_FF86EE98 \n"
      "B       loc_FF86EEA0 \n"
      "B       loc_FF86EEAC \n"
      "B       loc_FF86EEB4 \n"
      "B       loc_FF86EEBC \n"
      "B       loc_FF86EEC4 \n"
      "B       loc_FF86EECC \n"
      "B       loc_FF86EED8 \n"
      "B       loc_FF86EEE0 \n"
      "B       loc_FF86EEEC \n"
      "B       loc_FF86EF2C \n"
"loc_FF86ED74:\n"  // jump table entry 0
      "BL		shooting_expo_iso_override\n"  	// added - as ixus220 - but not defined for a810??
      "BL      sub_FF86F50C \n"
      "BL      shooting_expo_param_override\n"      // added
      "B       loc_FF86EE08 \n"
"loc_FF86ED7C:\n" // jump table entry 1
      "LDR     R4, [R0, #0x10] \n"
      "LDR     R0, [R5, #0x84] \n"
      "TST     R0, #0x30 \n"
      "BLNE    sub_FF87066C \n"
      "BL      sub_FF87034C \n"
      "MOV     R1, R4 \n"
      "BL      sub_FF8703A4 \n"
      "LDR     R0, =0x10F \n"
      "MOV     R2, #4 \n"
      "ADD     R1, R4, #0x24 \n"
      "BL      sub_FF87E744 \n"
      "MOV     R2, #4 \n"
      "ADD     R1, R4, #0x28 \n"
      "MOV     R0, #0x2C \n"
      "BL      sub_FF87E744 \n"
      "MOV     R0, R4 \n"
//      "BL      sub_FF960CA8 \n" //original
      "BL      sub_FF960CA8_my \n" //patched
      "BL      capt_seq_hook_raw_here \n" // patch
      "MOV     R7, R0 \n"
      "MOV     R2, R4 \n"
      "MOV     R1, #1 \n"
      "BL      sub_FF86D0F8 \n"
      "TST     R7, #1 \n"
      "MOVEQ   R0, R4 \n"
      "BLEQ    sub_FF9606B0 \n"
      "B       loc_FF86EF2C \n"
"loc_FF86EDE0:\n" // jump table entry 2
      "MOV     R0, #1 \n"
      "BL      sub_FF86F7D0 \n"
      "B       loc_FF86EF2C \n"
"loc_FF86EDEC:\n"
      "BL      sub_FF86F154 \n"
      "B       loc_FF86EF2C \n"
"loc_FF86EDF4:\n"
      "BL      sub_FF86F4EC \n"
      "B       loc_FF86EF2C \n"
"loc_FF86EDFC:\n"
      "BL      sub_FF86F4F4 \n"
      "B       loc_FF86EF2C \n"
"loc_FF86EE04:\n"
      "BL      sub_FF86F6B8 \n"
"loc_FF86EE08:\n"
      "BL      sub_FF86CC78 \n"
      "B       loc_FF86EF2C \n"
"loc_FF86EE10:\n"
      "LDR     R4, [R0, #0x10] \n"
      "MOV     R0, R4 \n"
      "BL      sub_FF960DAC \n"
      "MOV     R2, R4 \n"
      "MOV     R1, #9 \n"
      "BL      sub_FF86D0F8 \n"
      "B       loc_FF86EF2C \n"
"loc_FF86EE2C:\n"
      "BL      sub_FF86F738 \n"
      "B       loc_FF86EE08 \n"
"loc_FF86EE34:\n"
      "LDR     R0, [R5, #0x50] \n"
      "BL      sub_FF86FB70 \n"
      "B       loc_FF86EF2C \n"
"loc_FF86EE40:\n"
      "BL      sub_FF86FF08 \n"
      "B       loc_FF86EF2C \n"
"loc_FF86EE48:\n"
      "MOV     R0, #0 \n"
      "BL      sub_FF86FF6C \n"
      "B       loc_FF86EF2C \n"
"loc_FF86EE54:\n"
      "BL      sub_FF95FA80 \n"
      "B       loc_FF86EF2C \n"
"loc_FF86EE5C:\n"
      "BL      sub_FF95FCE0 \n"
      "B       loc_FF86EF2C \n"
"loc_FF86EE64:\n"
      "BL      sub_FF95FD98 \n"
      "B       loc_FF86EF2C \n"
"loc_FF86EE6C:\n"
      "BL      sub_FF95FE6C \n"
      "B       loc_FF86EF2C \n"
"loc_FF86EE74:\n"
      "MOV     R0, #0 \n"
      "BL      sub_FF9600CC \n"
      "B       loc_FF86EF2C \n"
"loc_FF86EE80:\n"
      "BL      sub_FF96023C \n"
      "B       loc_FF86EF2C \n"
"loc_FF86EE88:\n"
      "BL      sub_FF9602D0 \n"
      "B       loc_FF86EF2C \n"
"loc_FF86EE90:\n"
      "BL      sub_FF960388 \n"
      "B       loc_FF86EF2C \n"
"loc_FF86EE98:\n"
      "BL      sub_FF86F94C \n"
      "B       loc_FF86EF2C \n"
"loc_FF86EEA0:\n"
      "BL      sub_FF86F978 \n"
      "BL      sub_FF830FB0 \n"
      "B       loc_FF86EF2C \n"
"loc_FF86EEAC:\n"
      "BL      sub_FF95FF3C \n"
      "B       loc_FF86EF2C \n"
"loc_FF86EEB4:\n"
      "BL      sub_FF95FF7C \n"
      "B       loc_FF86EF2C \n"
"loc_FF86EEBC:\n"
      "BL      sub_FF871844 \n"
      "B       loc_FF86EF2C \n"
"loc_FF86EEC4:\n"
      "BL      sub_FF8718B8 \n"
      "B       loc_FF86EF2C \n"
"loc_FF86EECC:\n"
      "LDR     R0, [R0, #0xC] \n"
      "BL      sub_FF9604A0 \n"
      "B       loc_FF86EF2C \n"
"loc_FF86EED8:\n"
      "BL      sub_FF960510 \n"
      "B       loc_FF86EF2C \n"
"loc_FF86EEE0:\n"
      "BL      sub_FF871920 \n"
      "BL      sub_FF8718D8 \n"
      "B       loc_FF86EF2C \n"
"loc_FF86EEEC:\n"
      "MOV     R0, #1 \n"
      "BL      sub_FF9614C4 \n"
      "MOV     R0, #1 \n"
      "BL      sub_FF9615EC \n"
      "LDRH    R0, [R5, #0x94] \n"
      "CMP     R0, #4 \n"
      "LDRNEH  R0, [R5] \n"
      "SUBNE   R1, R0, #0x8200 \n"
      "SUBNES  R1, R1, #0x2E \n"
      "BNE     loc_FF86EF2C \n"
      "BL      sub_FF8718B8 \n"
      "BL      sub_FF871D7C \n"
      "B       loc_FF86EF2C \n"
"loc_FF86EF20:\n"
      "LDR     R1, =0x5F4 \n"
      "LDR     R0, =0xFF86E814 \n" // *"SsShootTask.c"
      "BL      _DebugAssert \n"
"loc_FF86EF2C:\n"
      "LDR     R0, [SP] \n"
      "LDR     R1, [R0, #4] \n"
      "LDR     R0, [R6] \n"
      "BL      sub_003FAC6C \n" // RAM
      "LDR     R4, [SP] \n"
      "LDR     R0, [R4, #8] \n"
      "CMP     R0, #0 \n"
      "LDREQ   R1, =0x117 \n"
      "LDREQ   R0, =0xFF86E814 \n" // *"SsShootTask.c"
      "BLEQ    _DebugAssert \n"
      "MOV     R0, #0 \n"
      "STR     R0, [R4, #8] \n"
      "B       loc_FF86ECB4 \n"
	);
}

//** sub_FF960CA8_my  @ 0xFF960CA8 

void __attribute__((naked,noinline)) sub_FF960CA8_my() {
asm volatile (
      "STMFD   SP!, {R3-R5,LR} \n"
      "MOV     R5, R0 \n"
      "MOV     R0, #0xC \n"
      "BL      sub_FF873300 \n"
      "TST     R0, #1 \n"
      "MOVNE   R0, #1 \n"
      "BNE     sub_FF960DA8 \n"
      "BL      sub_FF86F4FC \n"
      "MOV     R0, R5 \n"
      "BL      sub_FF960600 \n"
      "TST     R0, #1 \n"
      "BNE     sub_FF960DA8 \n"
      "LDR     R4, =0x36C34 \n"
      "LDR     R0, [R4, #0x84] \n"
      "AND     R0, R0, #0x40 \n"
      "CMP     R0, #0 \n"
      "LDRNEH  R0, [R4, #0x92] \n"
      "CMPNE   R0, #3 \n"
      "LDRNE   R0, [R5, #8] \n"
      "CMPNE   R0, #1 \n"
      "BLS     loc_FF960D18 \n"
      "BL      sub_FF9617AC \n"
      "MOV     R3, #0xC0 \n"
      "STR     R3, [SP] \n"
      "LDR     R2, =0x3A98 \n"
      "LDR     R3, =0xFF960E38 \n" //SsCaptureSeq.c
      "MOV     R1, #0x8000 \n"
      "BL      sub_FF873568 \n"
"loc_FF960D18:\n"
      "MOV     R0, R5 \n"
      "BL      sub_FF9608E8 \n"
      "BL      sub_FF9612A4 \n"
      
      "BL      wait_until_remote_button_is_released \n"  //before shoot XXX
      "BL      capt_seq_hook_set_nr \n"
       
      "LDR     R0, [R4, #0x84] \n"
      "TST     R0, #0x40 \n"
      "BEQ     sub_FF960D8C \n" //from loc_ to sub_ differs from 100b
      "LDR     R0, =0x181 \n"
      "MOV     R2, #4 \n"
      "MOV     R1, SP \n"
      "BL      _GetPropertyCase \n"
      "TST     R0, #1 \n"
      "MOVNE   R1, #0xD4 \n"
      "LDRNE   R0, =0xFF960E38 \n" //SsCaptureSeq.c
      "BLNE    _DebugAssert \n" //RAM
      "LDR     R0, [SP] \n"
      "CMP     R0, #0 \n"
      "BNE     loc_FF960D6C \n"
      "BL      sub_FF9617AC \n"
      "MOV     R1, #0x8000 \n"
      "BL      sub_003FAC6C \n" //RAM 
      "B       sub_FF960D8C \n"
"loc_FF960D6C:\n"
      "BL      sub_FF9617AC \n"
      "MOV     R1, #0x8000 \n"
      "BL      sub_003FACA0 \n" // RAM
      "LDR     R2, =0xFF960C94 \n"
      "LDR     R0, [SP] \n"
      "MOV     R3, #0x8000 \n"
      "ADD     R1, R2, #0 \n"
      "BL      sub_FF833200 \n"
 "loc_FF960D8C:\n"   //this does not exist in 100b
      "LDR     R0, [R4, #0x84] \n"
      "TST     R0, #0x10 \n"
      "MOV     R0, R5 \n"
      "LDMEQFD SP!, {R3-R5,LR} \n"
	);
}

//** exp_drv_task  @ 0xFF8AE838 

void __attribute__((naked,noinline)) exp_drv_task(  ) { 
asm volatile (
      "STMFD   SP!, {R4-R9,LR} \n"
      "SUB     SP, SP, #0x2C \n"
      "LDR     R6, =0x3D78 \n"
      "LDR     R7, =0xBB8 \n"
      "LDR     R4, =0x55E1C \n"
      "MOV     R0, #0 \n"
      "ADD     R5, SP, #0x1C \n"
      "STR     R0, [SP, #0xC] \n"
"loc_FF8AE858:\n"
      "LDR     R0, [R6, #0x20] \n"
      "MOV     R2, #0 \n"
      "ADD     R1, SP, #0x28 \n"
      "BL      sub_003F7218 \n" //RAM
      "LDR     R0, [SP, #0xC] \n"
      "CMP     R0, #1 \n"
      "BNE     loc_FF8AE8A4 \n"
      "LDR     R0, [SP, #0x28] \n"
      "LDR     R0, [R0] \n"
      "CMP     R0, #0x14 \n"
      "CMPNE   R0, #0x15 \n"
      "CMPNE   R0, #0x16 \n"
      "CMPNE   R0, #0x17 \n"
      "BEQ     loc_FF8AEA04 \n"
      "CMP     R0, #0x2A \n"
      "BEQ     loc_FF8AE98C \n"
      "ADD     R1, SP, #0xC \n"
      "MOV     R0, #0 \n"
      "BL      sub_FF8AE7E8 \n"
"loc_FF8AE8A4:\n"
      "LDR     R0, [SP, #0x28] \n"
      "LDR     R1, [R0] \n"
      "CMP     R1, #0x30 \n"
      "BNE     loc_FF8AE8D0 \n"
      "BL      sub_FF8AFC14 \n"
      "LDR     R0, [R6, #0x1C] \n"
      "MOV     R1, #1 \n"
      "BL      sub_003FAC6C \n" //RAM
      "BL      _ExitTask \n"
      "ADD     SP, SP, #0x2C \n"
      "LDMFD   SP!, {R4-R9,PC} \n"
"loc_FF8AE8D0:\n"
      "CMP     R1, #0x2F \n"
      "BNE     loc_FF8AE8EC \n"
      "LDR     R2, [R0, #0x8C]! \n"
      "LDR     R1, [R0, #4] \n"
      "MOV     R0, R1 \n"
      "BLX     R2 \n"
      "B       loc_FF8AEEC0 \n"
"loc_FF8AE8EC:\n"
      "CMP     R1, #0x28 \n"
      "BNE     loc_FF8AE93C \n"
      "LDR     R0, [R6, #0x1C] \n"
      "MOV     R1, #0x80 \n"
      "BL      sub_003FACA0 \n" //RAM
      "LDR     R0, =0xFF8AA154 \n"
      "MOV     R1, #0x80 \n"
      "BL      sub_FF954D60 \n"
      "LDR     R0, [R6, #0x1C] \n"
      "MOV     R2, R7 \n"
      "MOV     R1, #0x80 \n"
      "BL      sub_003FABAC \n" //RAM
      "TST     R0, #1 \n"
      "LDRNE   R1, =0x1599 \n"
      "BNE     loc_FF8AE9F8 \n"
"loc_FF8AE928:\n"
      "LDR     R1, [SP, #0x28] \n"
      "LDR     R0, [R1, #0x90] \n"
      "LDR     R1, [R1, #0x8C] \n"
      "BLX     R1 \n"
      "B       loc_FF8AEEC0 \n"
"loc_FF8AE93C:\n"
      "CMP     R1, #0x29 \n"
      "BNE     loc_FF8AE984 \n"
      "ADD     R1, SP, #0xC \n"
      "BL      sub_FF8AE7E8 \n"
      "LDR     R0, [R6, #0x1C] \n"
      "MOV     R1, #0x100 \n"
      "BL      sub_003FACA0 \n" //RAM
      "LDR     R0, =0xFF8AA164 \n"
      "MOV     R1, #0x100 \n"
      "BL      sub_FF954F00 \n"
      "LDR     R0, [R6, #0x1C] \n"
      "MOV     R2, R7 \n"
      "MOV     R1, #0x100 \n"
      "BL      sub_003FABAC \n" //RAM
      "TST     R0, #1 \n"
      "BEQ     loc_FF8AE928 \n"
      "LDR     R1, =0x15A3 \n"
      "B       loc_FF8AE9F8 \n"
"loc_FF8AE984:\n"
      "CMP     R1, #0x2A \n"
      "BNE     loc_FF8AE99C \n"
"loc_FF8AE98C:\n"
      "LDR     R0, [SP, #0x28] \n"
      "ADD     R1, SP, #0xC \n"
      "BL      sub_FF8AE7E8 \n"
      "B       loc_FF8AE928 \n"
"loc_FF8AE99C:\n"
      "CMP     R1, #0x2D \n"
      "BNE     loc_FF8AE9B4 \n"
      "BL      sub_FF89A404 \n"
      "BL      sub_FF89B0EC \n"
      "BL      sub_FF89AC54 \n"
      "B       loc_FF8AE928 \n"
"loc_FF8AE9B4:\n"
      "CMP     R1, #0x2E \n"
      "BNE     loc_FF8AEA04 \n"
      "LDR     R0, [R6, #0x1C] \n"
      "MOV     R1, #4 \n"
      "BL      sub_003FACA0 \n" //RAM
      "LDR     R1, =0xFF8AA184 \n"
      "LDR     R0, =0xFFFFF400 \n"
      "MOV     R2, #4 \n"
      "BL      sub_FF899E54 \n"
      "BL      sub_FF89A0E4 \n"
      "LDR     R0, [R6, #0x1C] \n"
      "MOV     R2, R7 \n"
      "MOV     R1, #4 \n"
      "BL      sub_003FAAC8 \n" //RAM
      "TST     R0, #1 \n"
      "BEQ     loc_FF8AE928 \n"
      "LDR     R1, =0x15CB \n"
"loc_FF8AE9F8:\n"
      "LDR     R0, =0xFF8AA878 \n" // **"ExpDrv.c"
      "BL      _DebugAssert \n"
      "B       loc_FF8AE928 \n"
"loc_FF8AEA04:\n"
      "LDR     R0, [SP, #0x28] \n"
      "MOV     R8, #1 \n"
      "LDR     R1, [R0] \n"
      "CMP     R1, #0x12 \n"
      "CMPNE   R1, #0x13 \n"
      "BNE     loc_FF8AEA6C \n"
      "LDR     R1, [R0, #0x7C] \n"
      "ADD     R1, R1, R1, LSL #1 \n"
      "ADD     R1, R0, R1, LSL #2 \n"
      "SUB     R1, R1, #8 \n"
      "LDMIA   R1, {R2,R3,R9} \n"
      "STMIA   R5, {R2,R3,R9} \n"
      "BL      sub_FF8ACD8C \n"
      "LDR     R0, [SP, #0x28] \n"
      "LDR     R1, [R0, #0x7C] \n"
      "LDR     R3, [R0, #0x8C] \n"
      "LDR     R2, [R0, #0x90] \n"
      "ADD     R0, R0, #4 \n"
      "BLX     R3 \n"
      "LDR     R0, [SP, #0x28] \n"
      "BL      sub_FF8B0018 \n"
      "LDR     R0, [SP, #0x28] \n"
      "LDR     R1, [R0, #0x7C] \n"
      "LDR     R2, [R0, #0x98] \n"
      "LDR     R3, [R0, #0x94] \n"
      "B       loc_FF8AED84 \n"
"loc_FF8AEA6C:\n"
      "CMP     R1, #0x14 \n"
      "CMPNE   R1, #0x15 \n"
      "CMPNE   R1, #0x16 \n"
      "CMPNE   R1, #0x17 \n"
      "BNE     loc_FF8AEB24 \n"
      "ADD     R3, SP, #0xC \n"
      "MOV     R2, SP \n"
      "ADD     R1, SP, #0x1C \n"
      "BL      sub_FF8ACFEC \n"
      "CMP     R0, #1 \n"
      "MOV     R9, R0 \n"
      "CMPNE   R9, #5 \n"
      "BNE     loc_FF8AEAC0 \n"
      "LDR     R0, [SP, #0x28] \n"
      "MOV     R2, R9 \n"
      "LDR     R1, [R0, #0x7C]! \n"
      "LDR     R12, [R0, #0x10]! \n"
      "LDR     R3, [R0, #4] \n"
      "MOV     R0, SP \n"
      "BLX     R12 \n"
      "B       loc_FF8AEAF8 \n"
"loc_FF8AEAC0:\n"
      "LDR     R0, [SP, #0x28] \n"
      "CMP     R9, #2 \n"
      "LDR     R3, [R0, #0x90] \n"
      "CMPNE   R9, #6 \n"
      "BNE     loc_FF8AEB0C \n"
      "LDR     R12, [R0, #0x8C] \n"
      "MOV     R2, R9 \n"
      "MOV     R1, #1 \n"
      "MOV     R0, SP \n"
      "BLX     R12 \n"
      "LDR     R0, [SP, #0x28] \n"
      "MOV     R2, SP \n"
      "ADD     R1, SP, #0x1C \n"
      "BL      sub_FF8AE4D4 \n"
"loc_FF8AEAF8:\n"
      "LDR     R0, [SP, #0x28] \n"
      "LDR     R2, [SP, #0xC] \n"
      "MOV     R1, R9 \n"
      "BL      sub_FF8AE724 \n"
      "B       loc_FF8AED8C \n"
"loc_FF8AEB0C:\n"
      "LDR     R1, [R0, #0x7C] \n"
      "LDR     R12, [R0, #0x8C] \n"
      "MOV     R2, R9 \n"
      "ADD     R0, R0, #4 \n"
      "BLX     R12 \n"
      "B       loc_FF8AED8C \n"
"loc_FF8AEB24:\n"
      "CMP     R1, #0x24 \n"
      "CMPNE   R1, #0x25 \n"
      "BNE     loc_FF8AEB70 \n"
      "LDR     R1, [R0, #0x7C] \n"
      "ADD     R1, R1, R1, LSL #1 \n"
      "ADD     R1, R0, R1, LSL #2 \n"
      "SUB     R1, R1, #8 \n"
      "LDMIA   R1, {R2,R3,R9} \n"
      "STMIA   R5, {R2,R3,R9} \n"
      "BL      sub_FF8ABD78 \n"
      "LDR     R0, [SP, #0x28] \n"
      "LDR     R1, [R0, #0x7C] \n"
      "LDR     R3, [R0, #0x8C] \n"
      "LDR     R2, [R0, #0x90] \n"
      "ADD     R0, R0, #4 \n"
      "BLX     R3 \n"
      "LDR     R0, [SP, #0x28] \n"
      "BL      sub_FF8AC1B8 \n"
      "B       loc_FF8AED8C \n"
"loc_FF8AEB70:\n"
      "ADD     R1, R0, #4 \n"
      "LDMIA   R1, {R2,R3,R9} \n"
      "STMIA   R5, {R2,R3,R9} \n"
      "LDR     R1, [R0] \n"
      "CMP     R1, #0x28 \n"
      "ADDCC   PC, PC, R1, LSL #2 \n"
      "B       loc_FF8AED74 \n"
      "B       loc_FF8AEC2C \n"
      "B       loc_FF8AEC2C \n"
      "B       loc_FF8AEC34 \n"
      "B       loc_FF8AEC3C \n"
      "B       loc_FF8AEC3C \n"
      "B       loc_FF8AEC3C \n"
      "B       loc_FF8AEC2C \n"
      "B       loc_FF8AEC34 \n"
      "B       loc_FF8AEC3C \n"
      "B       loc_FF8AEC3C \n"
      "B       loc_FF8AEC54 \n"
      "B       loc_FF8AEC54 \n"
      "B       loc_FF8AED60 \n"
      "B       loc_FF8AED68 \n"
      "B       loc_FF8AED68 \n"
      "B       loc_FF8AED68 \n"
      "B       loc_FF8AED68 \n"
      "B       loc_FF8AED70 \n"
      "B       loc_FF8AED74 \n"
      "B       loc_FF8AED74 \n"
      "B       loc_FF8AED74 \n"
      "B       loc_FF8AED74 \n"
      "B       loc_FF8AED74 \n"
      "B       loc_FF8AED74 \n"
      "B       loc_FF8AEC44 \n"
      "B       loc_FF8AEC4C \n"
      "B       loc_FF8AEC4C \n"
      "B       loc_FF8AEC4C \n"
      "B       loc_FF8AEC60 \n"
      "B       loc_FF8AEC60 \n"
      "B       loc_FF8AEC68 \n"
      "B       loc_FF8AECA0 \n"
      "B       loc_FF8AECD8 \n"
      "B       loc_FF8AED10 \n"
      "B       loc_FF8AED48 \n"
      "B       loc_FF8AED48 \n"
      "B       loc_FF8AED74 \n"
      "B       loc_FF8AED74 \n"
      "B       loc_FF8AED50 \n"
      "B       loc_FF8AED58 \n"
"loc_FF8AEC2C:\n"
      "BL      sub_FF8AA6FC \n"
      "B       loc_FF8AED74 \n"
"loc_FF8AEC34:\n"
      "BL      sub_FF8AA9A0 \n"
      "B       loc_FF8AED74 \n"
"loc_FF8AEC3C:\n"
      "BL      sub_FF8AABC8 \n"
      "B       loc_FF8AED74 \n"
"loc_FF8AEC44:\n"
      "BL      sub_FF8AAEEC \n"
      "B       loc_FF8AED74 \n"
"loc_FF8AEC4C:\n"
      "BL      sub_FF8AB104 \n"
      "B       loc_FF8AED74 \n"
"loc_FF8AEC54:\n"
//      "BL      sub_FF8AB4B0 \n" //original
      "BL      sub_FF8AB4B0_my \n" //patched
      "MOV     R8, #0 \n"
      "B       loc_FF8AED74 \n"
"loc_FF8AEC60:\n"
      "BL      sub_FF8AB5F0 \n"
      "B       loc_FF8AED74 \n"
"loc_FF8AEC68:\n"
      "LDRH    R1, [R0, #4] \n"
      "STRH    R1, [SP, #0x1C] \n"
      "LDRH    R1, [R4, #2] \n"
      "STRH    R1, [SP, #0x1E] \n"
      "LDRH    R1, [R4, #4] \n"
      "STRH    R1, [SP, #0x20] \n"
      "LDRH    R1, [R4, #6] \n"
      "STRH    R1, [SP, #0x22] \n"
      "LDRH    R1, [R0, #0xC] \n"
      "STRH    R1, [SP, #0x24] \n"
      "LDRH    R1, [R4, #0xA] \n"
      "STRH    R1, [SP, #0x26] \n"
      "BL      sub_FF8AFCA8 \n"
      "B       loc_FF8AED74 \n"
"loc_FF8AECA0:\n"
      "LDRH    R1, [R0, #4] \n"
      "STRH    R1, [SP, #0x1C] \n"
      "LDRH    R1, [R4, #2] \n"
      "STRH    R1, [SP, #0x1E] \n"
      "LDRH    R1, [R4, #4] \n"
      "STRH    R1, [SP, #0x20] \n"
      "LDRH    R1, [R4, #6] \n"
      "STRH    R1, [SP, #0x22] \n"
      "LDRH    R1, [R4, #8] \n"
      "STRH    R1, [SP, #0x24] \n"
      "LDRH    R1, [R4, #0xA] \n"
      "STRH    R1, [SP, #0x26] \n"
      "BL      sub_FF8AFE18 \n"
      "B       loc_FF8AED74 \n"
"loc_FF8AECD8:\n"
      "LDRH    R1, [R4] \n"
      "STRH    R1, [SP, #0x1C] \n"
      "LDRH    R1, [R0, #6] \n"
      "STRH    R1, [SP, #0x1E] \n"
      "LDRH    R1, [R4, #4] \n"
      "STRH    R1, [SP, #0x20] \n"
      "LDRH    R1, [R4, #6] \n"
      "STRH    R1, [SP, #0x22] \n"
      "LDRH    R1, [R4, #8] \n"
      "STRH    R1, [SP, #0x24] \n"
      "LDRH    R1, [R4, #0xA] \n"
      "STRH    R1, [SP, #0x26] \n"
      "BL      sub_FF8AFECC \n"
      "B       loc_FF8AED74 \n"
"loc_FF8AED10:\n"
      "LDRH    R1, [R4] \n"
      "STRH    R1, [SP, #0x1C] \n"
      "LDRH    R1, [R4, #2] \n"
      "STRH    R1, [SP, #0x1E] \n"
      "LDRH    R1, [R4, #4] \n"
      "STRH    R1, [SP, #0x20] \n"
      "LDRH    R1, [R4, #6] \n"
      "STRH    R1, [SP, #0x22] \n"
      "LDRH    R1, [R0, #0xC] \n"
      "STRH    R1, [SP, #0x24] \n"
      "LDRH    R1, [R4, #0xA] \n"
      "STRH    R1, [SP, #0x26] \n"
      "BL      sub_FF8AFF74 \n"
      "B       loc_FF8AED74 \n"
"loc_FF8AED48:\n"
      "BL      sub_FF8ABB2C \n"
      "B       loc_FF8AED74 \n"
"loc_FF8AED50:\n"
      "BL      sub_FF8AC2BC \n"
      "B       loc_FF8AED74 \n"
"loc_FF8AED58:\n"
      "BL      sub_FF8AC5A0 \n"
      "B       loc_FF8AED74 \n"
"loc_FF8AED60:\n"
      "BL      sub_FF8AC860 \n"
      "B       loc_FF8AED74 \n"
"loc_FF8AED68:\n"
      "BL      sub_FF8ACA1C \n"
      "B       loc_FF8AED74 \n"
"loc_FF8AED70:\n"
      "BL      sub_FF8ACB84 \n"
"loc_FF8AED74:\n"
      "LDR     R0, [SP, #0x28] \n"
      "LDR     R1, [R0, #0x7C] \n"
      "LDR     R2, [R0, #0x90] \n"
      "LDR     R3, [R0, #0x8C] \n"
"loc_FF8AED84:\n"
      "ADD     R0, R0, #4 \n"
      "BLX     R3 \n"
"loc_FF8AED8C:\n"
      "LDR     R0, [SP, #0x28] \n"
      "LDR     R0, [R0] \n"
      "CMP     R0, #0x10 \n"
      "BEQ     loc_FF8AEDC4 \n"
      "BGT     loc_FF8AEDB4 \n"
      "CMP     R0, #1 \n"
      "CMPNE   R0, #4 \n"
      "CMPNE   R0, #0xE \n"
      "BNE     loc_FF8AEDF8 \n"
      "B       loc_FF8AEDC4 \n"
"loc_FF8AEDB4:\n"
      "CMP     R0, #0x13 \n"
      "CMPNE   R0, #0x17 \n"
      "CMPNE   R0, #0x1A \n"
      "BNE     loc_FF8AEDF8 \n"
"loc_FF8AEDC4:\n"
      "LDRSH   R0, [R4] \n"
      "CMN     R0, #0xC00 \n"
      "LDRNESH R1, [R4, #8] \n"
      "CMNNE   R1, #0xC00 \n"
      "STRNEH  R0, [SP, #0x1C] \n"
      "STRNEH  R1, [SP, #0x24] \n"
      "BNE     loc_FF8AEDF8 \n"
      "ADD     R0, SP, #0x10 \n"
      "BL      sub_FF8B0228 \n"
      "LDRH    R0, [SP, #0x10] \n"
      "STRH    R0, [SP, #0x1C] \n"
      "LDRH    R0, [SP, #0x18] \n"
      "STRH    R0, [SP, #0x24] \n"
"loc_FF8AEDF8:\n"
      "LDR     R0, [SP, #0x28] \n"
      "CMP     R8, #1 \n"
      "BNE     loc_FF8AEE48 \n"
      "LDR     R1, [R0, #0x7C] \n"
      "MOV     R2, #0xC \n"
      "ADD     R1, R1, R1, LSL #1 \n"
      "ADD     R0, R0, R1, LSL #2 \n"
      "SUB     R8, R0, #8 \n"
      "LDR     R0, =0x55E1C \n"
      "ADD     R1, SP, #0x1C \n"
      "BL      sub_003FC17C \n" //RAM
      "LDR     R0, =0x55E28 \n"
      "MOV     R2, #0xC \n"
      "ADD     R1, SP, #0x1C \n"
      "BL      sub_003FC17C \n" //RAM
      "LDR     R0, =0x55E34 \n"
      "MOV     R2, #0xC \n"
      "MOV     R1, R8 \n"
      "BL      sub_003FC17C \n" //RAM
      "B       loc_FF8AEEC0 \n"
"loc_FF8AEE48:\n"
      "LDR     R0, [R0] \n"
      "MOV     R3, #1 \n"
      "CMP     R0, #0xB \n"
      "BNE     loc_FF8AEE8C \n"
      "MOV     R2, #0 \n"
      "STRD    R2, [SP] \n"
      "MOV     R2, R3 \n"
      "MOV     R1, R3 \n"
      "MOV     R0, #0 \n"
      "BL      sub_FF8AA4DC \n"
      "MOV     R3, #1 \n"
      "MOV     R2, #0 \n"
      "STRD    R2, [SP] \n"
      "MOV     R2, R3 \n"
      "MOV     R1, R3 \n"
      "MOV     R0, #0 \n"
      "B       loc_FF8AEEBC \n"
"loc_FF8AEE8C:\n"
      "MOV     R2, #1 \n"
      "STRD    R2, [SP] \n"
      "MOV     R3, R2 \n"
      "MOV     R1, R2 \n"
      "MOV     R0, R2 \n"
      "BL      sub_FF8AA4DC \n"
      "MOV     R3, #1 \n"
      "MOV     R2, R3 \n"
      "MOV     R1, R3 \n"
      "MOV     R0, R3 \n"
      "STR     R3, [SP] \n"
      "STR     R3, [SP, #4] \n"
"loc_FF8AEEBC:\n"
      "BL      sub_FF8AA648 \n"
"loc_FF8AEEC0:\n"
      "LDR     R0, [SP, #0x28] \n"
      "BL      sub_FF8AFC14 \n"
      "B       loc_FF8AE858 \n"
	);
}

//** sub_FF8AB4B0_my  @ 0xFF8AB4B0 
//crash if using this function
void __attribute__((naked,noinline)) sub_FF8AB4B0_my(  ) { 
asm volatile (
      "STMFD   SP!, {R4-R8,LR} \n"
      "LDR     R7, =0x3D78 \n"
      "MOV     R4, R0 \n"
      "LDR     R0, [R7, #0x1C] \n"
      "MOV     R1, #0x3E \n"
      "BL      sub_003FACA0 \n" // RAM
      "MOV     R2, #0 \n"
      "LDRSH   R0, [R4, #4] \n"
      "MOV     R1, R2 \n"
      "BL      sub_FF8AA1E4 \n"
      "MOV     R6, R0 \n"
      "LDRSH   R0, [R4, #6] \n"
      "BL      sub_FF8AA334 \n"
      "LDRSH   R0, [R4, #8] \n"
      "BL      sub_FF8AA38C \n"
      "LDRSH   R0, [R4, #0xA] \n"
      "BL      sub_FF8AA3E4 \n"
      "LDRSH   R0, [R4, #0xC] \n"
      "MOV     R1, #0 \n"
      "BL      sub_FF8AA43C \n"
      "MOV     R5, R0 \n"
      "LDR     R0, [R4] \n"
      "LDR     R8, =0x55E34 \n"
      "CMP     R0, #0xB \n"
      "MOVEQ   R6, #0 \n"
      "MOVEQ   R5, R6 \n"
      "BEQ     loc_FF8AB544 \n"
      "CMP     R6, #1 \n"
      "BNE     loc_FF8AB544 \n"
      "LDRSH   R0, [R4, #4] \n"
      "LDR     R1, =0xFF8AA144 \n"
      "MOV     R2, #2 \n"
      "BL      sub_FF954DE4 \n"
      "STRH    R0, [R4, #4] \n"
      "MOV     R0, #0 \n"
      "STR     R0, [R7, #0x28] \n"
      "B       loc_FF8AB54C \n"
"loc_FF8AB544:\n"
      "LDRH    R0, [R8] \n"
      "STRH    R0, [R4, #4] \n"
"loc_FF8AB54C:\n"
      "CMP     R5, #1 \n"
      "LDRNEH  R0, [R8, #8] \n"
      "BNE     loc_FF8AB568 \n"
      "LDRSH   R0, [R4, #0xC] \n"
      "LDR     R1, =0xFF8AA1C8 \n"
      "MOV     R2, #0x20 \n"
      "BL      sub_FF8AFC64 \n"
"loc_FF8AB568:\n"
      "STRH    R0, [R4, #0xC] \n"
      "LDRSH   R0, [R4, #6] \n"
//      "BL      sub_FF89A150 \n" //original
      "BL      sub_FF89A150_my \n" //patched
      "B       sub_FF8AB574 \n" // continue in firmware
	);
}

//** sub_FF89A150_my  @ 0xFF89A150 

void __attribute__((naked,noinline)) sub_FF89A150_my() { 
asm volatile (
      "STMFD   SP!, {R4-R6,LR} \n"
      "LDR     R5, =0x39C8 \n"
      "MOV     R4, R0 \n"
      "LDR     R0, [R5, #4] \n"
      "CMP     R0, #1 \n"
      "LDRNE   R1, =0x14D \n"
      "LDRNE   R0, =0xFF899F88 \n" //  ; "Shutter.c"
      "BLNE    _DebugAssert \n"
      "CMN     R4, #0xC00 \n"
      "LDREQSH R4, [R5, #2] \n"
      "CMN     R4, #0xC00 \n"
      "LDREQ   R1, =0x153 \n"
      "LDREQ   R0, =0xFF899F88 \n" //  ; "Shutter.c"
      "STRH    R4, [R5, #2] \n"
      "BLEQ    _DebugAssert \n" //RAM
      "MOV     R0, R4 \n"
//      "BL      sub_FF9D8DEC \n" //original _apex2us
      "BL      apex2us \n"   //patch
      "MOV     R4, R0 \n"
      "BL      sub_FF8E94F4 \n"
      "MOV     R0, R4 \n"
      "BL      sub_FF8F1CFC \n"
      "TST     R0, #1 \n"
      "LDMEQFD SP!, {R4-R6,PC} \n"
      "LDMFD   SP!, {R4-R6,LR} \n"
      "MOV     R1, #0x158 \n"
      "LDR     R0, =0xFF899F88 \n" //  ; "Shutter.c"
      "B       _DebugAssert \n" //RAM
	);
}

/*************** filewritetask ***************/

void __attribute__((naked,noinline)) filewritetask(  ) { //@ 0xFFA52524
asm volatile (
      "    STMFD   SP!, {R1-R7,LR} \n" 
      "    LDR     R7, =0x96B8 \n" 
      "    MOV     R6, #0 \n" 
"loc_FFA52530:\n"
      "    LDR     R0, [R7, #0x14] \n" 
      "    MOV     R2, #0 \n" 
      "    ADD     R1, SP, #8 \n" 
      "    MOV     R5, R7 \n" 
      "    BL      sub_003F7218 \n" //ReceiveMessageQueue
      "    CMP     R0, #0 \n" 
      "    LDRNE   R1, =0x38E \n" 
      "    LDRNE   R0, =0xFFA52668 \n" // dwFWrite.c
      "    BLNE    sub_003F6AFC \n" //DebugAssert
      "    LDR     R0, [SP, #8] \n" 
      "    LDR     R1, [R0] \n" // state (aka msg number)
      "    CMP     R1, #0xB \n" 
      "    ADDCC   PC, PC, R1, LSL #2 \n" 
      "    B       loc_FFA52530 \n" 
      "    B       loc_FFA52638 \n" 
      "    B       loc_FFA52638 \n" 
      "    B       loc_FFA52638 \n" 
      "    B       loc_FFA52638 \n" 
      "    B       loc_FFA52638 \n" 
      "    B       loc_FFA52638 \n" 
      "    B       loc_FFA52638 \n" 
      "    B       loc_FFA52640 \n" 
      "    B       loc_FFA52594 \n" 
      "    B       loc_FFA52604 \n" 
      "    B       loc_FFA525FC \n" 
"loc_FFA52594:\n"                   // (state 8) empties the message queue
      "    STR     R6, [SP] \n" 
"loc_FFA52598:\n"
      "    LDR     R0, [R5, #0x14] \n" 
      "    MOV     R1, SP \n" 
      "    BL      sub_003F745C \n" //GetNumberOfPostedMessages
      "    LDR     R0, [SP] \n" 
      "    CMP     R0, #0 \n" 
      "    BEQ     loc_FFA525C4 \n" // no message left in queue
      "    LDR     R0, [R5, #0x14] \n" 
      "    MOV     R2, #0 \n" 
      "    ADD     R1, SP, #4 \n" 
      "    BL      sub_003F7218 \n" //ReceiveMessageQueue
      "    B       loc_FFA52598 \n" 
"loc_FFA525C4:\n"
      "    LDR     R0, [R5, #8] \n" // file descriptor
      "    CMN     R0, #1 \n" 
      "    BEQ     loc_FFA525F0 \n" 
      "    BL      fwt_close\n"     // mod! sub_FF830158 Close
"loc_FFA525D4:\n"
      "    MVN     R0, #0 \n" 
      "    STR     R0, [R5, #8] \n" // file descriptor
      "    LDR     R0, =0x132120 \n" 
      "    STR     R6, [R5, #4] \n" 
      "    BL      sub_FF86671C \n" // path check or something
      "    MOV     R1, #0 \n" 
      "    BL      sub_FF8647B8 \n" // file semaphore related
"loc_FFA525F0:\n"
      "    LDR     R0, [R5, #0x10] \n" 
      "    BL      sub_003F7704 \n" //GiveSemaphore
      "    B       loc_FFA52530 \n" 
"loc_FFA525FC:\n"
      "    BL      sub_FFA52220_my \n" // -> open stage (state 10)
      "    B       loc_FFA52530 \n" 
"loc_FFA52604:\n"                   // (state 9), append? overwrite?
      "    LDR     R1, [R0, #4] \n" // seek offset
      "    MOV     R4, R0 \n" 
      "    LDR     R0, [R5, #8] \n" // file descriptor
      "    MOV     R2, #0 \n"       // SEEK_SET
      "    BL      fwt_lseek\n"     // mod! sub_FF8302F0  Lseek
      "    CMN     R0, #1 \n" 
      "    LDREQ   R0, =0x9200013 \n" 
      "    MOV     R1, R4 \n" 
      "    STREQ   R0, [R4, #0x14] \n" 
      "    MOVNE   R0, #0 \n"       // next state = 0 (write)
      "    MOVEQ   R0, #7 \n"       // next state = 7 (close)
      "    BL      sub_FFA52164 \n" // send_msg_to_filewritetask
      "    B       loc_FFA52530 \n" 
"loc_FFA52638:\n"
      "    BL      sub_FFA52860_my \n" // -> write stage (states 0..6)
      "    B       loc_FFA52530 \n" 
"loc_FFA52640:\n"
      "    BL      sub_FFA5238C_my \n" // -> close stage (state 7)
      "    B       loc_FFA52530 \n"
      );
}


void __attribute__((naked,noinline)) sub_FFA52220_my(  ) { //open
asm volatile (
      "    STMFD   SP!, {R4-R9,LR} \n" 
      "    LDR     R6, =0x96B8 \n" 
      "    MOV     R4, R0 \n" 
//hook start placed here to avoid bne a few instructions below
      "STMFD SP!, {R4-R12,LR}\n"
      //"MOV R0, R4\n"        //data block start, commented out as R0 is already holding what we need
      "BL filewrite_main_hook\n"
      "LDMFD SP!, {R4-R12,LR}\n"
//hook end
      "    LDR     R0, [R6, #4] \n" 
      "    SUB     SP, SP, #0x3C \n" 
      "    CMP     R0, #0 \n" 
      "    BNE     loc_FFA5235C \n"
      "    ADD     R0, R4, #0x54 \n" 
      "    BL      sub_FF86671C \n"   // path check or something
      "    MOV     R1, #0 \n" 
      "    BL      sub_FF86472C \n" 
      "    LDR     R0, [R4, #0x10] \n" 
      "    BL      sub_FF8636F0 \n" 
      "    LDR     R0, [R4, #0x50] \n" 
      "    LDR     R9, =0x1B6 \n" 
      "    CMP     R0, #1 \n" 
      "    LDREQ   R0, [R4, #0xC] \n" 
      "    ADD     R7, R4, #0x54 \n" 
      "    ORREQ   R0, R0, #0x8000 \n" 
      "    STREQ   R0, [R4, #0xC] \n" 
      "    LDR     R8, [R4, #0xC] \n" 
      "    LDR     R5, [R4, #0x10] \n" 
      "    MOV     R2, R9 \n" 
      "    MOV     R1, R8 \n" 
      "    MOV     R0, R7 \n" 
      "    BL      fwt_open\n"  //mod! sub_FF830154 Open
      "    CMN     R0, #1 \n" // rom:ffa52288
      "    BNE     loc_FFA522EC \n"
      "    MOV     R0, R7 \n" 
      "    BL      sub_FF83083C \n" 
      "    MOV     R2, #0xF \n" 
      "    MOV     R1, R7 \n" 
      "    ADD     R0, SP, #4 \n" 
      "    BL      sub_003FC17C \n" 
      "    MOV     R0, #0 \n" 
      "    LDR     R1, =0x41FF \n" 
      "    STRB    R0, [SP, #0x13] \n" 
      "    STR     R1, [SP, #0x24] \n" 
      "    MOV     R1, #0x10 \n" 
      "    STR     R0, [SP, #0x2C] \n" 
      "    STR     R1, [SP, #0x28] \n" 
      "    ADD     R1, SP, #0x24 \n" 
      "    ADD     R0, SP, #4 \n" 
      "    STR     R5, [SP, #0x30] \n" 
      "    STR     R5, [SP, #0x34] \n" 
      "    STR     R5, [SP, #0x38] \n" 
      "    BL      sub_FF863FF8 \n" 
      "    MOV     R2, R9 \n" 
      "    MOV     R1, R8 \n" 
      "    MOV     R0, R7 \n" 
      "    BL      sub_FF830154 \n" //Open
"loc_FFA522EC:\n"
      "    CMN     R0, #1 \n" 
      "    MOV     R5, R0 \n" 
      "    STR     R0, [R6, #8] \n" 
      "    BNE     loc_FFA52328 \n" 
      "    ADD     R0, R4, #0x54 \n" 
      "    BL      sub_FF86671C \n" // path check or something
      "    LDR     R1, [R6, #0x1C] \n" 
      "    BL      sub_FF8647B8 \n" 
      "    LDR     R1, [R6, #0x18] \n" 
      "    CMP     R1, #0 \n" 
      "    BEQ     loc_FFA52384 \n" 
      "    ADD     SP, SP, #0x3C \n" 
      "    LDMFD   SP!, {R4-R9,LR} \n" 
      "    LDR     R0, =0x9200001 \n" 
      "    BX      R1 \n" 
"loc_FFA52328:\n"
      "    MOV     R0, #1 \n" 
      "    STR     R0, [R6, #4] \n" 
      "    LDR     R0, =0x132120 \n" 
      "    MOV     R2, #0x20 \n" 
      "    ADD     R1, R4, #0x54 \n" 
      "    BL      sub_003FC364 \n" 
//mod start      
      "LDR R3, =current_write_ignored\n"
      "LDR R3, [R3]\n"
      "CMP R3, #0\n"
      "BNE loc_FFA5235C\n" // jump over the next block
//mod end
      "    LDR     R1, [R4, #8] \n" //total file size
      "    MOV     R0, R5 \n"       //file descriptor
      "    BL      sub_FF830430 \n" //function that checks something on the new file
      "    CMP     R0, #0 \n" 
      "    MOVEQ   R1, R4 \n" 
      "    MOVEQ   R0, #7 \n"       //check failed: close
      "    BEQ     loc_FFA52380 \n" 
"loc_FFA5235C:\n"
      "    LDR     R0, [R4, #0x50] \n" 
      "    CMP     R0, #2 \n" 
      "    BEQ     loc_FFA52378 \n" 
      "    LDR     R0, [R4, #4] \n" 
      "    CMP     R0, #0 \n" 
      "    MOVEQ   R1, R4 \n" 
      "    BEQ     loc_FFA52380 \n" 
"loc_FFA52378:\n"
      "    MOV     R1, R4 \n" 
      "    MOV     R0, #9 \n" // next state, the weird "append/overwrite" mode
"loc_FFA52380:\n"
      "    BL      sub_FFA52164 \n" // send_msg_to_filewritetask
"loc_FFA52384:\n"
      "    ADD     SP, SP, #0x3C \n" 
      "    LDMFD   SP!, {R4-R9,PC} \n"
      );
}


void __attribute__((naked,noinline)) sub_FFA52860_my(  ) { //write
asm volatile (
      "    STMFD   SP!, {R4-R10,LR} \n" 
      "    MOV     R5, R0 \n" 
      "    LDR     R0, [R0] \n" 
      "    CMP     R0, #6 \n" 
      "    BHI     loc_FFA5288C \n" 
      "    ADD     R0, R5, R0, LSL #3 \n" 
      "    LDR     R8, [R0, #0x18]! \n" // first data chunk address
      "    LDR     R7, [R0, #4] \n" 
      "    CMP     R7, #0 \n" 
      "    BNE     loc_FFA528A4 \n" 
      "    B       loc_FFA52898 \n" 
"loc_FFA5288C:\n"
      "    LDR     R1, =0x2DD \n" 
      "    LDR     R0, =0xFFA52668 \n" 
      "    BL      sub_003F6AFC \n" //DebugAssert
"loc_FFA52898:\n"
      "    MOV     R1, R5 \n" 
      "    MOV     R0, #7 \n" 
      "    B       loc_FFA52938 \n" 
"loc_FFA528A4:\n"
      "    LDR     R9, =0x96B8 \n" 
      "    MOV     R4, R7 \n" 
"loc_FFA528AC:\n"
      "    LDR     R0, [R5, #4] \n" 
      "    CMP     R4, #0x1000000 \n" 
      "    MOVLS   R6, R4 \n" 
      "    MOVHI   R6, #0x1000000 \n" 
      "    BIC     R1, R0, #0xFF000000 \n" 
      "    CMP     R1, #0 \n" 
      "    BICNE   R0, R0, #0xFF000000 \n" 
      "    RSBNE   R0, R0, #0x1000000 \n" 
      "    CMPNE   R6, R0 \n" 
      "    MOVHI   R6, R0 \n" 
      "    LDR     R0, [R9, #8] \n" 
      "    MOV     R2, R6 \n" 
      "    MOV     R1, R8 \n" 
      "    BL      fwt_write\n"     // mod! sub_FF830290 Write
      "    LDR     R1, [R5, #4] \n"
      "    CMP     R6, R0 \n" 
      "    ADD     R1, R1, R0 \n" 
      "    STR     R1, [R5, #4] \n" 
      "    BEQ     loc_FFA5290C \n" 
      "    CMN     R0, #1 \n" 
      "    LDRNE   R0, =0x9200015 \n" 
      "    LDREQ   R0, =0x9200005 \n" 
      "    STR     R0, [R5, #0x14] \n" 
      "    B       loc_FFA52898 \n" 
"loc_FFA5290C:\n"
      "    SUB     R4, R4, R0 \n" 
      "    CMP     R4, R7 \n" 
      "    ADD     R8, R8, R0 \n" 
      "    MOVCS   R1, #0x308 \n" 
      "    LDRCS   R0, =0xFFA52668 \n" 
      "    BLCS    sub_003F6AFC \n" //DebugAssert
      "    CMP     R4, #0 \n" 
      "    BNE     loc_FFA528AC \n" 
      "    LDR     R0, [R5] \n" 
      "    MOV     R1, R5 \n" 
      "    ADD     R0, R0, #1 \n" 
"loc_FFA52938:\n"
      "    LDMFD   SP!, {R4-R10,LR} \n" 
      "    B       sub_FFA52164 \n" // send_msg_to_filewritetask
      ".ltorg\n" //+
      );
}


void __attribute__((naked,noinline)) sub_FFA5238C_my(  ) { //close
asm volatile (
      "    STMFD   SP!, {R4-R6,LR} \n" 
      "    MOV     R4, R0 \n" 
      "    LDR     R0, [R0, #0x50] \n" 
      "    LDR     R5, =0x96B8 \n" 
      "    CMP     R0, #3 \n" 
      "    SUB     SP, SP, #0x38 \n" 
      "    BEQ     loc_FFA52504 \n" 
      "    LDR     R0, [R5, #8] \n" 
      "    CMN     R0, #1 \n" 
      "    BEQ     loc_FFA523E0 \n" 
      "    LDR     R1, [R4, #0xC] \n" 
      "    LDR     R6, =0x9200003 \n" 
      "    TST     R1, #0x8000 \n" 
      "    BEQ     loc_FFA523CC \n" 
//mod start      
      "LDR R3, =current_write_ignored\n"
      "LDR R3, [R3]\n"
      "CMP R3, #0\n"
      "BNE loc_FFA523CC\n" // jump over the next block
//mod end
      "    BL      sub_FF83015C \n"     // fsionotify related
      "    B       loc_FFA523D0 \n" 
"loc_FFA523CC:\n"
      "    BL      fwt_close\n"         // mod! sub_FF830158 Close
"loc_FFA523D0:\n"
      "    CMP     R0, #0 \n" 
      "    MVN     R0, #0 \n" 
      "    STRNE   R6, [R4, #0x14] \n" 
      "    STR     R0, [R5, #8] \n" 
"loc_FFA523E0:\n"
      "    LDR     R0, [R4, #0x14] \n" 
      "    TST     R0, #1 \n" 
      "    BNE     loc_FFA524E8 \n" 
      "    LDR     R0, [R4, #0xC] \n" 
      "    TST     R0, #8 \n" 
      "    BNE     loc_FFA52404 \n" 
      "    LDR     R0, [R4, #0x50] \n" 
      "    CMP     R0, #3 \n" 
      "    BNE     loc_FFA52434 \n" 
"loc_FFA52404:\n"
      "    ADD     R1, SP, #0x20 \n" 
      "    ADD     R0, R4, #0x54 \n" 
      "    BL      sub_FF863F40 \n" 
      "    CMP     R0, #0 \n" 
      "    LDREQ   R1, =0x346 \n" 
      "    LDREQ   R0, =0xFFA52668 \n" 
      "    BLEQ    sub_003F6AFC \n" //DebugAssert
      "    LDR     R0, [SP, #0x28] \n" 
      "    LDR     R1, [R4, #4] \n" 
      "    ADD     R0, R0, R1 \n" 
      "    STR     R0, [SP, #0x28] \n" 
      "    B       loc_FFA52464 \n" 
"loc_FFA52434:\n"
      "    LDR     R0, =0x81FF \n" 
      "    STR     R0, [SP, #0x20] \n" 
      "    MOV     R0, #0x20 \n" 
      "    STR     R0, [SP, #0x24] \n" 
      "    LDR     R0, [R4, #4] \n" 
      "    STR     R0, [SP, #0x28] \n" 
      "    LDR     R0, [R4, #0x10] \n" 
      "    STR     R0, [SP, #0x2C] \n" 
      "    LDR     R0, [R4, #0x10] \n" 
      "    STR     R0, [SP, #0x30] \n" 
      "    LDR     R0, [R4, #0x10] \n" 
      "    STR     R0, [SP, #0x34] \n" 
"loc_FFA52464:\n"
      "    LDR     R0, [R4, #0x50] \n" 
      "    CMP     R0, #2 \n" 
      "    BEQ     loc_FFA524E8 \n" 
      "    ADD     R1, SP, #0x20 \n" 
      "    ADD     R0, R4, #0x54 \n" 
      "    BL      sub_FF863FF8 \n" 
      "    LDR     R0, [R4, #0x50] \n" 
      "    CMP     R0, #1 \n" 
      "    BNE     loc_FFA524E8 \n" 
      "    MOV     R2, #0x20 \n" 
      "    ADD     R1, R4, #0x54 \n" 
      "    MOV     R0, SP \n" 
      "    BL      sub_003FC364 \n" 
      "    MOV     R0, SP \n" 
      "    BL      sub_FF812E38 \n" 
      "    MOV     R2, #0x54 \n" 
      "    ADD     R0, R0, SP \n" 
      "    MOV     R1, #0x4D \n" 
      "    STRB    R2, [R0, #-3] \n" 
      "    STRB    R1, [R0, #-2] \n" 
      "    MOV     R1, #0x50 \n" 
      "    STRB    R1, [R0, #-1] \n" 
      "    MOV     R1, SP \n" 
      "    ADD     R0, R4, #0x54 \n" 
      "    BL      sub_FF863878 \n" 
      "    CMP     R0, #0 \n" 
      "    MOVEQ   R1, #0x164 \n" 
      "    LDREQ   R0, =0xFFA52668 \n" 
      "    BLEQ    sub_003F6AFC \n" //DebugAssert
      "    MOV     R0, SP \n" 
      "    BL      sub_FF864454 \n" 
      "    ADD     R0, R4, #0x54 \n" 
      "    BL      sub_FF864454 \n" 
"loc_FFA524E8:\n"
      "    ADD     R0, R4, #0x54 \n" 
      "    BL      sub_FF86671C \n" // path check or something
      "    LDR     R1, [R5, #0x1C] \n" 
      "    BL      sub_FF8647B8 \n" 
      "    MOV     R0, #0 \n" 
      "    STR     R0, [R5, #4] \n" 
      "    B       loc_FFA5250C \n" 
"loc_FFA52504:\n"
      "    LDR     R0, [R5, #0x1C] \n" 
      "    BLX     R0 \n" 
"loc_FFA5250C:\n"
      "    LDR     R1, [R5, #0x18] \n" 
      "    CMP     R1, #0 \n" 
      "    LDRNE   R0, [R4, #0x14] \n" 
      "    BLXNE   R1 \n" 
      "    ADD     SP, SP, #0x38 \n" 
      "    LDMFD   SP!, {R4-R6,PC} \n"
      );
}
