
#OBJS=boot.o stubs_min.o stubs_auto.o stubs_entry.o lib.o stubs_entry_2.o capt_seq.o movie_rec.o
#STUBS_AUTO_DEPS=boot.c capt_seq.c movie_rec.c

OBJS=boot.o stubs_min.o stubs_auto.o stubs_entry.o lib.o stubs_entry_2.o capt_seq.o debug.o movie_rec.o filewrite.o
STUBS_AUTO_DEPS=boot.c capt_seq.c debug.c movie_rec.c filewrite.c

include ../../../makefile_sub.inc
