/*
 * movie_rec.c - auto-generated by CHDK code_gen.
 */
#include "conf.h"

void change_video_tables(int a, int b){
}

void  set_quality(int *x){ // -17 highest; +12 lowest
 if (conf.video_mode) *x=12-((conf.video_quality-1)*(12+17)/(99-1));
}


/*************************************************************/
//** movie_record_task @ 0xFF9934B0 - 0xFF993640, length=101
void __attribute__((naked,noinline)) movie_record_task() {
asm volatile (
"    STMFD   SP!, {R2-R10,LR} \n"
"    LDR     R8, =0xFF9930C4 \n"
"    LDR     R4, =0x7028 \n"
"    LDR     R9, =0x6D4 \n"
"    LDR     R10, =0x2710 \n"
"    MVN     R7, #0 \n"
"    MOV     R5, #1 \n"
"    MOV     R6, #0 \n"

"loc_FF9934D0:\n"
"    LDR     R0, [R4, #0x2C] \n"
"    MOV     R2, #0 \n"
"    ADD     R1, SP, #4 \n"
"    BL      sub_006B8458 /*_ReceiveMessageQueue*/ \n"
"    LDR     R0, [R4, #0x34] \n"
"    CMP     R0, #0 \n"
"    LDRNE   R0, [R4, #0x14] \n"
"    CMPNE   R0, #2 \n"
"    LDRNE   R0, [R4, #0x48] \n"
"    CMPNE   R0, #6 \n"
"    BNE     loc_FF993624 \n"
"    LDR     R0, [SP, #4] \n"
"    LDR     R1, [R0] \n"
"    SUB     R1, R1, #2 \n"
"    CMP     R1, #0xD \n"
"    ADDCC   PC, PC, R1, LSL#2 \n"
"    B       loc_FF993624 \n"
"    B       loc_FF993598 \n"
"    B       loc_FF9935C4 \n"
"    B       loc_FF9935D4 \n"
"    B       loc_FF9935DC \n"
"    B       loc_FF9935A0 \n"
"    B       loc_FF9935E4 \n"
"    B       loc_FF993610 \n"
"    B       loc_FF993618 \n"
"    B       loc_FF9935AC \n"
"    B       loc_FF993624 \n"
"    B       loc_FF993620 \n"
"    B       loc_FF993574 \n"
"    B       loc_FF993548 \n"

"loc_FF993548:\n"
"    STR     R6, [R4, #0x44] \n"
"    STR     R6, [R4, #0x38] \n"
"    STR     R7, [R4, #0xD0] \n"
"    STRH    R6, [R4, #8] \n"
"    STR     R8, [R4, #0xB0] \n"
"    LDR     R0, [R4, #0x14] \n"
"    ADD     R0, R0, #1 \n"
"    STR     R0, [R4, #0x14] \n"
"    MOV     R0, #6 \n"
"    STR     R0, [R4, #0x48] \n"
"    B       loc_FF993590 \n"

"loc_FF993574:\n"
"    STR     R6, [R4, #0x44] \n"
"    STR     R7, [R4, #0xD0] \n"
"    STR     R8, [R4, #0xB0] \n"
"    LDR     R0, [R4, #0x14] \n"
"    ADD     R0, R0, #1 \n"
"    STR     R0, [R4, #0x14] \n"
"    STR     R5, [R4, #0x48] \n"

"loc_FF993590:\n"
"    STR     R5, [R4, #0xC] \n"
"    B       loc_FF993624 \n"

"loc_FF993598:\n"
"    BL      sub_FF992DAC \n"
"    B       loc_FF993624 \n"

"loc_FF9935A0:\n"
"    LDR     R1, [R4, #0xB0] \n"
"    BLX     R1 \n"
//begin patch
"    LDR     R0, =video_compression_rate \n" // added
"    BL      set_quality \n"                 // added
//end patch
"    B       loc_FF993624 \n"

"loc_FF9935AC:\n"
"    LDR     R1, [R0, #0x18] \n"
"    LDR     R2, [R0, #0x28] \n"
"    LDR     R3, [R0, #0x24] \n"
"    LDR     R0, [R0, #4] \n"
"    BL      sub_FFABC0D4 \n"
"    B       loc_FF993624 \n"

"loc_FF9935C4:\n"
"    LDR     R0, [R4, #0x48] \n"
"    CMP     R0, #5 \n"
"    STRNE   R5, [R4, #0x38] \n"
"    B       loc_FF993624 \n"

"loc_FF9935D4:\n"
"    BL      sub_FF992A20 \n"
"    B       loc_FF993624 \n"

"loc_FF9935DC:\n"
"    BL      sub_FF9928E0 \n"
"    B       loc_FF993624 \n"

"loc_FF9935E4:\n"
"    LDR     R0, =0xCDF44 \n"
"    LDR     R0, [R0, #8] \n"
"    CMP     R0, #0 \n"
"    LDRNE   R2, =0xFF992800 \n"
"    LDRNE   R0, =0xFF992888 \n"
"    MOVNE   R3, #0 \n"
"    MOVNE   R1, R3 \n"
"    BLNE    sub_FF86B700 \n"
"    MOV     R0, #3 \n"
"    STR     R0, [R4, #0x48] \n"
"    B       loc_FF993624 \n"

"loc_FF993610:\n"
"    BL      sub_FF992788 \n"
"    B       loc_FF993624 \n"

"loc_FF993618:\n"
"    BL      sub_FF993EF0 \n"
"    B       loc_FF993624 \n"

"loc_FF993620:\n"
"    BL      sub_FF993E14 \n"

"loc_FF993624:\n"
"    LDR     R1, [SP, #4] \n"
"    LDR     R3, =0xFF99244C /*'MovieRecorder.c'*/ \n"
"    STR     R6, [R1] \n"
"    STR     R9, [SP] \n"
"    LDR     R0, [R4, #0x30] \n"
"    MOV     R2, R10 \n"
"    BL      sub_006B7CF4 /*_PostMessageQueueStrictly*/ \n"
"    B       loc_FF9934D0 \n"
);
}
