/*
 * movie_rec.c - auto-generated by CHDK code_gen.
 */
#include "conf.h"

void change_video_tables(__attribute__ ((unused))int a, __attribute__ ((unused))int b) {}

void  set_quality(int *x){ // -17 highest; +12 lowest
 if (conf.video_mode) *x=12-((conf.video_quality-1)*(12+17)/(99-1));
}

/*************************************************************/
//** movie_record_task @ 0xFF17D034 - 0xFF17D1AC, length=95
void __attribute__((naked,noinline)) movie_record_task() {
asm volatile (
"    STMFD   SP!, {R2-R10,LR} \n"
"    LDR     R6, =0xFF17BCA0 \n"
"    LDR     R7, =0xFF17CA28 \n"
"    LDR     R4, =0x6DC0 \n"
"    LDR     R9, =0x69B \n"
"    LDR     R10, =0x2710 \n"
"    MOV     R8, #1 \n"
"    MOV     R5, #0 \n"

"loc_FF17D054:\n"
"    LDR     R0, [R4, #0x24] \n"
"    MOV     R2, #0 \n"
"    ADD     R1, SP, #4 \n"
"    BL      sub_00477218 /*_ReceiveMessageQueue*/ \n"
"    LDR     R0, [R4, #0x2C] \n"
"    CMP     R0, #0 \n"
"    LDRNE   R0, [R4, #0xC] \n"
"    CMPNE   R0, #2 \n"
"    LDRNE   R0, [R4, #0x44] \n"
"    CMPNE   R0, #6 \n"
"    BNE     loc_FF17D190 \n"
"    LDR     R0, [SP, #4] \n"
"    LDR     R1, [R0] \n"
"    SUB     R1, R1, #2 \n"
"    CMP     R1, #0xD \n"
"    ADDCC   PC, PC, R1, LSL#2 \n"
"    B       loc_FF17D190 \n"
"    B       loc_FF17D130 \n"
"    B       loc_FF17D154 \n"
"    B       loc_FF17D164 \n"
"    B       loc_FF17D16C \n"
"    B       loc_FF17D174 \n"
"    B       loc_FF17D17C \n"
"    B       loc_FF17D138 \n"
"    B       loc_FF17D184 \n"
"    B       loc_FF17D144 \n"
"    B       loc_FF17D190 \n"
"    B       loc_FF17D18C \n"
"    B       loc_FF17D0FC \n"
"    B       loc_FF17D0CC \n"

"loc_FF17D0CC:\n"
"    STR     R5, [R4, #0x40] \n"
"    STR     R5, [R4, #0x30] \n"
"    STR     R5, [R4, #0x34] \n"
"    STRH    R5, [R4, #6] \n"
"    STR     R6, [R4, #0xD8] \n"
"    STR     R7, [R4, #0xF4] \n"
"    LDR     R0, [R4, #0xC] \n"
"    ADD     R0, R0, #1 \n"
"    STR     R0, [R4, #0xC] \n"
"    MOV     R0, #6 \n"
"    STR     R0, [R4, #0x44] \n"
"    B       loc_FF17D11C \n"

"loc_FF17D0FC:\n"
"    STR     R5, [R4, #0x40] \n"
"    STR     R5, [R4, #0x30] \n"
"    STR     R6, [R4, #0xD8] \n"
"    STR     R7, [R4, #0xF4] \n"
"    LDR     R0, [R4, #0xC] \n"
"    ADD     R0, R0, #1 \n"
"    STR     R0, [R4, #0xC] \n"
"    STR     R8, [R4, #0x44] \n"

"loc_FF17D11C:\n"
"    LDR     R2, =0xFF17B198 \n"
"    LDR     R1, =0xB7A5C \n"
"    LDR     R0, =0xFF17B2AC \n"
"    BL      sub_FF03BB30 \n"
"    B       loc_FF17D190 \n"

"loc_FF17D130:\n"
"      BL      unlock_optical_zoom \n"     //added
"    BL      sub_FF17C5F0 \n"
"    B       loc_FF17D190 \n"

"loc_FF17D138:\n"
"    LDR     R1, [R4, #0xF4] \n"
"    BLX     R1 \n"
//begin patch
"    LDR     R0, =video_compression_rate\n" //added
"    BL      set_quality\n"                 //added
//end patch
"    B       loc_FF17D190 \n"

"loc_FF17D144:\n"
"    LDR     R1, [R0, #0x18] \n"
"    LDR     R0, [R0, #4] \n"
"    BL      sub_FF2E2FD0 \n"
"    B       loc_FF17D190 \n"

"loc_FF17D154:\n"
"    LDR     R0, [R4, #0x44] \n"
"    CMP     R0, #5 \n"
"    STRNE   R8, [R4, #0x34] \n"
"    B       loc_FF17D190 \n"

"loc_FF17D164:\n"
"    BL      sub_FF17B914 \n"
"    B       loc_FF17D190 \n"

"loc_FF17D16C:\n"
"    BL      sub_FF17B5F8 \n"
"    B       loc_FF17D190 \n"

"loc_FF17D174:\n"
"    BL      sub_FF17B310 \n"
"    B       loc_FF17D190 \n"

"loc_FF17D17C:\n"
"    BL      sub_FF17AEC0 \n"
"    B       loc_FF17D190 \n"

"loc_FF17D184:\n"
"    BL      sub_FF17AE40 \n"
"    B       loc_FF17D190 \n"

"loc_FF17D18C:\n"
"    BL      sub_FF17D764 \n"

"loc_FF17D190:\n"
"    LDR     R1, [SP, #4] \n"
"    LDR     R3, =0xFF17AAD8 /*'MovieRecorder.c'*/ \n"
"    STR     R5, [R1] \n"
"    STR     R9, [SP] \n"
"    LDR     R0, [R4, #0x28] \n"
"    MOV     R2, R10 \n"
"    BL      sub_00477B90 /*_PostMessageQueueStrictly*/ \n"
"    B       loc_FF17D054 \n"
);
}
