#include "stubs_asm.h"

DEF(movie_status,                       0x4B29C + 0x38) // 0x4B29C + 0x38 via task_MovieRecord -> sub_FF92F3E8 -> loc_FF92F36C
DEF(recreview_hold,                     0x70B0 + 0xC4)  // from sub_FF95C814 via search on int 0x3007, similar to sd990, TODO may not be right

DEF(some_f_for_dng,                     0xDEAD)         // TODO NOT FOUND!
DEF(second_ext_for_dng,                 0xDEAD)         // TODO NOT FOUND!
