/*
 * movie_rec.c - auto-generated by CHDK code_gen.
 */
#include "conf.h"

void change_video_tables(__attribute__ ((unused))int a, __attribute__ ((unused))int b) {}

void  set_quality(int *x){ // -17 highest; +12 lowest
 if (conf.video_mode) *x=12-((conf.video_quality-1)*(12+17)/(99-1));
}

/*************************************************************/
//** movie_record_task @ 0xFF973648 - 0xFF9737D0, length=99
void __attribute__((naked,noinline)) movie_record_task() {
asm volatile (
"    STMFD   SP!, {R2-R10,LR} \n"
"    LDR     R8, =0xFF9732C4 \n"
"    LDR     R4, =0x6B18 \n"
"    LDR     R10, =0x2710 \n"
"    MVN     R7, #0 \n"
"    MOV     R5, #1 \n"
"    MOV     R6, #0 \n"
"    ADD     R9, R7, #0x670 \n"

"loc_FF973668:\n"
"    LDR     R0, [R4, #0x28] \n"
"    MOV     R2, #0 \n"
"    ADD     R1, SP, #4 \n"
"    BL      sub_003F7418 /*_ReceiveMessageQueue*/ \n"
"    LDR     R0, [R4, #0x30] \n"
"    CMP     R0, #0 \n"
"    LDRNE   R0, [R4, #0x10] \n"
"    CMPNE   R0, #2 \n"
"    LDRNE   R0, [R4, #0x44] \n"
"    CMPNE   R0, #6 \n"
"    BNE     loc_FF9737B4 \n"
"    LDR     R0, [SP, #4] \n"
"    LDR     R1, [R0] \n"
"    SUB     R1, R1, #2 \n"
"    CMP     R1, #0xD \n"
"    ADDCC   PC, PC, R1, LSL#2 \n"
"    B       loc_FF9737B4 \n"
"    B       loc_FF973730 \n"
"    B       loc_FF973754 \n"
"    B       loc_FF973764 \n"
"    B       loc_FF97376C \n"
"    B       loc_FF973738 \n"
"    B       loc_FF973774 \n"
"    B       loc_FF9737A0 \n"
"    B       loc_FF9737A8 \n"
"    B       loc_FF973744 \n"
"    B       loc_FF9737B4 \n"
"    B       loc_FF9737B0 \n"
"    B       loc_FF97370C \n"
"    B       loc_FF9736E0 \n"

"loc_FF9736E0:\n"
"    STR     R6, [R4, #0x40] \n"
"    STR     R6, [R4, #0x34] \n"
"    STR     R7, [R4, #0xC4] \n"
"    STRH    R6, [R4, #6] \n"
"    STR     R8, [R4, #0xAC] \n"
"    LDR     R0, [R4, #0x10] \n"
"    ADD     R0, R0, #1 \n"
"    STR     R0, [R4, #0x10] \n"
"    MOV     R0, #6 \n"
"    STR     R0, [R4, #0x44] \n"
"    B       loc_FF973728 \n"

"loc_FF97370C:\n"
"    STR     R6, [R4, #0x40] \n"
"    STR     R7, [R4, #0xC4] \n"
"    STR     R8, [R4, #0xAC] \n"
"    LDR     R0, [R4, #0x10] \n"
"    ADD     R0, R0, #1 \n"
"    STR     R0, [R4, #0x10] \n"
"    STR     R5, [R4, #0x44] \n"

"loc_FF973728:\n"
"    STR     R5, [R4, #8] \n"
"    B       loc_FF9737B4 \n"

"loc_FF973730:\n"
"    BL      sub_FF973014 \n"
"    B       loc_FF9737B4 \n"

"loc_FF973738:\n"
"    LDR     R1, [R4, #0xAC] \n"
"    BLX     R1 \n"
//begin patch
"    LDR     R0, =video_compression_rate \n" // added
"    BL      set_quality \n"                 // added
//end patch
"    B       loc_FF9737B4 \n"

"loc_FF973744:\n"
"    LDR     R1, [R0, #0x18] \n"
"    LDR     R0, [R0, #4] \n"
"    BL      sub_FFA92CEC \n"
"    B       loc_FF9737B4 \n"

"loc_FF973754:\n"
"    LDR     R0, [R4, #0x44] \n"
"    CMP     R0, #5 \n"
"    STRNE   R5, [R4, #0x34] \n"
"    B       loc_FF9737B4 \n"

"loc_FF973764:\n"
"    BL      sub_FF972C90 \n"
"    B       loc_FF9737B4 \n"

"loc_FF97376C:\n"
"    BL      sub_FF972B60 \n"
"    B       loc_FF9737B4 \n"

"loc_FF973774:\n"
"    LDR     R0, =0xC1C40 \n"
"    LDR     R0, [R0, #8] \n"
"    CMP     R0, #0 \n"
"    LDRNE   R2, =0xFF972AB4 \n"
"    LDRNE   R0, =0xFF972B08 \n"
"    MOVNE   R3, #0 \n"
"    MOVNE   R1, R3 \n"
"    BLNE    sub_FF864394 \n"
"    MOV     R0, #3 \n"
"    STR     R0, [R4, #0x44] \n"
"    B       loc_FF9737B4 \n"

"loc_FF9737A0:\n"
"    BL      sub_FF972A40 \n"
"    B       loc_FF9737B4 \n"

"loc_FF9737A8:\n"
"    BL      sub_FF9740BC \n"
"    B       loc_FF9737B4 \n"

"loc_FF9737B0:\n"
"    BL      sub_FF973FE4 \n"

"loc_FF9737B4:\n"
"    LDR     R1, [SP, #4] \n"
"    LDR     R3, =0xFF9727BC /*'MovieRecorder.c'*/ \n"
"    STR     R6, [R1] \n"
"    STR     R9, [SP] \n"
"    LDR     R0, [R4, #0x2C] \n"
"    MOV     R2, R10 \n"
"    BL      sub_003F7D90 /*_PostMessageQueueStrictly*/ \n"
"    B       loc_FF973668 \n"
);
}
