#include "stubs_asm.h"

DEF(playrec_mode,                   0x000038C0) //* sub_FF8998B0

DEF(file_counter_var,               0x6A90) //* loc_FF998EEC

DEF(active_palette_buffer,          0x5FEC+0x8)

DEF(palette_buffer_ptr,             0x5FEC+0x2C) //* sub_FF95E0E8

DEF(active_viewport_buffer,         0x17B2C+0x3c) //* sub_FF850B9C + loc_FF850FE0

DEF(viewport_buffers,               0xFFBF4D60)     //* 

DEF(bitmap_buffer,                  0x3DB0+0x34)    //* sub_FF8AB908
 
DEF(active_bitmap_buffer,           0x3DB0+0x2C)    //* sub_FF8AAC24

DEF(recreview_hold,                 0x8900+0x1C)    //* sub_FFA0B714
 
DEF(_nrflag,                        0x9804+0x4) //* sub_FFA43AD4 






