OBJS=boot.o stubs_min.o stubs_auto.o stubs_entry.o stubs_entry_2.o capt_seq.o lib.o
#TODO filewrite.o movie_rec.o
STUBS_AUTO_DEPS=boot.c capt_seq.c
#TODO filewrite.c movie_rec.c

include ../../../makefile_sub.inc

