#include "stubs_asm.h"

DEF(physw_status                            ,0x0000c664) // Found @0xffc11a0c
DEF(physw_run                               ,0x00001c24) // Found @0xffc11680
DEF(levent_table                            ,0xffe95518) // Found @0xffe95518
DEF(FlashParamsTable                        ,0xffebde00) // Found @0xffebde00
DEF(movie_status                            ,0x00005670) // Found @0xffcf840c
DEF(canon_menu_active                       ,0x00002b78) // Found @0xffc59d6c
DEF(canon_shoot_menu_active                 ,0x0000690d) // Found @0xffd2c9a4
DEF(playrec_mode                            ,0x000028e8) // Found @0xffc4d404
DEF(zoom_status                             ,0x00009938) // Found @0xffe0110c
DEF(some_flag_for_af_scan                   ,0x00005b24) // Found @0xffcfab30
DEF(zoom_busy                               ,0x0000559c) // Found @0xffcf4b10
DEF(focus_busy                              ,0x00005498) // Found @0xffcef9e4
DEF(recreview_hold                          ,0x000030dc) // Found @0xffc657a0