PLATFORMID=12895

PLATFORMOS=dryos

# points to the start of the memory pool used by the firmware
MEMISOSTART=0x2bd558

# start of firmware
ROMBASEADDR=0xFC000000

MAXRAMADDR = 0x0fffffff

# Found @
NEED_ENCODED_DISKBOOT=10

# Found @
KEYSYS=d4d

PLATFORMOSVER=52
