
PLATFORMID=12953

PLATFORMOS=dryos

# points to the start of the memory pool used by the firmware @0xFC02006A
MEMISOSTART=0x3a7c80

# start of firmware
ROMBASEADDR=0xFC000000

MAXRAMADDR = 0x1fffffff

# Found @
NEED_ENCODED_DISKBOOT=14

# Found @
KEYSYS=d4h

PLATFORMOSVER=55

# mandatory for DIGIC 6
MEMBASEADDR=0x8000
