#include "lolevel.h"
#include "platform.h"
#include "core.h"

static long *nrflag = (long*)0x6E10;

#include "../../../generic/capt_seq.c"

void __attribute__((naked,noinline)) sub_FF9580F0_my(  ) {
asm volatile (
      "    STMFD   SP!, {R4,R5,LR} \n" 
      "    LDR     R3, =0x748FC \n" 
      "    LDR     R5, =0x6E0C \n" 
      "    SUB     SP, SP, #4 \n" 
      "    MVN     R1, #0 \n" 
      "    STR     R0, [R5] \n" 
      "    LDR     R0, [R3] \n" 
      "    BL      sub_FF81FD78 \n" 
      "    BL      sub_FF95E3C4 \n" 
      "    BL      wait_until_remote_button_is_released\n" // +
      "    LDR     R0, [R0, #0x7C] \n" 
      //"    BL      sub_FF89FD2C \n" // - nullsub
      "    BL      sub_FF958064 \n" 
      "    BL      capt_seq_hook_set_nr\n" // +
      "    LDR     R3, =0x6E14 \n" 
      "    LDR     R0, [R3] \n" 
      "    BL      sub_FF8A0228 \n" 
      "    LDR     PC, =0xFF958128\n" // + continue in ROM
/*      "    LDR     R3, =0x6E10 \n" 
      "    LDR     R3, [R3] \n" 
      "    CMP     R3, #1 \n" 
      "    MOV     R4, #0 \n" 
      "    BNE     sub_FF95816C \n" 
      "    BL      sub_FF952194 \n" */
    );
}


void __attribute__((naked,noinline)) sub_FF954A34_my(  ) {
asm volatile (
      "    STMFD   SP!, {R4,R5,LR} \n" 
      "    LDR     R5, [R0, #0xC] \n" 
      "    BL      sub_FF95E168 \n" 
      "    CMP     R0, #0 \n" 
      "    BNE     loc_FF954A4C \n" 
      "    BL      sub_FF95E174 \n" 
"loc_FF954A4C:\n"
      "    MOV     R0, R5 \n" 
      "    BL      sub_FF956E20 \n" 
      "    MOV     R0, R5 \n" 
      "    BL      sub_FF956E60 \n" 
      "    TST     R0, #1 \n" 
      "    MOV     R2, R5 \n" 
      "    MOV     R1, #1 \n" 
      "    BEQ     loc_FF954A74 \n" 
      "    LDMFD   SP!, {R4,R5,LR} \n" 
      "    B       sub_FF952E4C \n" 
"loc_FF954A74:\n"
      "    BL      sub_FF995868 \n" 
      "    BL      sub_FF952194 \n" 
      "    MOV     R4, R0 \n" 
      "    BL      sub_FF824754 \n" 
      "    ADD     R3, R5, R5, LSL #1 \n" 
      "    ADD     R4, R4, R3, LSL #5 \n" 
      "    STR     R0, [R4, #4] \n" 
      "    MOV     R0, R5 \n" 
      "    BL      sub_FF958908 \n" 
      "    BL      sub_FF9573CC \n" 
      "    BL      sub_FF957370 \n" 
      "    MOV     R0, R5 \n" 
      "    BL      sub_FF9580F0_my \n" // ->
      "    BL      capt_seq_hook_raw_here\n" // +
      "    MOV     R2, R5 \n" 
      "    MOV     R1, #1 \n" 
      "    BL      sub_FF952E4C \n" 
      "    LDMFD   SP!, {R4,R5,LR} \n" 
      "    B       sub_FF9582F0 \n" 
    );
}

void __attribute__((naked,noinline)) capt_seq_task() //** capt_seq_task  @ 0xFF954E30
{
	asm volatile (
                 "STMFD   SP!, {R4,LR}\n"
                 "SUB     SP, SP, #4\n"
                 "MOV     R4, SP\n"
                 "B       loc_FF954F94\n"
"loc_FF954E40:\n"
                 "LDR     R2, [SP,#0xC-0xC]\n"
                 "LDR     R3, [R2]\n"
                 "MOV     R0, R2\n"
                 "CMP     R3, #0x15\n"
                 "LDRLS   PC, [PC,R3,LSL#2]\n"
                 "B       loc_FF954F6C \n" 
                 ".long   loc_FF954EB0 \n" 
                 ".long   loc_FF954EBC \n" 
                 ".long   loc_FF954EC4 \n" 
                 ".long   loc_FF954ED4 \n" 
                 ".long   loc_FF954ECC \n" 
                 ".long   loc_FF954EDC \n" 
                 ".long   loc_FF954EE4 \n" 
                 ".long   loc_FF954EF0 \n" 
                 ".long   loc_FF954EF8 \n" 
                 ".long   loc_FF954F04 \n" 
                 ".long   loc_FF954F0C \n" 
                 ".long   loc_FF954F14 \n" 
                 ".long   loc_FF954F1C \n" 
                 ".long   loc_FF954F24 \n" 
                 ".long   loc_FF954F2C \n" 
                 ".long   loc_FF954F38 \n" 
                 ".long   loc_FF954F40 \n" 
                 ".long   loc_FF954F48 \n" 
                 ".long   loc_FF954F50 \n" 
                 ".long   loc_FF954F5C \n" 
                 ".long   loc_FF954F64 \n" 
                 ".long   loc_FF954F7C \n" 
"loc_FF954EB0:\n"
                 "BL      sub_FF9566B4\n"
                 "BL      shooting_expo_param_override\n" // +
                 "BL      sub_FF952988\n"
                 "B       loc_FF954F78\n"
"loc_FF954EBC:\n"
                 "BL      sub_FF954A34_my\n"    // ->
                 "B       loc_FF954F78 \n" 
"loc_FF954EC4:\n"
                 "BL      sub_FF956E10 \n" 
                 "B       loc_FF954F78 \n" 
"loc_FF954ECC:\n"
                 "BL      sub_FF9558B8 \n" 
                 "B       loc_FF954F78 \n" 
"loc_FF954ED4:\n"
                 "BL      sub_FF955914 \n" 
                 "B       loc_FF954F78 \n" 
"loc_FF954EDC:\n"
                 "BL      sub_FF955B78 \n" 
                 "B       loc_FF954F78 \n" 
"loc_FF954EE4:\n"
                 "BL      sub_FF9567A8 \n" 
                 "BL      sub_FF952988 \n" 
                 "B       loc_FF954F78 \n" 
"loc_FF954EF0:\n"
                 "BL      sub_FF954B24 \n" 
                 "B       loc_FF954F78 \n" 
"loc_FF954EF8:\n"
                 "BL      sub_FF956810 \n" 
                 "BL      sub_FF952988 \n" 
                 "B       loc_FF954F78 \n" 
"loc_FF954F04:\n"
                 "BL      sub_FF955914 \n" 
                 "B       loc_FF954F78 \n" 
"loc_FF954F0C:\n"
                 "BL      sub_FF957508 \n" 
                 "B       loc_FF954F78 \n" 
"loc_FF954F14:\n"
                 "BL      sub_FF957830 \n" 
                 "B       loc_FF954F78 \n" 
"loc_FF954F1C:\n"
                 "BL      sub_FF9578BC \n" 
                 "B       loc_FF954F78 \n" 
"loc_FF954F24:\n"
                 "BL      sub_FF957974 \n" 
                 "B       loc_FF954F78 \n" 
"loc_FF954F2C:\n"
                 "MOV     R0, #0 \n" 
                 "BL      sub_FF957A24 \n" 
                 "B       loc_FF954F78 \n" 
"loc_FF954F38:\n"
                 "BL      sub_FF957B74 \n" 
                 "B       loc_FF954F78 \n" 
"loc_FF954F40:\n"
                 "BL      sub_FF957BE8 \n" 
                 "B       loc_FF954F78 \n" 
"loc_FF954F48:\n"
                 "BL      sub_FF957CA0 \n" 
                 "B       loc_FF954F78 \n" 
"loc_FF954F50:\n"
                 "MOV     R0, #1 \n" 
                 "BL      sub_FF957A24 \n" 
                 "B       loc_FF954F78 \n" 
"loc_FF954F5C:\n"
                 "BL      sub_FF957D70 \n" 
                 "B       loc_FF954F78 \n" 
"loc_FF954F64:\n"
                 "BL      sub_FF957D9C \n" 
                 "B       loc_FF954F78 \n" 
"loc_FF954F6C:\n"
                 "LDR     R0, =0xFF9547B8 \n" 
                 "MOV     R1, #0x2DC \n" 
                 "BL      sub_FF813A80 \n" 
"loc_FF954F78:\n"
                 "LDR     R2, [SP] \n" 
"loc_FF954F7C:\n"
                 "LDR     R3, =0x74884 \n" 
                 "LDR     R1, [R2, #4] \n" 
                 "LDR     R0, [R3] \n" 
                 "BL      sub_FF81FBDC \n" 
                 "LDR     R0, [SP] \n" 
                 "BL      sub_FF954834 \n" 
"loc_FF954F94:\n"
                 "LDR     R3, =0x74888 \n" 
                 "MOV     R1, R4 \n" 
                 "LDR     R0, [R3] \n" 
                 "MOV     R2, #0 \n" 
                 "BL      sub_FF82038C \n" 
                 "TST     R0, #1 \n" 
                 "BEQ     loc_FF954E40 \n" 
                 "MOV     R1, #0x24C \n" 
                 "LDR     R0, =0xFF9547B8 \n" 
                 "ADD     R1, R1, #1 \n" 
                 "BL      sub_FF813A80 \n" 
                 "BL      sub_FF821928 \n" 
                 "ADD     SP, SP, #4 \n" 
                 "LDMFD   SP!, {R4,PC} \n" 
    );
}


void __attribute__((naked,noinline)) exp_drv_task() { // sub_FF8FB1F8 
asm volatile (
                 "STMFD   SP!, {R4-R8,LR} \n" 
                 "SUB     SP, SP, #0x14 \n" 
                 "MOV     R7, SP \n" 
                 "B       loc_FF8FB4EC \n" 
"loc_FF8FB208:\n"
                 "CMP     R2, #0x19 \n" 
                 "BNE     loc_FF8FB220 \n" 
                 "LDR     R0, [R12, #0x34] \n" 
                 "MOV     LR, PC \n" 
                 "LDR     PC, [R12, #0x30] \n" 
                 "B       loc_FF8FB258 \n" 
"loc_FF8FB220:\n"
                 "SUB     R3, R2, #0x16 \n" 
                 "CMP     R3, #1 \n" 
                 "BHI     loc_FF8FB238 \n" 
                 "MOV     R0, R12 \n" 
                 "BL      sub_FF8FB1A0 \n" 
                 "B       loc_FF8FB248 \n" 
"loc_FF8FB238:\n"
                 "CMP     R2, #0x18 \n" 
                 "BNE     loc_FF8FB264 \n" 
                 "BL      sub_FF8AE1BC \n" 
                 "BL      sub_FF8B0034 \n" 
"loc_FF8FB248:\n"
                 "LDR     R3, [SP] \n" 
                 "LDR     R0, [R3, #0x34] \n" 
                 "MOV     LR, PC \n" 
                 "LDR     PC, [R3, #0x30] \n" 
"loc_FF8FB258:\n"
                 "LDR     R0, [SP] \n" 
                 "BL      sub_FF8F9390 \n" 
                 "B       loc_FF8FB4EC \n" 
"loc_FF8FB264:\n"
                 "CMP     R2, #0xC \n" 
                 "MOV     R8, #1 \n" 
                 "BNE     loc_FF8FB2D4 \n" 
                 "LDR     R1, [R12, #0x24] \n" 
                 "ADD     R1, R1, R1, LSL #1 \n" 
                 "ADD     R1, R12, R1, LSL #1 \n" 
                 "ADD     R6, SP, #0xC \n" 
                 "SUB     R1, R1, #2 \n" 
                 "MOV     R2, #6 \n" 
                 "MOV     R0, R6 \n" 
                 "BL      sub_FFAFC778 \n" 
                 "LDR     R0, [SP] \n" 
                 "BL      sub_FF8FA66C \n" 
                 "LDR     R3, [SP] \n" 
                 "LDR     R1, [R3, #0x24] \n" 
                 "LDR     R2, [R3, #0x34] \n" 
                 "ADD     R0, R3, #4 \n" 
                 "MOV     LR, PC \n" 
                 "LDR     PC, [R3, #0x30] \n" 
                 "LDR     R0, [SP] \n" 
                 "BL      sub_FF8FA7F0 \n" 
                 "LDR     R3, [SP] \n" 
                 "ADD     R0, R3, #4 \n" 
                 "LDR     R1, [R3, #0x24] \n" 
                 "LDR     R2, [R3, #0x3C] \n" 
                 "MOV     LR, PC \n" 
                 "LDR     PC, [R3, #0x38] \n" 
                 "B       loc_FF8FB49C \n" 
"loc_FF8FB2D4:\n"
                 "SUB     R3, R2, #0xD \n" 
                 "CMP     R3, #1 \n" 
                 "BHI     loc_FF8FB354 \n" 
                 "ADD     R6, SP, #0xC \n" 
                 "ADD     R5, SP, #4 \n" 
                 "MOV     R0, R12 \n" 
                 "MOV     R1, R6 \n" 
                 "MOV     R2, R5 \n" 
                 "BL      sub_FF8FA86C \n" 
                 "MOV     R4, R0 \n" 
                 "CMP     R4, #3 \n" 
                 "CMPNE   R4, #1 \n" 
                 "BNE     loc_FF8FB334 \n" 
                 "LDR     R12, [SP] \n" 
                 "MOV     R0, R5 \n" 
                 "LDR     R1, [R12, #0x24] \n" 
                 "MOV     R2, R4 \n" 
                 "LDR     R3, [R12, #0x34] \n" 
                 "MOV     LR, PC \n" 
                 "LDR     PC, [R12, #0x30] \n" 
                 "MOV     R1, R4 \n" 
                 "LDR     R0, [SP] \n" 
                 "BL      sub_FF8FB180 \n" 
                 "B       loc_FF8FB49C \n" 
"loc_FF8FB334:\n"
                 "LDR     R12, [SP] \n" 
                 "MOV     R2, R4 \n" 
                 "ADD     R0, R12, #4 \n" 
                 "LDR     R1, [R12, #0x24] \n" 
                 "LDR     R3, [R12, #0x34] \n" 
                 "MOV     LR, PC \n" 
                 "LDR     PC, [R12, #0x30] \n" 
                 "B       loc_FF8FB49C \n" 
"loc_FF8FB354:\n"
                 "CMP     R2, #0x14 \n" 
                 "BNE     loc_FF8FB3A8 \n" 
                 "LDR     R1, [R12, #0x24] \n" 
                 "ADD     R1, R1, R1, LSL #1 \n" 
                 "ADD     R1, R12, R1, LSL #1 \n" 
                 "ADD     R6, SP, #0xC \n" 
                 "SUB     R1, R1, #2 \n" 
                 "MOV     R2, #6 \n" 
                 "MOV     R0, R6 \n" 
                 "BL      sub_FFAFC778 \n" 
                 "LDR     R0, [SP] \n" 
                 "BL      sub_FF8FA140 \n" 
                 "LDR     R3, [SP] \n" 
                 "ADD     R0, R3, #4 \n" 
                 "LDR     R1, [R3, #0x24] \n" 
                 "LDR     R2, [R3, #0x34] \n" 
                 "MOV     LR, PC \n" 
                 "LDR     PC, [R3, #0x30] \n" 
                 "LDR     R0, [SP] \n" 
                 "BL      sub_FF8FA39C \n" 
                 "B       loc_FF8FB49C \n" 
"loc_FF8FB3A8:\n"
                 "ADD     R6, SP, #0xC \n" 
                 "ADD     R1, R12, #4 \n" 
                 "MOV     R0, R6 \n" 
                 "MOV     R2, #6 \n" 
                 "BL      sub_FFAFC778 \n" 
                 "LDR     R12, [SP] \n" 
                 "LDR     R3, [R12] \n" 
                 "MOV     R0, R12 \n" 
                 "CMP     R3, #0x15 \n" 
                 "LDRLS   PC, [PC, R3, LSL #2] \n" 
                 "B       loc_FF8FB488 \n" 
                 ".long   loc_FF8FB42C \n" 
                 ".long   loc_FF8FB434 \n" 
                 ".long   loc_FF8FB43C \n" 
                 ".long   loc_FF8FB43C \n" 
                 ".long   loc_FF8FB42C \n" 
                 ".long   loc_FF8FB434 \n" 
                 ".long   loc_FF8FB43C \n" 
                 ".long   loc_FF8FB43C \n" 
                 ".long   loc_FF8FB454 \n" 
                 ".long   loc_FF8FB454 \n" 
                 ".long   loc_FF8FB478 \n" 
                 ".long   loc_FF8FB480 \n" 
                 ".long   loc_FF8FB488 \n" 
                 ".long   loc_FF8FB488 \n" 
                 ".long   loc_FF8FB488 \n" 
                 ".long   loc_FF8FB444 \n" 
                 ".long   loc_FF8FB44C \n" 
                 ".long   loc_FF8FB460 \n" 
                 ".long   loc_FF8FB468 \n" 
                 ".long   loc_FF8FB468 \n" 
                 ".long   loc_FF8FB488 \n" 
                 ".long   loc_FF8FB470 \n" 
"loc_FF8FB42C:\n"
                 "BL      sub_FF8F986C \n" 
                 "B       loc_FF8FB484 \n" 
"loc_FF8FB434:\n" 
                 "BL      sub_FF8F99A8 \n" 
                 "B       loc_FF8FB484 \n" 
"loc_FF8FB43C:\n" 
                 "BL      sub_FF8F9AD8 \n" 
                 "B       loc_FF8FB484 \n" 
"loc_FF8FB444:\n" 
                 "BL      sub_FF8F9CAC \n" 
                 "B       loc_FF8FB484 \n" 
"loc_FF8FB44C:\n" 
                 "BL      sub_FF8F9DB4 \n" 
                 "B       loc_FF8FB484 \n" 
"loc_FF8FB454:\n" 
                 "BL      sub_FF8F9E78_my \n" // ->
                 "MOV     R8, #0 \n" 
                 "B       loc_FF8FB484 \n" 
"loc_FF8FB460:\n"
                 "BL      sub_FF8F9F3C \n" 
                 "B       loc_FF8FB484 \n" 
"loc_FF8FB468:\n"
                 "BL      sub_FF8FA024 \n" 
                 "B       loc_FF8FB484 \n" 
"loc_FF8FB470:\n"
                 "BL      sub_FF8FA42C \n" 
                 "B       loc_FF8FB484 \n" 
"loc_FF8FB478:\n"
                 "BL      sub_FF8FA500 \n" 
                 "B       loc_FF8FB484 \n" 
"loc_FF8FB480:\n"
                 "BL      sub_FF8FA5EC \n" 
"loc_FF8FB484:\n"
                 "LDR     R12, [SP] \n" 
"loc_FF8FB488:\n"
                 "ADD     R0, R12, #4 \n" 
                 "LDR     R1, [R12, #0x24] \n" 
                 "LDR     R2, [R12, #0x34] \n" 
                 "MOV     LR, PC \n" 
                 "LDR     PC, [R12, #0x30] \n" 
"loc_FF8FB49C:\n"
                 "CMP     R8, #1 \n" 
                 "BNE     loc_FF8FB4C4 \n" 
                 "LDR     R1, [SP] \n" 
                 "LDR     R3, [R1, #0x24] \n" 
                 "ADD     R3, R3, R3, LSL #1 \n" 
                 "ADD     R1, R1, R3, LSL #1 \n" 
                 "MOV     R0, R6 \n" 
                 "SUB     R1, R1, #2 \n" 
                 "BL      sub_FF8F9724 \n" 
                 "B       loc_FF8FB4E4 \n" 
"loc_FF8FB4C4:\n"
                 "MOV     R0, #1 \n" 
                 "MOV     R1, R0 \n" 
                 "MOV     R2, R0 \n" 
                 "BL      sub_FF8F96C8 \n" 
                 "MOV     R0, #1 \n" 
                 "MOV     R1, R0 \n" 
                 "MOV     R2, R0 \n" 
                 "BL      sub_FF8F97E4 \n" 
"loc_FF8FB4E4:\n"
                 "LDR     R0, [SP] \n" 
                 "BL      sub_FF8F9390 \n" 
"loc_FF8FB4EC:\n"
                 "LDR     R3, =0x50390 \n" 
                 "MOV     R2, #0 \n" 
                 "LDR     R0, [R3] \n" 
                 "MOV     R1, R7 \n" 
                 "BL      sub_FF82038C \n" 
                 "LDR     R12, [SP] \n" 
                 "LDR     R2, [R12] \n" 
                 "CMP     R2, #0x1A \n" 
                 "BNE     loc_FF8FB208 \n" 
                 "MOV     R0, R12 \n" 
                 "BL      sub_FF8F9390 \n" 
                 "LDR     R3, =0x5038C \n" 
                 "MOV     R1, #1 \n" 
                 "LDR     R0, [R3] \n" 
                 "BL      sub_FF81FBDC \n" 
                 "BL      sub_FF821928 \n" 
                 "ADD     SP, SP, #0x14 \n" 
                 "LDMFD   SP!, {R4-R8,PC} \n" 
    );
}

void __attribute__((naked,noinline)) sub_FF8F9E78_my(  ) {
asm volatile (
                 "STMFD   SP!, {R4,R5,LR} \n" 
                 "LDR     R3, =0x5038C \n" 
                 "MOV     R4, R0 \n" 
                 "MOV     R1, #0xE \n" 
                 "LDR     R0, [R3] \n" 
                 "BL      sub_FF81FD78 \n" 
                 "MOV     R1, #0 \n" 
                 "LDRSH   R0, [R4, #4] \n" 
                 "BL      sub_FF8F9430 \n" 
                 "MOV     R5, R0 \n" 
                 "LDRSH   R0, [R4, #6] \n" 
                 "BL      sub_FF8F9560 \n" 
                 "LDRSH   R0, [R4, #8] \n" 
                 "BL      sub_FF8F95FC \n" 
                 "LDR     R3, [R4] \n" 
                 "CMP     R3, #9 \n" 
                 "MOVEQ   R5, #0 \n" 
                 "CMP     R5, #1 \n" 
                 "LDR     R1, =0xFF8F93C0 \n" 
                 "MOV     R2, #2 \n" 
                 "BNE     loc_FF8F9EE4 \n" 
                 "LDRSH   R0, [R4, #4] \n" 
                 "BL      sub_FFAA11A0 \n" 
                 "LDR     R2, =0x503B8 \n" 
                 "MOV     R3, #0 \n" 
                 "STR     R3, [R2] \n" 
                 "B       loc_FF8F9EE8 \n" 
"loc_FF8F9EE4:\n"
                 "BL      sub_FF8F9698 \n" 
"loc_FF8F9EE8:\n"
                 "STRH    R0, [R4, #4] \n" 
                 "LDRSH   R0, [R4, #6] \n" 
                 "BL      sub_FF8ADE54_my \n" // ->
                 "BL      sub_FF8AFDD8 \n" 
                 "LDRSH   R0, [R4, #8] \n" 
                 "MOV     R1, #1 \n" 
                 "BL      sub_FF8AFBF4 \n" 
                 "MOV     R1, #0 \n" 
                 "ADD     R0, R4, #8 \n" 
                 "BL      sub_FF8AFCB8 \n" 
                 "CMP     R5, #1 \n" 
                 "MOV     R1, #2 \n" 
                 "MOV     R2, #0 \n" 
                 "LDMNEFD SP!, {R4,R5,PC} \n" 
                 "LDR     R3, =0x5038C \n" 
                 "LDR     R0, [R3] \n" 
                 "LDMFD   SP!, {R4,R5,LR} \n" 
                 "B       sub_FF81FBCC \n" 
    );
}

void __attribute__((naked,noinline)) sub_FF8ADE54_my(  ) {
asm volatile (
                 "STMFD   SP!, {R4,LR} \n" 
                 "LDR     R3, =0x541C \n" 
                 "LDR     R2, [R3] \n" 
                 "MOV     R3, R0, LSL #0x10 \n" 
                 "CMP     R2, #1 \n" 
                 "MOV     R1, #0x110 \n" 
                 "LDR     R0, =0xFF8AD7F0 \n" 
                 "MOV     R4, R3, ASR #0x10 \n" 
                 "BEQ     loc_FF8ADE7C \n" 
                 "BL      sub_FF813A80 \n" 
"loc_FF8ADE7C:\n"
                 "MOV     R1, #0x114 \n" 
                 "CMN     R4, #0xC00 \n" 
                 "LDR     R3, =0x367BE \n" 
                 "LDR     R0, =0xFF8AD7F0 \n" 
                 "ADD     R1, R1, #2 \n" 
                 "LDREQSH R4, [R3] \n" 
                 "LDRNE   R3, =0x367BE \n" 
                 "CMN     R4, #0xC00 \n" 
                 "STRH    R4, [R3] \n" 
                 "BNE     loc_FF8ADEA8 \n" 
                 "BL      sub_FF813A80 \n" 
"loc_FF8ADEA8:\n"
                 "MOV     R0, R4 \n" 
//                 "BL      sub_FF8AEF8C \n" // -
                 "BL      apex2us\n"         // +
                 "BL      sub_FF8AD3A8 \n" 
                 "TST     R0, #1 \n" 
                 "MOV     R1, #0x118 \n" 
                 "LDR     R0, =0xFF8AD7F0 \n" 
                 "LDMEQFD SP!, {R4,PC} \n" 
                 "LDMFD   SP!, {R4,LR} \n" 
                 "B       sub_FF813A80 \n"
    );
}
