/*
 * filewrite.c - auto-generated by CHDK code_gen.
 */
#include "lolevel.h"
#include "platform.h"



typedef struct {
    unsigned int address;
    unsigned int length;
} cam_ptp_data_chunk; //camera specific structure

#define MAX_CHUNKS_FOR_FWT 7 // filewritetask is prepared for this many chunks


/*
 * fwt_data_struct: defined here as it's camera dependent
 * unneeded members are designated with unkn
 * file_offset, full_size, seek_flag only needs to be defined for cameras with CAM_FILEWRITETASK_SEEK/CAM_FILEWRITETASK_MULTIPASS
 * pdc is always required
 * name is not currently used
 */
typedef struct
{
    int unkn1; // message number
    int file_offset;
    int maybe_full_size; // maybe, on g7x wasn't always full size
    int unkn2, unkn3;
    int unkn4;
    cam_ptp_data_chunk pdc[MAX_CHUNKS_FOR_FWT];
    int maybe_seek_flag;      // 0x2083 jpeg, 0x100 create dir, 0x200 CacheFlush
    int unkn5, unkn6;
    char name[32];      // offset from start 0x5c, from Open case
} fwt_data_struct;
/*
observed message sequences
JPEG
12 maybe_full_size = 0x004437ac (=actual size), seek_flag = 0x2083
 0 chunk 0-0x004437ac
 1 chunk 0-0
 7 close

new directory
11 seek_flag = 0x100
before m 12 for shot, after raw hook in capt_seq

after shot
10 A/ seek_flag 0x200
*/

#include "../../../generic/filewrite.c"



/*************************************************************/
//** filewritetask @ 0xFF32FF78 - 0xFF3300B8, length=81
void __attribute__((naked,noinline)) filewritetask() {
asm volatile (
"    STMFD   SP!, {R1-R5,LR} \n"
"    LDR     R5, =0xC1C0 \n"

"loc_FF32FF80:\n"
"    MOV     R2, #0 \n"
"    LDR     R0, [R5, #0x14] \n"
"    ADD     R1, SP, #8 \n"
"    BL      sub_006B8568 /*_ReceiveMessageQueue*/ \n"
"    CMP     R0, #0 \n"
"    LDRNE   R2, =0x476 \n"
"    LDRNE   R1, =0xFF3300EC /*'dwFWrite.c'*/ \n"
"    MOVNE   R0, #0 \n"
"    BLNE    _DebugAssert \n"
"    LDR     R0, [SP, #8] \n"
"    LDR     R1, [R0] \n"
"    CMP     R1, #0xD \n"
"    ADDCC   PC, PC, R1, LSL#2 \n"
"    B       loc_FF32FF80 \n"
"    B       loc_FF3300AC \n"
"    B       loc_FF3300AC \n"
"    B       loc_FF3300AC \n"
"    B       loc_FF3300AC \n"
"    B       loc_FF3300AC \n"
"    B       loc_FF3300AC \n"
"    B       loc_FF3300AC \n"
"    B       loc_FF3300B4 \n"
"    B       loc_FF32FFEC \n"
"    B       loc_FF330074 \n"
"    B       loc_FF3300A4 \n"
"    B       loc_FF330064 \n"
"    B       loc_FF33006C \n"

"loc_FF32FFEC:\n"
"    MOV     R0, #0 \n"
"    STR     R0, [SP] \n"

"loc_FF32FFF4:\n"
"    LDR     R0, [R5, #0x14] \n"
"    MOV     R1, SP \n"
"    BL      sub_006B87F0 /*_GetNumberOfPostedMessages*/ \n"
"    LDR     R0, [SP] \n"
"    CMP     R0, #0 \n"
"    BEQ     loc_FF330020 \n"
"    LDR     R0, [R5, #0x14] \n"
"    MOV     R2, #0 \n"
"    ADD     R1, SP, #4 \n"
"    BL      sub_006B8568 /*_ReceiveMessageQueue*/ \n"
"    B       loc_FF32FFF4 \n"

"loc_FF330020:\n"
"    LDR     R0, [R5, #8] \n"
"    MOV     R4, R5 \n"
"    CMN     R0, #1 \n"
"    BEQ     loc_FF330058 \n"
"    BL      _Close \n"
"    MVN     R0, #0 \n"
"    STR     R0, [R4, #8] \n"
"    MOV     R1, #0 \n"
"    MOV     R0, #0x48 \n"
"    BL      sub_FF0BDDB8 \n"
"    LDR     R0, =0x138318 \n"
"    BL      sub_FF030FF4 \n"
"    MOV     R1, #0 \n"
"    BL      sub_FF02EEB8 \n"

"loc_FF330058:\n"
"    LDR     R0, [R4, #0x10] \n"
"    BL      _GiveSemaphore \n"
"    B       loc_FF32FF80 \n"

"loc_FF330064:\n"
"    BL      sub_FF33030C \n"
"    B       loc_FF32FF80 \n"

"loc_FF33006C:\n"
"    BL      sub_FF32FBA0_my \n"  // --> Patched. Old value = 0xFF32FBA0. msg 12 - open, main hook
"    B       loc_FF32FF80 \n"

"loc_FF330074:\n"
"    LDR     R1, [R0, #4] \n"
"    MOV     R4, R0 \n"
"    LDR     R0, [R5, #8] \n"
"    MOV     R2, #0 \n"
"    BL      _lseek \n"
"    CMN     R0, #1 \n"
"    LDREQ   R0, =0x9200013 \n"
"    MOVEQ   R1, R4 \n"
"    STREQ   R0, [R4, #0x14] \n"
"    MOVEQ   R0, #7 \n"
"    BLEQ    sub_FF32FAD8 \n"
"    B       loc_FF32FF80 \n"

"loc_FF3300A4:\n"
"    BL      sub_FF3303AC \n"
"    B       loc_FF32FF80 \n"

"loc_FF3300AC:\n"
"    BL      sub_FF330448_my \n"  // --> Patched. Old value = 0xFF330448. msg 0-6 - write chunk
"    B       loc_FF32FF80 \n"

"loc_FF3300B4:\n"
"    BL      sub_FF32FD78_my \n"  // --> Patched. Old value = 0xFF32FD78. msg 0-7 - close
"    B       loc_FF32FF80 \n"
);
}

/*************************************************************/
//** sub_FF32FBA0_my @ 0xFF32FBA0 - 0xFF32FD74, length=118
void __attribute__((naked,noinline)) sub_FF32FBA0_my() {
asm volatile (
"    STMFD   SP!, {R4-R9,LR} \n"
"    MOV     R4, R0 \n"
//hook placed here to avoid conditional branch a few instructions below (watch out for registers!)
//"  MOV   R0, R4\n"      //data block start, commented out as R0 is already holding what we need
"    BL filewrite_main_hook\n"
"    MOV     R0, R4\n"      //restore register(s)
"    LDR     R0, [R0, #0x50] \n"
"    LDR     R7, =0xC1C0 \n"
"    TST     R0, #5 \n"
"    SUB     SP, SP, #0x3C \n"
"    BEQ     loc_FF32FBE4 \n"
"    LDR     R0, [R7, #0x1C] \n"
"    CMP     R0, #0 \n"
"    BLXNE   R0 \n"
"    ADD     R0, R4, #0x5C \n"
"    BL      sub_FF030FF4 \n"
"    MOV     R1, #0 \n"
"    BL      sub_FF02ED78 \n"
"    MOV     R1, #0 \n"
"    MOV     R0, #0x47 \n"
"    BL      sub_FF0BDDB8 \n"

"loc_FF32FBE4:\n"
"    LDR     R0, [R4, #0x50] \n"
"    TST     R0, #1 \n"
"    BEQ     loc_FF32FD48 \n"
"    LDR     R0, [R4, #0x10] \n"
"    BL      sub_FF02DDF8 \n"
"    LDR     R0, [R4, #0x50] \n"
"    LDR     R5, =0x301 \n"
"    TST     R0, #0x10 \n"
"    MOVNE   R5, #9 \n"
"    BNE     loc_FF32FC14 \n"
"    TST     R0, #0x40 \n"
"    MOVNE   R5, #1 \n"

"loc_FF32FC14:\n"
"    TST     R0, #0x20 \n"
"    BNE     loc_FF32FC28 \n"
"    LDR     R0, [R4, #0x58] \n"
"    CMP     R0, #1 \n"
"    BNE     loc_FF32FC2C \n"

"loc_FF32FC28:\n"
"    ORR     R5, R5, #0x8000 \n"

"loc_FF32FC2C:\n"
"    LDR     R9, =0x1B6 \n"
"    ADD     R8, R4, #0x5C \n"
"    LDR     R6, [R4, #0x10] \n"
"    MOV     R2, R9 \n"
"    MOV     R1, R5 \n"
"    MOV     R0, R8 \n"
"    BL      fwt_open \n"  // --> Patched. Old value = _Open.
"    CMN     R0, #1 \n"
"    BNE     loc_FF32FCAC \n"
"    MOV     R0, R8 \n"
"    BL      sub_FF02799C \n"
"    MOV     R2, #0xF \n"
"    MOV     R1, R8 \n"
"    ADD     R0, SP, #4 \n"
"    BL      sub_006DBE10 \n"
"    MOV     R0, #0 \n"
"    LDR     R1, =0x41FF \n"
"    STRB    R0, [SP, #0x13] \n"
"    STR     R1, [SP, #0x24] \n"
"    MOV     R1, #0x10 \n"
"    STR     R0, [SP, #0x2C] \n"
"    STR     R1, [SP, #0x28] \n"
"    ADD     R1, SP, #0x24 \n"
"    ADD     R0, SP, #4 \n"
"    STR     R6, [SP, #0x30] \n"
"    STR     R6, [SP, #0x34] \n"
"    STR     R6, [SP, #0x38] \n"
"    BL      sub_FF02E6DC \n"
"    MOV     R2, R9 \n"
"    MOV     R1, R5 \n"
"    MOV     R0, R8 \n"
"    BL      _Open \n"

"loc_FF32FCAC:\n"
"    CMN     R0, #1 \n"
"    MOV     R5, R0 \n"
"    STR     R0, [R7, #8] \n"
"    BNE     loc_FF32FD08 \n"
"    MOV     R1, #0 \n"
"    MOV     R0, #0x48 \n"
"    BL      sub_FF0BDDB8 \n"
"    ADD     R0, R4, #0x5C \n"
"    BL      sub_FF030FF4 \n"
"    LDR     R1, [R7, #0x20] \n"
"    BL      sub_FF02EEB8 \n"
"    LDR     R0, [R7, #0x18] \n"
"    CMP     R0, #0 \n"
"    BEQ     loc_FF32FD70 \n"
"    LDR     R5, =0x9200001 \n"
"    MOV     R0, R4 \n"
"    MOV     R1, R5 \n"
"    BL      sub_FF32FA74 \n"
"    LDR     R1, [R7, #0x18] \n"
"    MOV     R0, R5 \n"
"    ADD     SP, SP, #0x3C \n"
"    LDMFD   SP!, {R4-R9,LR} \n"
"    BX      R1 \n"

"loc_FF32FD08:\n"
"    LDR     R0, =0x138318 \n"
"    MOV     R2, #0x20 \n"
"    ADD     R1, R4, #0x5C \n"
"    BL      sub_006DBFF8 /*_dry_memcpy*/ \n"
"    LDR R3, =current_write_ignored\n"
"    LDR R3, [R3]\n"
"    CMP R3, #0\n"
"    BNE loc_C\n" // jump over the next block
"    LDR     R0, [R4, #0x50] \n"
"    TST     R0, #0x80 \n"
"    BEQ     loc_FF32FD48 \n"
"    LDR     R1, [R4, #0xC] \n"
"    MOV     R0, R5 \n"
"    BL      sub_FF02766C \n"
"    CMP     R0, #0 \n"
"    LDREQ   R0, =0x9200017 \n"
"    MOVEQ   R1, R4 \n"
"    STREQ   R0, [R4, #0x14] \n"
"    MOVEQ   R0, #7 \n"
"    BEQ     loc_FF32FD6C \n"

"loc_FF32FD48:\n"
"loc_C:\n"
"    LDR     R0, [R4, #0x50] \n"
"    TST     R0, #0x40 \n"
"    LDREQ   R0, [R4, #4] \n"
"    CMPEQ   R0, #0 \n"
"    MOVNE   R1, R4 \n"
"    MOVNE   R0, #9 \n"
"    BLNE    sub_FF32FAD8 \n"
"    MOV     R1, R4 \n"
"    MOV     R0, #0 \n"

"loc_FF32FD6C:\n"
"    BL      sub_FF32FAD8 \n"

"loc_FF32FD70:\n"
"    ADD     SP, SP, #0x3C \n"
"    LDMFD   SP!, {R4-R9,PC} \n"
);
}

/*************************************************************/
//** sub_FF330448_my @ 0xFF330448 - 0xFF33052C, length=58
void __attribute__((naked,noinline)) sub_FF330448_my() {
asm volatile (
"    STMFD   SP!, {R4-R10,LR} \n"
"    MOV     R5, R0 \n"
"    LDR     R0, [R0] \n"
"    CMP     R0, #6 \n"
"    BHI     loc_FF330474 \n"
"    ADD     R0, R5, R0, LSL#3 \n"
"    LDR     R8, [R0, #0x18]! \n"
"    LDR     R7, [R0, #4] \n"
"    CMP     R7, #0 \n"
"    BNE     loc_FF330490 \n"
"    B       loc_FF330484 \n"

"loc_FF330474:\n"
"    LDR     R2, =0x3B5 \n"
"    LDR     R1, =0xFF3300EC /*'dwFWrite.c'*/ \n"
"    MOV     R0, #0 \n"
"    BL      _DebugAssert \n"

"loc_FF330484:\n"
"    MOV     R1, R5 \n"
"    MOV     R0, #7 \n"
"    B       loc_FF330528 \n"

"loc_FF330490:\n"
"    LDR     R9, =0xC1C0 \n"
"    MOV     R4, R7 \n"

"loc_FF330498:\n"
"    LDR     R0, [R5, #4] \n"
"    CMP     R4, #0x1000000 \n"
"    MOVLS   R6, R4 \n"
"    MOVHI   R6, #0x1000000 \n"
"    BIC     R1, R0, #0xFF000000 \n"
"    CMP     R1, #0 \n"
"    BICNE   R0, R0, #0xFF000000 \n"
"    RSBNE   R0, R0, #0x1000000 \n"
"    CMPNE   R6, R0 \n"
"    MOVHI   R6, R0 \n"
"    LDR     R0, [R9, #8] \n"
"    MOV     R2, R6 \n"
"    MOV     R1, R8 \n"
"    BL      fwt_write \n"  // --> Patched. Old value = _Write.
"    LDR     R1, [R5, #4] \n"
"    CMP     R6, R0 \n"
"    ADD     R1, R1, R0 \n"
"    STR     R1, [R5, #4] \n"
"    BEQ     loc_FF3304F8 \n"
"    CMN     R0, #1 \n"
"    LDRNE   R0, =0x9200015 \n"
"    LDREQ   R0, =0x9200005 \n"
"    STR     R0, [R5, #0x14] \n"
"    B       loc_FF330484 \n"

"loc_FF3304F8:\n"
"    SUB     R4, R4, R0 \n"
"    CMP     R4, R7 \n"
"    LDRCS   R2, =0x3DF \n"
"    LDRCS   R1, =0xFF3300EC /*'dwFWrite.c'*/ \n"
"    ADD     R8, R8, R0 \n"
"    MOVCS   R0, #0 \n"
"    BLCS    _DebugAssert \n"
"    CMP     R4, #0 \n"
"    BNE     loc_FF330498 \n"
"    LDR     R0, [R5] \n"
"    MOV     R1, R5 \n"
"    ADD     R0, R0, #1 \n"

"loc_FF330528:\n"
"    LDMFD   SP!, {R4-R10,LR} \n"
"    B       sub_FF32FAD8 \n"
);
}

/*************************************************************/
//** sub_FF32FD78_my @ 0xFF32FD78 - 0xFF32FE0C, length=38
void __attribute__((naked,noinline)) sub_FF32FD78_my() {
asm volatile (
"    STMFD   SP!, {R4-R6,LR} \n"
"    MOV     R4, R0 \n"
"    LDR     R0, [R0, #0x50] \n"
"    LDR     R5, =0xC1C0 \n"
"    TST     R0, #0xA \n"
"    SUB     SP, SP, #0x38 \n"
"    BEQ     sub_FF32FF44 \n"
"    TST     R0, #2 \n"
"    BEQ     sub_FF32FE20 \n"
"    TST     R0, #0x80 \n"
"    LDRNE   R0, [R4, #0xC] \n"
"    LDRNE   R1, [R4, #8] \n"
"    CMPNE   R1, R0 \n"
"    BEQ     loc_FF32FDE8 \n"
"    LDR     R0, [R5, #8] \n"
"    BL      sub_FF02766C \n"
"    CMP     R0, #0 \n"
"    LDREQ   R0, =0x9200017 \n"
"    STREQ   R0, [R4, #0x14] \n"
"    BEQ     loc_FF32FDE8 \n"
"    LDR     R0, [R4, #8] \n"
"    ADD     R1, SP, #0x20 \n"
"    STR     R0, [R4, #4] \n"
"    ADD     R0, R4, #0x5C \n"
"    BL      sub_FF02E624 \n"
"    CMP     R0, #1 \n"
"    LDREQ   R0, [R4, #4] \n"
"    STREQ   R0, [SP, #0x28] \n"

"loc_FF32FDE8:\n"
"    LDR     R0, [R5, #8] \n"
"    CMN     R0, #1 \n"
"    BEQ     sub_FF32FE20 \n"
"    LDR     R1, [R4, #0x58] \n"
"    LDR     R6, =0x9200003 \n"
"    CMP     R1, #1 \n"
"    BNE     loc_FF32FE0C \n"
"    LDR R3, =current_write_ignored\n"
"    LDR R3, [R3]\n"
"    CMP R3, #0\n"
"    BNE loc_D\n" // jump over the next block
"    BL      sub_FF02726C \n"
"    B       sub_FF32FE10 \n"

"loc_FF32FE0C:\n"
"loc_D:\n"
"    BL      fwt_close \n"  // --> Patched. Old value = _Close.
"    LDR     PC, =0xFF32FE10 \n"  // Continue in firmware
);
}
