#include "lolevel.h"
#include "platform.h"
#include "core.h"
#include "conf.h"
#include "stdlib.h"

static long *nrflag = (long*)0x5828;	// ??? ROM:FFD10EE0 "ShutterSoundTask"

typedef struct {
    unsigned int address;
    unsigned int length;
} cam_ptp_data_chunk; //camera specific structure

#define MAX_CHUNKS_FOR_JPEG 4 // filewritetask is prepared for this many chunks
/*
 * fwt_data_struct: defined here as it's camera dependent
 * unneeded members are designated with unkn
 * file_offset, full_size, seek_flag only needs to be defined for DryOS>=r50 generation cameras
 * pdc and name are always needed
 */
typedef struct
{
    int unkn1, unkn2, unkn3, unkn4, unkn5;
    cam_ptp_data_chunk pdc[MAX_CHUNKS_FOR_JPEG];
	int unkn6;
    char name[32];
} fwt_data_struct;

#include "../../../generic/capt_seq.c"

// ROM:FFC59274 task_CaptSeqTask()

void __attribute__((naked,noinline)) capt_seq_task() {
	asm volatile (
"	STMFD	SP!, {R3-R7,LR} \n"                
"	LDR	R7, =0x33324 \n"                     
"	LDR	R6, =0x26C0 \n"                      
"loc_FFC59230:\n"
"	LDR	R0, [R6, #4] \n"                     
"	MOV	R2, #0 \n"                           
"	MOV	R1, SP \n"                           
"	BL	sub_FFC28AA0 \n"                      
"	TST	R0, #1 \n"                           
"	BEQ	loc_FFC5925C \n"                     
"	LDR	R1, =0x5B4 \n"                       
"	LDR	R0, =0xFFC58E30 \n"                  
    "   BL       _DebugAssert \n"
    "   BL       _ExitTask \n"
"	LDMFD	SP!, {R3-R7,PC} \n"                
"loc_FFC5925C:\n"
"	LDR	R0, [SP] \n"                         
"	LDR	R1, [R0] \n"                         
"	CMP	R1, #0x1D \n"                        
"	ADDLS	PC, PC, R1, LSL #2 \n"             
"	B	loc_FFC5946C \n"                       
"	B	loc_FFC592E8 \n"                       
"	B	loc_FFC592F0 \n"                       
"	B	loc_FFC59318 \n"                       
"	B	loc_FFC5932C \n"                       
"	B	loc_FFC59324 \n"                       
"	B	loc_FFC59334 \n"                       
"	B	loc_FFC5933C \n"                       
"	B	loc_FFC59348 \n"                       
"	B	loc_FFC593A0 \n"                       
"	B	loc_FFC5932C \n"                       
"	B	loc_FFC593A8 \n"                       
"	B	loc_FFC593B4 \n"                       
"	B	loc_FFC593BC \n"                       
"	B	loc_FFC593C4 \n"                       
"	B	loc_FFC593CC \n"                       
"	B	loc_FFC593D4 \n"                       
"	B	loc_FFC593DC \n"                       
"	B	loc_FFC593E4 \n"                       
"	B	loc_FFC593F0 \n"                       
"	B	loc_FFC593F8 \n"                       
"	B	loc_FFC59400 \n"                       
"	B	loc_FFC59408 \n"                       
"	B	loc_FFC59410 \n"                       
"	B	loc_FFC5941C \n"                       
"	B	loc_FFC59424 \n"                       
"	B	loc_FFC5942C \n"                       
"	B	loc_FFC59434 \n"                       
"	B	loc_FFC5943C \n"                       
"	B	loc_FFC59448 \n"                       
"	B	loc_FFC59478 \n"                       
"loc_FFC592E8:\n"
"	BL	sub_FFC59B04 \n"              
"	BL      shooting_expo_param_override\n"      // +        
"	B	loc_FFC59340 \n"                       
"loc_FFC592F0:\n"
"	MOV	R0, #0xC \n"                         
"	BL	sub_FFC5D7E0 \n"                      
"	TST	R0, #1 \n"                           
"	LDR	R0, [SP] \n"                         
"	MOVNE	R1, #1 \n"                         
"	LDRNE	R2, [R0, #0xC] \n"                 
"	MOVNE	R0, #1 \n"                         
"	BNE	loc_FFC59398 \n"                     
"	BL	sub_FFC59598_my\n"  //--------->                    
"	B	loc_FFC59478 \n"                       
"loc_FFC59318:\n"
"	MOV	R0, #1 \n"                           
"	BL	sub_FFC59D8C \n"                      
"	B	loc_FFC59478 \n"                       
"loc_FFC59324:\n"
"	BL	sub_FFC59770 \n"                      
"	B	loc_FFC59478 \n"                       
"loc_FFC5932C:\n"
"	BL	sub_FFC59AE4 \n"                      
"	B	loc_FFC59478 \n"                       
"loc_FFC59334:\n"
"	BL	sub_FFC59AEC \n"                      
"	B	loc_FFC59478 \n"                       
"loc_FFC5933C:\n"
"	BL	sub_FFC59C9C \n"                      
"loc_FFC59340:\n"
"	BL	sub_FFC5753C \n"                      
"	B	loc_FFC59478 \n"                       
"loc_FFC59348:\n"
"	LDR	R4, [R0, #0xC] \n"                   
"	BL	sub_FFC59AF4 \n"                      
"	MOV	R0, R4 \n"                           
"	BL	sub_FFD0FDE0 \n"                      
"	TST	R0, #1 \n"                           
"	MOV	R5, R0 \n"                           
"	BNE	loc_FFC59388 \n"                     
"	BL	sub_FFC696BC \n"                      
"	STR	R0, [R4, #0x18] \n"                  
"	MOV	R0, R4 \n"                           
"	BL	sub_FFD10D54 \n"                      
"	MOV	R0, R4 \n"                           
"	BL	sub_FFD110F4 \n"                      
"	MOV	R5, R0 \n"                           
"	LDR	R0, [R4, #0x18] \n"                  
"	BL	sub_FFC698F4 \n"                      
"loc_FFC59388:\n"
"	BL	sub_FFC59AE4 \n"                      
"	MOV	R2, R4 \n"                           
"	MOV	R1, #9 \n"                           
"	MOV	R0, R5 \n"                           
"loc_FFC59398:\n"
"	BL	sub_FFC57934 \n"                      
"	B	loc_FFC59478 \n"                       
"loc_FFC593A0:\n"
"	BL	sub_FFC59D04 \n"                      
"	B	loc_FFC59340 \n"                       
"loc_FFC593A8:\n"
"	LDR	R0, [R7, #0x4C] \n"                  
"	BL	sub_FFC5A0A8 \n"                      
"	B	loc_FFC59478 \n"                       
"loc_FFC593B4:\n"
"	BL	sub_FFC5A358 \n"                      
"	B	loc_FFC59478 \n"                       
"loc_FFC593BC:\n"
"	BL	sub_FFC5A3EC \n"                      
"	B	loc_FFC59478 \n"                       
"loc_FFC593C4:\n"
"	BL	sub_FFD1000C \n"                      
"	B	loc_FFC59478 \n"                       
"loc_FFC593CC:\n"
"	BL	sub_FFD10204 \n"                      
"	B	loc_FFC59478 \n"                       
"loc_FFC593D4:\n"
"	BL	sub_FFD10298 \n"                      
"	B	loc_FFC59478 \n"                       
"loc_FFC593DC:\n"
"	BL	sub_FFD10358 \n"                      
"	B	loc_FFC59478 \n"                       
"loc_FFC593E4:\n"
"	MOV	R0, #0 \n"                           
"	BL	sub_FFD10550 \n"                      
"	B	loc_FFC59478 \n"                       
"loc_FFC593F0:\n"
"	BL	sub_FFD106A0 \n"                      
"	B	loc_FFC59478 \n"                       
"loc_FFC593F8:\n"
"	BL	sub_FFD10730 \n"                      
"	B	loc_FFC59478 \n"                       
"loc_FFC59400:\n"
"	BL	sub_FFD107F0 \n"                      
"	B	loc_FFC59478 \n"                       
"loc_FFC59408:\n"
"	BL	sub_FFC59EE8 \n"                      
"	B	loc_FFC59478 \n"                       
"loc_FFC59410:\n"
"	BL	sub_FFC59F24 \n"                      
"	BL	sub_FFC26C78 \n"                      
"	B	loc_FFC59478 \n"                       
"loc_FFC5941C:\n"
"	BL	sub_FFD10424 \n"                      
"	B	loc_FFC59478 \n"                       
"loc_FFC59424:\n"
"	BL	sub_FFD10468 \n"                      
"	B	loc_FFC59478 \n"                       
"loc_FFC5942C:\n"
"	BL	sub_FFC5C020 \n"                      
"	B	loc_FFC59478 \n"                       
"loc_FFC59434:\n"
"	BL	sub_FFC5C0A0 \n"                      
"	B	loc_FFC59478 \n"                       
"loc_FFC5943C:\n"
"	BL	sub_FFC5C0FC \n"                      
"	BL	sub_FFC5C0BC \n"                      
"	B	loc_FFC59478 \n"                       
"loc_FFC59448:\n"
"	LDRH	R0, [R7, #0x8C] \n"                 
"	CMP	R0, #4 \n"                           
"	LDRNEH	R0, [R7] \n"                      
"	SUBNE	R12, R0, #0x8200 \n"               
"	SUBNES	R12, R12, #0x2A \n"               
"	BNE	loc_FFC59478 \n"                     
"	BL	sub_FFC5C0A0 \n"                      
"	BL	sub_FFC5C440 \n"                      
"	B	loc_FFC59478 \n"                       
"loc_FFC5946C:\n"
"	LDR	R1, =0x70B \n"                       
"	LDR	R0, =0xFFC58E30 \n"                  
"   BL      _DebugAssert \n"
"loc_FFC59478:\n"
"	LDR	R0, [SP] \n"                         
"	LDR	R1, [R0, #4] \n"                     
"	LDR	R0, [R6] \n"                         
"	BL	sub_FFC28810 \n"                      
"	LDR	R4, [SP] \n"                         
"	LDR	R0, [R4, #8] \n"                     
"	CMP	R0, #0 \n"                           
"	LDREQ	R1, =0x132 \n"                     
"	LDREQ	R0, =0xFFC58E30 \n"                
    "   BLEQ     _DebugAssert \n"
"	MOV	R0, #0 \n"                           
"	STR	R0, [R4, #8] \n"                     
"	B	loc_FFC59230 \n"                       
	);
} 


void __attribute__((naked,noinline)) sub_FFC59598_my(){ // 
	asm volatile(
"	STMFD	SP!, {R3-R5,LR} \n"                
"	LDR	R4, [R0, #0xC] \n"                   
"	LDR	R0, [R4, #8] \n"                     
"	ORR	R0, R0, #1 \n"                       
"	STR	R0, [R4, #8] \n"                     
"	BL	sub_FFC59AF4 \n"                      
"	MOV	R0, R4 \n"                           
"	BL	sub_FFC59E9C \n"                      
"	MOV	R0, R4 \n"                           
"	BL	sub_FFD0FA4C \n"                      
"	CMP	R0, #0 \n"                           
"	MOV	R0, R4 \n"                           
"	BEQ	loc_FFC595E8 \n"                     
"	BL	sub_FFD0FAD8 \n"                      
"	TST	R0, #1 \n"                           
"	MOVNE	R2, R4 \n"                         
"	LDMNEFD	SP!, {R3-R5,LR} \n"              
"	MOVNE	R1, #1 \n"                         
"	BNE	sub_FFC57934 \n"                     
"	B	loc_FFC595EC \n"                       
"loc_FFC595E8:\n"
"	BL	sub_FFD0FA9C \n"                      
"loc_FFC595EC:\n"
"	MOV	R0, #0 \n"                           
"	STR	R0, [SP] \n"                         
"	LDR	R0, =0x33324 \n"                     
"	MOV	R2, #2 \n"                           
"	LDRH	R0, [R0, #0x8A] \n"                 
"	MOV	R1, SP \n"                           
"	CMP	R0, #3 \n"                           
"	LDRNE	R0, [R4, #0xC] \n"                 
"	CMPNE	R0, #1 \n"                         
"	MOVHI	R0, #1 \n"                         
"	STRHI	R0, [SP] \n"                       
"	LDR	R0, =0x127 \n"                       
"   BL      _SetPropertyCase \n"
"	BL	sub_FFD2F660 \n"                      
"	BL	sub_FFC696BC \n"                      
"	STR	R0, [R4, #0x18] \n"                  
"	MOV	R0, R4 \n"                           
"	BL	sub_FFD10D54 \n"                      
"	BL	sub_FFD11770 \n"                      
"	MOV	R0, R4 \n"                           
"	BL	sub_FFD10E1C_my\n"			//---------->                    
"	MOV	R5, R0 \n"   
"	BL  capt_seq_hook_raw_here\n"	// +                        
"	BL	sub_FFC5C0A0 \n"                      
"	BL	sub_FFC5C0E8 \n"                      
"	BL	sub_FFC5C128 \n"                      
"	MOV	R2, R4 \n"                           
"	MOV	R1, #1 \n"                           
"	MOV	R0, R5 \n"                           
"	BL	sub_FFC57934 \n"                      
"	BL	sub_FFD110A8 \n"                      
"	CMP	R0, #0 \n"                           
"	LDRNE	R0, [R4, #8] \n"                   
"	ORRNE	R0, R0, #0x2000 \n"                
"	STRNE	R0, [R4, #8] \n"                   
"	LDMFD	SP!, {R3-R5,PC} \n"                
	);
}

void __attribute__((naked,noinline)) sub_FFD10E1C_my(  ) { 
asm volatile (
"	STMFD	SP!, {R0-R8,LR} \n"                
"	MOV	R4, R0 \n"                           
"	BL	sub_FFD11904 \n"                      
"	MVN	R1, #0 \n"                           
"	BL	sub_FFC28844 \n"                      
"	LDR	R5, =0x5828 \n"                      
"	LDR	R0, [R5, #0xC] \n"                   
"	CMP	R0, #0 \n"                           
"	BNE	loc_FFD10E6C \n"                     
"	MOV	R1, #1 \n"                           
"	MOV	R0, #0 \n"                           
"	BL	sub_FFC0F4B4 \n"                      
"	STR	R0, [R5, #0xC] \n"                   
"	MOV	R3, #0 \n"                           
"	STR	R3, [SP] \n"                         
"	LDR	R3, =0xFFD108E0 \n"                  
"	LDR	R0, =0xFFD11078 \n"                  
"	MOV	R2, #0x400 \n"                       
"	MOV	R1, #0x17 \n"                        
"	BL	sub_FFC0F480 \n"                      
"loc_FFD10E6C:\n"
"	MOV	R2, #4 \n"                           
"	ADD	R1, SP, #8 \n"                       
"	MOV	R0, #0x8A \n"                        
"   BL  _GetPropertyCase \n"
"	TST	R0, #1 \n"                           
"	LDRNE	R1, =0x3BA \n"                     
"	LDRNE	R0, =0xFFD10B0C \n"                
    "   BLNE     _DebugAssert \n"
"	LDR	R6, =0x333E0 \n"                     
"	LDR	R7, =0x33324 \n"                     
"	LDR	R3, [R6] \n"                         
"	LDRSH	R2, [R6, #0xC] \n"                 
"	LDRSH	R1, [R6, #0xE] \n"                 
"	LDR	R0, [R7, #0x80] \n"                  
"	BL	sub_FFCE5C8C \n"                      
"   BL      _GetCCDTemperature \n"
"	LDR	R3, =0x5830 \n"                      
"	STRH	R0, [R4, #0xA4] \n"                 
"	SUB	R2, R3, #4 \n"                       
"	STRD	R2, [SP] \n"                        
"	MOV	R1, R0 \n"                           
"	LDRH	R0, [R7, #0x54] \n"                 
"	LDRSH	R2, [R6, #0xC] \n"                 
"	SUB	R3, R3, #8 \n"  
"	BL      sub_FFD11F70\n"
"	BL      wait_until_remote_button_is_released\n"     // +
"	BL      capt_seq_hook_set_nr\n"                     // +
"	B       sub_FFD10ED0\n"                             // continue function in firmware
	);
}

/*************************************************************/

// ROM:FFC91654 task_ExpDrvTask
void __attribute__((naked,noinline)) exp_drv_task(){
	asm volatile(
"	STMFD	SP!, {R4-R8,LR} \n"                
"	SUB	SP, SP, #0x20 \n"                    
"	LDR	R8, =0xBB8 \n"                       
"	LDR	R7, =0x38CC \n"                      
"	LDR	R5, =0x3C714 \n"                     
"	MOV	R0, #0 \n"                           
"	ADD	R6, SP, #0x10 \n"                    
"	STR	R0, [SP, #0xC] \n"                   
"loc_FFC91624:\n"
"	LDR	R0, [R7, #0x20] \n"                  
"	MOV	R2, #0 \n"                           
"	ADD	R1, SP, #0x1C \n"                    
"	BL	sub_FFC28AA0 \n"                      
"	LDR	R0, [SP, #0xC] \n"                   
"	CMP	R0, #1 \n"                           
"	BNE	loc_FFC91670 \n"                     
"	LDR	R0, [SP, #0x1C] \n"                  
"	LDR	R0, [R0] \n"                         
"	CMP	R0, #0x13 \n"                        
"	CMPNE	R0, #0x14 \n"                      
"	CMPNE	R0, #0x15 \n"                      
"	CMPNE	R0, #0x16 \n"                      
"	BEQ	loc_FFC917D4 \n"                     
"	CMP	R0, #0x28 \n"                        
"	BEQ	loc_FFC9175C \n"                     
"	ADD	R1, SP, #0xC \n"                     
"	MOV	R0, #0 \n"                           
"	BL	sub_FFC915B4 \n"                      
"loc_FFC91670:\n"
"	LDR	R0, [SP, #0x1C] \n"                  
"	LDR	R1, [R0] \n"                         
"	CMP	R1, #0x2E \n"                        
"	BNE	loc_FFC916A0 \n"                     
"	LDR	R0, [SP, #0x1C] \n"                  
"	BL	sub_FFC9290C \n"                      
"	LDR	R0, [R7, #0x1C] \n"                  
"	MOV	R1, #1 \n"                           
"	BL	sub_FFC28810 \n"                      
"   BL       _ExitTask \n"
"	ADD	SP, SP, #0x20 \n"                    
"	LDMFD	SP!, {R4-R8,PC} \n"                
"loc_FFC916A0:\n"
"	CMP	R1, #0x2D \n"                        
"	BNE	loc_FFC916BC \n"                     
"	LDR	R2, [R0, #0x8C]! \n"                 
"	LDR	R1, [R0, #4] \n"                     
"	MOV	R0, R1 \n"                           
"	BLX	R2 \n"                               
"	B	loc_FFC91BFC \n"                       
"loc_FFC916BC:\n"
"	CMP	R1, #0x26 \n"                        
"	BNE	loc_FFC9170C \n"                     
"	LDR	R0, [R7, #0x1C] \n"                  
"	MOV	R1, #0x80 \n"                        
"	BL	sub_FFC28844 \n"                      
"	LDR	R0, =0xFFC8DD80 \n"                  
"	MOV	R1, #0x80 \n"                        
"	BL	sub_FFD0850C \n"                      
"	LDR	R0, [R7, #0x1C] \n"                  
"	MOV	R2, R8 \n"                           
"	MOV	R1, #0x80 \n"                        
"	BL	sub_FFC28750 \n"                      
"	TST	R0, #1 \n"                           
"	LDRNE	R1, =0xE5F \n"                     
"	BNE	loc_FFC917C8 \n"                     
"loc_FFC916F8:\n"
"	LDR	R1, [SP, #0x1C] \n"                  
"	LDR	R0, [R1, #0x90] \n"                  
"	LDR	R1, [R1, #0x8C] \n"                  
"	BLX	R1 \n"                               
"	B	loc_FFC91BFC \n"                       
"loc_FFC9170C:\n"
"	CMP	R1, #0x27 \n"                        
"	BNE	loc_FFC91754 \n"                     
"	ADD	R1, SP, #0xC \n"                     
"	BL	sub_FFC915B4 \n"                      
"	LDR	R0, [R7, #0x1C] \n"                  
"	MOV	R1, #0x100 \n"                       
"	BL	sub_FFC28844 \n"                      
"	LDR	R0, =0xFFC8DD90 \n"                  
"	MOV	R1, #0x100 \n"                       
"	BL	sub_FFD08794 \n"                      
"	LDR	R0, [R7, #0x1C] \n"                  
"	MOV	R2, R8 \n"                           
"	MOV	R1, #0x100 \n"                       
"	BL	sub_FFC28750 \n"                      
"	TST	R0, #1 \n"                           
"	BEQ	loc_FFC916F8 \n"                     
"	LDR	R1, =0xE69 \n"                       
"	B	loc_FFC917C8 \n"                       
"loc_FFC91754:\n"
"	CMP	R1, #0x28 \n"                        
"	BNE	loc_FFC9176C \n"                     
"loc_FFC9175C:\n"
"	LDR	R0, [SP, #0x1C] \n"                  
"	ADD	R1, SP, #0xC \n"                     
"	BL	sub_FFC915B4 \n"                      
"	B	loc_FFC916F8 \n"                       
"loc_FFC9176C:\n"
"	CMP	R1, #0x2B \n"                        
"	BNE	loc_FFC91784 \n"                     
"	BL	sub_FFC8118C \n"                      
"	BL	sub_FFC81DB4 \n"                      
"	BL	sub_FFC81904 \n"                      
"	B	loc_FFC916F8 \n"                       
"loc_FFC91784:\n"
"	CMP	R1, #0x2C \n"                        
"	BNE	loc_FFC917D4 \n"                     
"	LDR	R0, [R7, #0x1C] \n"                  
"	MOV	R1, #4 \n"                           
"	BL	sub_FFC28844 \n"                      
"	LDR	R1, =0xFFC8DDB0 \n"                  
"	LDR	R0, =0xFFFFF400 \n"                  
"	MOV	R2, #4 \n"                           
"	BL	sub_FFC80C08 \n"                      
"	BL	sub_FFC80E90 \n"                      
"	LDR	R0, [R7, #0x1C] \n"                  
"	MOV	R2, R8 \n"                           
"	MOV	R1, #4 \n"                           
"	BL	sub_FFC2866C \n"                      
"	TST	R0, #1 \n"                           
"	BEQ	loc_FFC916F8 \n"                     
"	LDR	R1, =0xE91 \n"                       
"loc_FFC917C8:\n"
"	LDR	R0, =0xFFC8E3F0 \n"                  
"   BL       _DebugAssert \n"
"	B	loc_FFC916F8 \n"                       
"loc_FFC917D4:\n"
"	LDR	R0, [SP, #0x1C] \n"                  
"	MOV	R4, #1 \n"                           
"	LDR	R1, [R0] \n"                         
"	CMP	R1, #0x11 \n"                        
"	CMPNE	R1, #0x12 \n"                      
"	BNE	loc_FFC91844 \n"                     
"	LDR	R1, [R0, #0x7C] \n"                  
"	ADD	R1, R1, R1, LSL #1 \n"               
"	ADD	R1, R0, R1, LSL #2 \n"               
"	SUB	R1, R1, #8 \n"                       
"	LDMIA	R1, {R2-R4} \n"                    
"	STMIA	R6, {R2-R4} \n"                   
"	BL	sub_FFC8FF40 \n"                      
"	LDR	R0, [SP, #0x1C] \n"                  
"	LDR	R1, [R0, #0x7C] \n"                  
"	LDR	R3, [R0, #0x8C] \n"                  
"	LDR	R2, [R0, #0x90] \n"                  
"	ADD	R0, R0, #4 \n"                       
"	BLX	R3 \n"                               
"	LDR	R0, [SP, #0x1C] \n"                  
"	BL	sub_FFC92CD4 \n"                      
"	LDR	R0, [SP, #0x1C] \n"                  
"	LDR	R1, [R0, #0x7C] \n"                  
"	LDR	R3, [R0, #0x94] \n"                  
"	LDR	R2, [R0, #0x98] \n"                  
"	ADD	R0, R0, #4 \n"                       
"	BLX	R3 \n"                               
"	B	loc_FFC91B3C \n"                       
"loc_FFC91844:\n"
"	CMP	R1, #0x13 \n"                        
"	CMPNE	R1, #0x14 \n"                      
"	CMPNE	R1, #0x15 \n"                      
"	CMPNE	R1, #0x16 \n"                      
"	BNE	loc_FFC918FC \n"                     
"	ADD	R3, SP, #0xC \n"                     
"	MOV	R2, SP \n"                           
"	ADD	R1, SP, #0x10 \n"                    
"	BL	sub_FFC9021C \n"                      
"	CMP	R0, #1 \n"                           
"	MOV	R4, R0 \n"                           
"	CMPNE	R4, #5 \n"                         
"	BNE	loc_FFC91898 \n"                     
"	LDR	R0, [SP, #0x1C] \n"                  
"	MOV	R2, R4 \n"                           
"	LDR	R1, [R0, #0x7C]! \n"                 
"	LDR	R12, [R0, #0x10]! \n"                
"	LDR	R3, [R0, #4] \n"                     
"	MOV	R0, SP \n"                           
"	BLX	R12 \n"                              
"	B	loc_FFC918D0 \n"                       
"loc_FFC91898:\n"
"	LDR	R0, [SP, #0x1C] \n"                  
"	CMP	R4, #2 \n"                           
"	LDR	R3, [R0, #0x90] \n"                  
"	CMPNE	R4, #6 \n"                         
"	BNE	loc_FFC918E4 \n"                     
"	LDR	R12, [R0, #0x8C] \n"                 
"	MOV	R0, SP \n"                           
"	MOV	R2, R4 \n"                           
"	MOV	R1, #1 \n"                           
"	BLX	R12 \n"                              
"	LDR	R0, [SP, #0x1C] \n"                  
"	MOV	R2, SP \n"                           
"	ADD	R1, SP, #0x10 \n"                    
"	BL	sub_FFC912BC \n"                      
"loc_FFC918D0:\n"
"	LDR	R0, [SP, #0x1C] \n"                  
"	LDR	R2, [SP, #0xC] \n"                   
"	MOV	R1, R4 \n"                           
"	BL	sub_FFC91554 \n"                      
"	B	loc_FFC91B3C \n"                       
"loc_FFC918E4:\n"
"	LDR	R1, [R0, #0x7C] \n"                  
"	LDR	R12, [R0, #0x8C] \n"                 
"	ADD	R0, R0, #4 \n"                       
"	MOV	R2, R4 \n"                           
"	BLX	R12 \n"                              
"	B	loc_FFC91B3C \n"                       
"loc_FFC918FC:\n"
"	CMP	R1, #0x22 \n"                        
"	CMPNE	R1, #0x23 \n"                      
"	BNE	loc_FFC91948 \n"                     
"	LDR	R1, [R0, #0x7C] \n"                  
"	ADD	R1, R1, R1, LSL #1 \n"               
"	ADD	R1, R0, R1, LSL #2 \n"               
"	SUB	R1, R1, #8 \n"                       
"	LDMIA	R1, {R2-R4} \n"                    
"	STMIA	R6, {R2-R4} \n"                    
"	BL	sub_FFC8F490 \n"                      
"	LDR	R0, [SP, #0x1C] \n"                  
"	LDR	R1, [R0, #0x7C] \n"                  
"	LDR	R3, [R0, #0x8C] \n"                  
"	LDR	R2, [R0, #0x90] \n"                  
"	ADD	R0, R0, #4 \n"                       
"	BLX	R3 \n"                               
"	LDR	R0, [SP, #0x1C] \n"                  
"	BL	sub_FFC8F784 \n"                      
"	B	loc_FFC91B3C \n"                       
"loc_FFC91948:\n"
"	ADD	R1, R0, #4 \n"                       
"	LDMIA	R1, {R2,R3,R12} \n"                
"	STMIA	R6, {R2,R3,R12} \n"                
"	LDR	R1, [R0] \n"                         
"	CMP	R1, #0x25 \n"                        
"	ADDLS	PC, PC, R1, LSL #2 \n"             
"	B	loc_FFC91B1C \n"                       
"	B	loc_FFC919FC \n"                       
"	B	loc_FFC919FC \n"                       
"	B	loc_FFC91A04 \n"                       
"	B	loc_FFC91A0C \n"                       
"	B	loc_FFC91A0C \n"                       
"	B	loc_FFC91A0C \n"                       
"	B	loc_FFC919FC \n"                       
"	B	loc_FFC91A04 \n"                       
"	B	loc_FFC91A0C \n"                       
"	B	loc_FFC91A0C \n"                       
"	B	loc_FFC91A24 \n"                       
"	B	loc_FFC91A24 \n"                       
"	B	loc_FFC91B10 \n"                       
"	B	loc_FFC91B18 \n"                       
"	B	loc_FFC91B18 \n"                       
"	B	loc_FFC91B18 \n"                       
"	B	loc_FFC91B18 \n"                       
"	B	loc_FFC91B1C \n"                       
"	B	loc_FFC91B1C \n"                       
"	B	loc_FFC91B1C \n"                       
"	B	loc_FFC91B1C \n"                       
"	B	loc_FFC91B1C \n"                       
"	B	loc_FFC91B1C \n"                       
"	B	loc_FFC91A14 \n"                       
"	B	loc_FFC91A1C \n"                       
"	B	loc_FFC91A1C \n"                       
"	B	loc_FFC91A30 \n"                       
"	B	loc_FFC91A30 \n"                       
"	B	loc_FFC91A38 \n"                       
"	B	loc_FFC91A68 \n"                       
"	B	loc_FFC91A98 \n"                       
"	B	loc_FFC91AC8 \n"                       
"	B	loc_FFC91AF8 \n"                       
"	B	loc_FFC91AF8 \n"                       
"	B	loc_FFC91B1C \n"                       
"	B	loc_FFC91B1C \n"                       
"	B	loc_FFC91B00 \n"                       
"	B	loc_FFC91B08 \n"                       
"loc_FFC919FC:\n"
"	BL	sub_FFC8E298 \n"                      
"	B	loc_FFC91B1C \n"                       
"loc_FFC91A04:\n"
"	BL	sub_FFC8E51C \n"                      
"	B	loc_FFC91B1C \n"                       
"loc_FFC91A0C:\n"
"	BL	sub_FFC8E724 \n"                      
"	B	loc_FFC91B1C \n"                       
"loc_FFC91A14:\n"
"	BL	sub_FFC8E99C \n"                      
"	B	loc_FFC91B1C \n"                       
"loc_FFC91A1C:\n"
"	BL	sub_FFC8EB94 \n"                      
"	B	loc_FFC91B1C \n"                       
"loc_FFC91A24:\n"
"	BL	sub_FFC8EE50_my\n"		//---------->                   
"	MOV	R4, #0 \n"                           
"	B	loc_FFC91B1C \n"                       
"loc_FFC91A30:\n"
"	BL	sub_FFC8EF90 \n"                      
"	B	loc_FFC91B1C \n"                       
"loc_FFC91A38:\n"
"	LDRH	R1, [R0, #4] \n"                    
"	STRH	R1, [SP, #0x10] \n"                 
"	LDRH	R1, [R5, #2] \n"                    
"	STRH	R1, [SP, #0x12] \n"                 
"	LDRH	R1, [R5, #4] \n"                    
"	STRH	R1, [SP, #0x14] \n"                 
"	LDRH	R1, [R5, #6] \n"                    
"	STRH	R1, [SP, #0x16] \n"                 
"	LDRH	R1, [R0, #0xC] \n"                  
"	STRH	R1, [SP, #0x18] \n"                 
"	BL	sub_FFC92980 \n"                      
"	B	loc_FFC91B1C \n"                       
"loc_FFC91A68:\n"
"	LDRH	R1, [R0, #4] \n"                    
"	STRH	R1, [SP, #0x10] \n"                 
"	LDRH	R1, [R5, #2] \n"                    
"	STRH	R1, [SP, #0x12] \n"                 
"	LDRH	R1, [R5, #4] \n"                    
"	STRH	R1, [SP, #0x14] \n"                 
"	LDRH	R1, [R5, #6] \n"                    
"	STRH	R1, [SP, #0x16] \n"                 
"	LDRH	R1, [R5, #8] \n"                    
"	STRH	R1, [SP, #0x18] \n"                 
"	BL	sub_FFC92AEC \n"                      
"	B	loc_FFC91B1C \n"                       
"loc_FFC91A98:\n"
"	LDRH	R1, [R5] \n"                        
"	STRH	R1, [SP, #0x10] \n"                 
"	LDRH	R1, [R0, #6] \n"                    
"	STRH	R1, [SP, #0x12] \n"                 
"	LDRH	R1, [R5, #4] \n"                    
"	STRH	R1, [SP, #0x14] \n"                 
"	LDRH	R1, [R5, #6] \n"                    
"	STRH	R1, [SP, #0x16] \n"                 
"	LDRH	R1, [R5, #8] \n"                    
"	STRH	R1, [SP, #0x18] \n"                 
"	BL	sub_FFC92B98 \n"                      
"	B	loc_FFC91B1C \n"                       
"loc_FFC91AC8:\n"
"	LDRH	R1, [R5] \n"                        
"	STRH	R1, [SP, #0x10] \n"                 
"	LDRH	R1, [R5, #2] \n"                    
"	STRH	R1, [SP, #0x12] \n"                 
"	LDRH	R1, [R5, #4] \n"                    
"	STRH	R1, [SP, #0x14] \n"                 
"	LDRH	R1, [R5, #6] \n"                    
"	STRH	R1, [SP, #0x16] \n"                 
"	LDRH	R1, [R0, #0xC] \n"                  
"	STRH	R1, [SP, #0x18] \n"                 
"	BL	sub_FFC92C38 \n"                      
"	B	loc_FFC91B1C \n"                       
"loc_FFC91AF8:\n"
"	BL	sub_FFC8F2E8 \n"                      
"	B	loc_FFC91B1C \n"                       
"loc_FFC91B00:\n"
"	BL	sub_FFC8F888 \n"                      
"	B	loc_FFC91B1C \n"                       
"loc_FFC91B08:\n"
"	BL	sub_FFC8FAC4 \n"                      
"	B	loc_FFC91B1C \n"                       
"loc_FFC91B10:\n"
"	BL	sub_FFC8FC40 \n"                      
"	B	loc_FFC91B1C \n"                       
"loc_FFC91B18:\n"
"	BL	sub_FFC8FDDC \n"                      
"loc_FFC91B1C:\n"
"	LDR	R0, [SP, #0x1C] \n"                  
"	LDR	R1, [R0, #0x7C] \n"                  
"	LDR	R3, [R0, #0x8C] \n"                  
"	LDR	R2, [R0, #0x90] \n"                  
"	ADD	R0, R0, #4 \n"                       
"	BLX	R3 \n"                               
"	CMP	R4, #1 \n"                           
"	BNE	loc_FFC91B84 \n"                     
"loc_FFC91B3C:\n"
"	LDR	R0, [SP, #0x1C] \n"                  
"	MOV	R2, #0xC \n"                         
"	LDR	R1, [R0, #0x7C] \n"                  
"	ADD	R1, R1, R1, LSL #1 \n"               
"	ADD	R0, R0, R1, LSL #2 \n"               
"	SUB	R4, R0, #8 \n"                       
"	LDR	R0, =0x3C714 \n"                     
"	ADD	R1, SP, #0x10 \n"                    
"	BL	sub_FFE80E10 \n"                      
"	LDR	R0, =0x3C720 \n"                     
"	MOV	R2, #0xC \n"                         
"	ADD	R1, SP, #0x10 \n"                    
"	BL	sub_FFE80E10 \n"                      
"	LDR	R0, =0x3C72C \n"                     
"	MOV	R2, #0xC \n"                         
"	MOV	R1, R4 \n"                           
"	BL	sub_FFE80E10 \n"                      
"	B	loc_FFC91BFC \n"                       
"loc_FFC91B84:\n"
"	LDR	R0, [SP, #0x1C] \n"                  
"	LDR	R0, [R0] \n"                         
"	CMP	R0, #0xB \n"                         
"	BNE	loc_FFC91BCC \n"                     
"	MOV	R3, #0 \n"                           
"	STR	R3, [SP] \n"                         
"	MOV	R3, #1 \n"                           
"	MOV	R2, #1 \n"                           
"	MOV	R1, #1 \n"                           
"	MOV	R0, #0 \n"                           
"	BL	sub_FFC8E0A0 \n"                      
"	MOV	R3, #0 \n"                           
"	STR	R3, [SP] \n"                         
"	MOV	R3, #1 \n"                           
"	MOV	R2, #1 \n"                           
"	MOV	R1, #1 \n"                           
"	MOV	R0, #0 \n"                           
"	B	loc_FFC91BF8 \n"                       
"loc_FFC91BCC:\n"
"	MOV	R3, #1 \n"                           
"	MOV	R2, #1 \n"                           
"	MOV	R1, #1 \n"                           
"	MOV	R0, #1 \n"                           
"	STR	R3, [SP] \n"                         
"	BL	sub_FFC8E0A0 \n"                      
"	MOV	R3, #1 \n"                           
"	MOV	R2, #1 \n"                           
"	MOV	R1, #1 \n"                           
"	MOV	R0, #1 \n"                           
"	STR	R3, [SP] \n"                         
"loc_FFC91BF8:\n"
"	BL	sub_FFC8E1E0 \n"                      
"loc_FFC91BFC:\n"
"	LDR	R0, [SP, #0x1C] \n"                  
"	BL	sub_FFC9290C \n"                      
"	B	loc_FFC91624 \n" 
	);
}

void __attribute__((naked,noinline)) sub_FFC8EE50_my(){ // 
	asm volatile(
"	STMFD	SP!, {R4-R8,LR} \n"                
"	LDR	R7, =0x38CC \n"                      
"	MOV	R4, R0 \n"                           
"	LDR	R0, [R7, #0x1C] \n"                  
"	MOV	R1, #0x3E \n"                        
"	BL	sub_FFC28844 \n"                      
"	LDRSH	R0, [R4, #4] \n"                   
"	MOV	R2, #0 \n"                           
"	MOV	R1, #0 \n"                           
"	BL	sub_FFC8DE04 \n"                      
"	MOV	R6, R0 \n"                           
"	LDRSH	R0, [R4, #6] \n"                   
"	BL	sub_FFC8DF14 \n"                      
"	LDRSH	R0, [R4, #8] \n"                   
"	BL	sub_FFC8DF6C \n"                      
"	LDRSH	R0, [R4, #0xA] \n"                 
"	BL	sub_FFC8DFC4 \n"                      
"	LDRSH	R0, [R4, #0xC] \n"                 
"	MOV	R1, #0 \n"                           
"	BL	sub_FFC8E01C \n"                      
"	MOV	R5, R0 \n"                           
"	LDR	R0, [R4] \n"                         
"	LDR	R8, =0x3C72C \n"                     
"	CMP	R0, #0xB \n"                         
"	MOVEQ	R6, #0 \n"                         
"	MOVEQ	R5, #0 \n"                         
"	BEQ	loc_FFC8EEE4 \n"                     
"	CMP	R6, #1 \n"                           
"	BNE	loc_FFC8EEE4 \n"                     
"	LDRSH	R0, [R4, #4] \n"                   
"	LDR	R1, =0xFFC8DD70 \n"                  
"	MOV	R2, #2 \n"                           
"	BL	sub_FFD08660 \n"                      
"	STRH	R0, [R4, #4] \n"                    
"	MOV	R0, #0 \n"                           
"	STR	R0, [R7, #0x28] \n"                  
"	B	loc_FFC8EEEC \n"                       
"loc_FFC8EEE4:\n"
"	LDRH	R0, [R8] \n"                        
"	STRH	R0, [R4, #4] \n"                    
"loc_FFC8EEEC:\n"
"	CMP	R5, #1 \n"                           
"	LDRNEH	R0, [R8, #8] \n"                  
"	BNE	loc_FFC8EF08 \n"                     
"	LDRSH	R0, [R4, #0xC] \n"                 
"	LDR	R1, =0xFFC8DDF4 \n"                  
"	MOV	R2, #0x20 \n"                        
"	BL	sub_FFC9293C \n"                      
"loc_FFC8EF08:\n"
"	STRH	R0, [R4, #0xC] \n"                  
"	LDRSH	R0, [R4, #6] \n"                   
"	BL	sub_FFC80EFC_my\n"		//----------->                     
"	LDRSH	R0, [R4, #8] \n"                   
"	MOV	R1, #1 \n"                           
"	BL	sub_FFC8164C \n"                      
"	MOV	R1, #0 \n"                           
"	ADD	R0, R4, #8 \n"                       
"	BL	sub_FFC816D4 \n"                      
"	LDRSH	R0, [R4, #0xE] \n"                 
"	BL	sub_FFC890FC \n"                      
"	LDR	R4, =0xBB8 \n"                       
"	CMP	R6, #1 \n"                           
"	BNE	loc_FFC8EF60 \n"                     
"	LDR	R0, [R7, #0x1C] \n"                  
"	MOV	R2, R4 \n"                           
"	MOV	R1, #2 \n"                           
"	BL	sub_FFC28750 \n"                      
"	TST	R0, #1 \n"                           
"	LDRNE	R1, =0x5A3 \n"                     
"	LDRNE	R0, =0xFFC8E3F0 \n"                
    "   BLNE     _DebugAssert \n"
"loc_FFC8EF60:\n"
"	CMP	R5, #1 \n"                           
"	LDMNEFD	SP!, {R4-R8,PC} \n"              
"	LDR	R0, [R7, #0x1C] \n"                  
"	MOV	R2, R4 \n"                           
"	MOV	R1, #0x20 \n"                        
"	BL	sub_FFC28750 \n"                      
"	TST	R0, #1 \n"                           
"	LDRNE	R1, =0x5A8 \n"                     
"	LDRNE	R0, =0xFFC8E3F0 \n"                
"	LDMNEFD	SP!, {R4-R8,LR} \n"              
    "   BNE      _DebugAssert \n"
"	LDMFD	SP!, {R4-R8,PC} \n"       
	);
}

void __attribute__((naked,noinline)) sub_FFC80EFC_my(){ // 
	asm volatile(
	"	STMFD	SP!, {R4-R6,LR} \n"                
"	LDR	R5, =0x35C0 \n"                      
"	MOV	R4, R0 \n"                           
"	LDR	R0, [R5, #4] \n"                     
"	CMP	R0, #1 \n"                           
"	LDRNE	R1, =0x146 \n"                     
"	LDRNE	R0, =0xFFC80D00 \n"                
"   BLNE     _DebugAssert \n"
"	CMN	R4, #0xC00 \n"                       
"	LDREQSH	R4, [R5, #2] \n"                 
"	CMN	R4, #0xC00 \n"                       
"	MOVEQ	R1, #0x14C \n"                     
"	LDREQ	R0, =0xFFC80D00 \n"                
"	STRH	R4, [R5, #2] \n"                    
"   BLEQ     _DebugAssert \n"
"	MOV	R0, R4 \n"                           
//"	BL	sub_FFD7D848 \n" 			// -                     
"	BL      apex2us\n"				// +
"	MOV	R4, R0 \n"                           
//"	BL	sub_FFCB3A60 \n"                      
"	MOV	R0, R4 \n"                           
"	BL	sub_FFCB80F0 \n"                      
"	TST	R0, #1 \n"                           
"	LDRNE	R1, =0x151 \n"                     
"	LDMNEFD	SP!, {R4-R6,LR} \n"              
"	LDRNE	R0, =0xFFC80D00 \n"                
"   BNE      _DebugAssert \n"
"	LDMFD	SP!, {R4-R6,PC} \n"                
	);
}


//** filewritetask  @ 0xFFDE66CC 

void __attribute__((naked,noinline)) filewritetask(  ) { 
asm volatile (
    "STMFD   SP!, {R1-R5,LR}\n"
    "LDR     R4, =0x8428\n"
"loc_FFDE66D4:\n"
    "LDR     R0, [R4, #0x10]\n"
    "MOV     R2, #0\n"
    "ADD     R1, SP, #8\n"
    "BL      sub_FFC28AA0\n"
    "CMP     R0, #0\n"
    "BNE     loc_FFDE6704\n"
    "LDR     R0, [SP, #8]\n"
    "LDR     R1, [R0]\n"
    "CMP     R1, #1\n"
    "BNE     loc_FFDE670C\n"
    "LDR     R0, [R4, #8]\n"
    "BL      _GiveSemaphore \n"
"loc_FFDE6704:\n"
    "BL      _ExitTask \n"
    "LDMFD   SP!, {R1-R5,PC}\n"
"loc_FFDE670C:\n"
    "SUB     R1, R1, #2\n"
    "CMP     R1, #6\n"
    "ADDLS   PC, PC, R1, LSL #2\n"
    "B       loc_FFDE66D4\n"
    "B       loc_FFDE6738\n" //(0)
    "B       loc_FFDE679C\n" //(1)
    "B       loc_FFDE67A4\n" //(2)
    "B       loc_FFDE67A4\n" //(3)
    "B       loc_FFDE67A4\n" //(4)
    "B       loc_FFDE67A4\n" //(5)
    "B       loc_FFDE67AC\n" //(6)
"loc_FFDE6738:\n"            //(state 0)
    "MOV     R0, #0\n"
    "STR     R0, [SP]\n"
"loc_FFDE6740:\n"
    "LDR     R0, [R4, #0x10]\n"
    "MOV     R1, SP\n"
    "BL      sub_FFC28CE4\n"
    "LDR     R0, [SP]\n"
    "CMP     R0, #0\n"
    "BEQ     loc_FFDE676C\n"
    "LDR     R0, [R4, #0x10]\n"
    "MOV     R2, #0\n"
    "ADD     R1, SP, #4\n"
    "BL      sub_FFC28AA0\n"
    "B       loc_FFDE6740\n"
"loc_FFDE676C:\n"
    "LDR     R0, [R4]\n"
    "CMN     R0, #1\n"
    "BEQ     loc_FFDE6790\n"
//    "BL      _Close \n"       //original
    "BL      fwt_close\n" 		//patch
    "MVN     R0, #0\n"
    "STR     R0, [R4]\n"
    "LDR     R0, =0xBF334\n"
    "BL      sub_FFC514AC\n"
    "BL      sub_FFC4F748\n"
"loc_FFDE6790:\n"
    "LDR     R0, [R4, #0xC]\n"
    "BL      _GiveSemaphore \n"
    "B       loc_FFDE66D4\n"
"loc_FFDE679C:\n"               //-> open (state 1)
//    "BL      sub_FFDE69BC\n"  //original
    "BL      sub_FFDE69BC_my\n" //patch
    "B       loc_FFDE66D4\n"
"loc_FFDE67A4:\n"			 	// -> write stage (states 2..5)
//    "BL      sub_FFDE6AF0\n"  //original
    "BL      sub_FFDE6AF0_my\n" //patch
    "B       loc_FFDE66D4\n"
"loc_FFDE67AC:\n"               // -> close stage (state 6)
//    "BL      sub_FFDE6558\n"  //original
    "BL      sub_FFDE6558_my\n" //patch
    "B       loc_FFDE66D4\n"
	);
}


//** sub_FFDE69BC_my  @ 0xFFDE69BC

void __attribute__((naked,noinline)) sub_FFDE69BC_my(  ) { //open
asm volatile (
    "STMFD   SP!, {R4-R8,LR}\n"
    "MOV     R4, R0\n"
    "ADD     R0, R0, #0x38\n"
    "SUB     SP, SP, #0x38\n"
    "BL      sub_FFC514AC\n"
    "MOV     R1, #0\n"
    "BL      sub_FFC4F6F8\n"
    "LDR     R0, [R4, #0xC]\n"
    "BL      sub_FFC4E55C\n"
    "LDR     R7, [R4, #8]\n"
    "LDR     R8, =0x1B6\n"
    "ADD     R6, R4, #0x38\n"
    "LDR     R5, [R4, #0xC]\n"
//hook start
      "STMFD SP!, {R4-R12,LR}\n"
      "MOV R0, R4\n"
      "BL filewrite_main_hook\n"
      "LDMFD SP!, {R4-R12,LR}\n"
//hook end
    "MOV     R0, R6\n"
    "MOV     R1, R7\n"
    "MOV     R2, R8\n"
//    "BL      _Open \n"        //original
	"BL      fwt_open\n"        //patch
    "LDR PC, =0xFFDE6A00\n"     //+ jump back to ROM
/*    "CMN     R0, #1\n"        //@sub_FFDE69BC+0x44
    "BNE     loc_FFDE6A60\n"
    "MOV     R0, R6\n"
    "BL      sub_FFC2649C\n"
    "MOV     R2, #0xF\n"
    "MOV     R1, R6\n"
    "MOV     R0, SP\n"
    "BL      sub_FFE80E10\n"
    "LDR     R0, =0x41FF\n"
    "MOV     R1, #0\n"
    "STRB    R1, [SP, #0xF]\n"
    "STR     R0, [SP, #0x20]\n"
    "MOV     R0, #0x10\n"
    "ADD     R2, SP, #0x24\n"
    "STMIA   R2, {R0,R1,R5}\n"
    "ADD     R1, SP, #0x20\n"
    "MOV     R0, SP\n"
    "STR     R5, [SP, #0x30]\n"
    "STR     R5, [SP, #0x34]\n"
    "BL      sub_FFC4F068\n"
    "MOV     R2, R8\n"
    "MOV     R1, R7\n"
    "MOV     R0, R6\n"
    "BL      _Open \n"
"loc_FFDE6A60:\n"
    "LDR     R5, =0x8428\n"
    "CMN     R0, #1\n"
    "STR     R0, [R5]\n"
    "BNE     loc_FFDE6AA8\n"
    "LDR     R0, [R5, #0x18]\n"
    "CMP     R0, #0\n"
    "BLXNE   R0\n"
    "ADD     R0, R4, #0x38\n"
    "BL      sub_FFC514AC\n"
    "BL      sub_FFC4F748\n"
    "LDR     R1, [R5, #0x14]\n"
    "CMP     R1, #0\n"
    "ADDNE   SP, SP, #0x38\n"
    "LDMNEFD SP!, {R4-R8,LR}\n"
    "LDRNE   R0, =0x9200001\n"
    "BXNE    R1\n"
"loc_FFDE6AA0:\n"
    "ADD     SP, SP, #0x38\n"
    "LDMFD   SP!, {R4-R8,PC}\n"
"loc_FFDE6AA8:\n"
    "LDR     R0, =0xBF334\n"
    "MOV     R2, #0x20\n"
    "ADD     R1, R4, #0x38\n"
    "BL      sub_FFE80F78\n"
    "MOV     R1, R4\n"
    "MOV     R0, #4\n"
    "BL      sub_FFDE6498\n"
    "B       loc_FFDE6AA0\n"*/
	);
}


//** sub_FFDE6AF0_my  @ 0xFFDE6AF0 

void __attribute__((naked,noinline)) sub_FFDE6AF0_my(  ) { //write
asm volatile (
    "STMFD   SP!, {R4-R10,LR}\n"
    "MOV     R4, R0\n"
    "LDR     R0, [R0]\n"
    "CMP     R0, #4\n"
    "LDREQ   R6, [R4, #0x18]\n"
    "LDREQ   R7, [R4, #0x14]\n"
    "BEQ     loc_FFDE6B3C\n"
    "CMP     R0, #5\n"
    "LDREQ   R6, [R4, #0x20]\n"
    "LDREQ   R7, [R4, #0x1C]\n"
    "BEQ     loc_FFDE6B3C\n"
    "CMP     R0, #6\n"
    "LDREQ   R6, [R4, #0x28]\n"
    "LDREQ   R7, [R4, #0x24]\n"
    "BEQ     loc_FFDE6B3C\n"
    "CMP     R0, #7\n"
    "BNE     loc_FFDE6B50\n"
    "LDR     R6, [R4, #0x30]\n"
    "LDR     R7, [R4, #0x2C]\n"
"loc_FFDE6B3C:\n"
    "CMP     R6, #0\n"
    "BNE     loc_FFDE6B60\n"
"loc_FFDE6B44:\n"
    "MOV     R1, R4\n"
    "MOV     R0, #8\n"
    "B       loc_FFDE6BF4\n"
"loc_FFDE6B50:\n"
    "LDR     R1, =0x29F\n"
    "LDR     R0, =0xFFDE67C4\n"
    "BL      _DebugAssert \n"
    "B       loc_FFDE6B44\n"
"loc_FFDE6B60:\n"
    "LDR     R9, =0x8428\n"
    "MOV     R5, R6\n"
"loc_FFDE6B68:\n"
    "LDR     R0, [R4, #4]\n"
    "CMP     R5, #0x1000000\n"
    "MOVLS   R8, R5\n"
    "MOVHI   R8, #0x1000000\n"
    "BIC     R1, R0, #0xFF000000\n"
    "CMP     R1, #0\n"
    "BICNE   R0, R0, #0xFF000000\n"
    "RSBNE   R0, R0, #0x1000000\n"
    "CMPNE   R8, R0\n"
    "MOVHI   R8, R0\n"
    "LDR     R0, [R9]\n"
    "MOV     R2, R8\n"
    "MOV     R1, R7\n"
//    "BL      _write \n"       //original
    "BL      fwt_write\n"       //patch
    "LDR     R1, [R4, #4]\n"
    "CMP     R8, R0\n"
    "ADD     R1, R1, R0\n"
    "STR     R1, [R4, #4]\n"
    "BEQ     loc_FFDE6BC8\n"
    "CMN     R0, #1\n"
    "LDRNE   R0, =0x9200015\n"
    "LDREQ   R0, =0x9200005\n"
    "STR     R0, [R4, #0x10]\n"
    "B       loc_FFDE6B44\n"
"loc_FFDE6BC8:\n"
    "SUB     R5, R5, R0\n"
    "CMP     R5, R6\n"
    "ADD     R7, R7, R0\n"
    "LDRCS   R0, =0xFFDE67C4\n"
    "LDRCS   R1, =0x2CA\n"
    "BLCS    _DebugAssert \n"
    "CMP     R5, #0\n"
    "BNE     loc_FFDE6B68\n"
    "LDR     R0, [R4]\n"
    "MOV     R1, R4\n"
    "ADD     R0, R0, #1\n"
"loc_FFDE6BF4:\n"
    "LDMFD   SP!, {R4-R10,LR}\n"
    "B       sub_FFDE6498\n"
	);
}


//** sub_FFDE6558_my  @ 0xFFDE6558

void __attribute__((naked,noinline)) sub_FFDE6558_my(  ) { 
asm volatile (
    "STMFD   SP!, {R4-R6,LR}\n"
    "LDR     R5, =0x8428\n"
    "MOV     R4, R0\n"
    "LDR     R0, [R5]\n"
    "SUB     SP, SP, #0x38\n"
    "CMN     R0, #1\n"
//    "BEQ     loc_FFDE65A0\n"  //original
    "LDREQ PC, =0xFFDE65A0\n"   //patch
    "LDR     R1, [R4, #8]\n"
    "LDR     R6, =0x9200003\n"
    "TST     R1, #0x8000\n"
    "BEQ     loc_FFDE658C\n"
    "BL      sub_FFC4E7A4\n"
    "B       loc_FFDE6590\n"
"loc_FFDE658C:\n"
//    "BL      _Close \n"       //original
    "BL      fwt_close\n"       //patch
"loc_FFDE6590:\n"
    "LDR PC, =0xFFDE6590\n"     //+ jump back to ROM
/*    "CMP     R0, #0\n"
    "MVN     R0, #0\n"
    "STRNE   R6, [R4, #0x10]\n"
    "STR     R0, [R5]\n"
"loc_FFDE65A0:\n"
    "LDR     R0, [R4, #0x10]\n"
    "TST     R0, #1\n"
    "BNE     loc_FFDE669C\n"
    "LDR     R0, [R4, #8]\n"
    "TST     R0, #8\n"
    "BEQ     loc_FFDE65E8\n"
    "ADD     R1, SP, #0x20\n"
    "ADD     R0, R4, #0x38\n"
    "BL      sub_FFC4EEB4\n"
    "CMP     R0, #0\n"
    "LDREQ   R1, =0x305\n"
    "LDREQ   R0, =0xFFDE67C4\n"
    "BLEQ    _DebugAssert \n"
    "LDR     R0, [SP, #0x28]\n"
    "LDR     R1, [R4, #4]\n"
    "ADD     R0, R0, R1\n"
    "STR     R0, [SP, #0x28]\n"
    "B       loc_FFDE6618\n"
"loc_FFDE65E8:\n"
    "LDR     R0, =0x81FF\n"
    "STR     R0, [SP, #0x20]\n"
    "MOV     R0, #0x20\n"
    "STR     R0, [SP, #0x24]\n"
    "LDR     R0, [R4, #4]\n"
    "STR     R0, [SP, #0x28]\n"
    "LDR     R0, [R4, #0xC]\n"
    "STR     R0, [SP, #0x2C]\n"
    "LDR     R0, [R4, #0xC]\n"
    "STR     R0, [SP, #0x30]\n"
    "LDR     R0, [R4, #0xC]\n"
    "STR     R0, [SP, #0x34]\n"
"loc_FFDE6618:\n"
    "LDR     R0, [R4, #0x34]\n"
    "CMP     R0, #2\n"
    "BEQ     loc_FFDE669C\n"
    "ADD     R1, SP, #0x20\n"
    "ADD     R0, R4, #0x38\n"
    "BL      sub_FFC4F068\n"
    "LDR     R0, [R4, #0x34]\n"
    "CMP     R0, #1\n"
    "BNE     loc_FFDE669C\n"
    "MOV     R2, #0x20\n"
    "ADD     R1, R4, #0x38\n"
    "MOV     R0, SP\n"
    "BL      sub_FFE80F78\n"
    "MOV     R0, SP\n"
    "BL      _strlen \n"
    "MOV     R2, #0x54\n"
    "ADD     R0, SP, R0\n"
    "MOV     R1, #0x4D\n"
    "STRB    R2, [R0, #-3]\n"
    "STRB    R1, [R0, #-2]\n"
    "MOV     R1, #0x50\n"
    "STRB    R1, [R0, #-1]\n"
    "MOV     R1, SP\n"
    "ADD     R0, R4, #0x38\n"
    "BL      sub_FFC4E7C4\n"
    "CMP     R0, #0\n"
    "LDREQ   R1, =0x159\n"
    "LDREQ   R0, =0xFFDE67C4\n"
    "BLEQ    _DebugAssert \n"
    "MOV     R0, SP\n"
    "BL      sub_FFC4F4C4\n"
    "ADD     R0, R4, #0x38\n"
    "BL      sub_FFC4F4C4\n"
"loc_FFDE669C:\n"
    "LDR     R0, [R5, #0x18]\n"
    "CMP     R0, #0\n"
    "BLXNE   R0\n"
    "ADD     R0, R4, #0x38\n"
    "BL      sub_FFC514AC\n"
    "BL      sub_FFC4F748\n"
    "LDR     R1, [R5, #0x14]\n"
    "CMP     R1, #0\n"
    "LDRNE   R0, [R4, #0x10]\n"
    "BLXNE   R1\n"
    "ADD     SP, SP, #0x38\n"
    "LDMFD   SP!, {R4-R6,PC}\n"*/
	);
}
