/*
 * movie_rec.c - auto-generated by CHDK code_gen.
 */
#include "conf.h"

static int bitrate_multiplier = 4; // unit: factory rate / 4
static int bitrate_changed = 0;
extern int video_target_framesize;
extern int video_target_framesize2;


static int orig_bitrate[2]; // original bitrates, saved at beginning of recording

void change_video_tables(int a, int b) {
    bitrate_multiplier = (a<<2)/b;
    bitrate_changed = 1;
}

// firmware: -12 (best) ... +20 (worst)
void  set_quality(int *x){ // -17 highest; +12 lowest
 if (conf.video_mode) *x=12-((conf.video_quality-1)*(12+17)/(99-1));
}

void save_original_bitrates() {
    orig_bitrate[0] = video_target_framesize;
    orig_bitrate[1] = video_target_framesize2;
    bitrate_changed = 1;
}

void modify_bitrate() {
    if (bitrate_changed) {
        bitrate_changed = 0;
        video_target_framesize = (orig_bitrate[0] * bitrate_multiplier) >> 2;
        video_target_framesize2 = (orig_bitrate[1] * bitrate_multiplier) >> 2;
    }
}


/*************************************************************/
//** movie_record_task @ 0xFF9A96DC - 0xFF9A986C, length=101
void __attribute__((naked,noinline)) movie_record_task() {
asm volatile (
"    STMFD   SP!, {R2-R10,LR} \n"
"    LDR     R8, =0xFF9A92DC \n"
"    LDR     R4, =0x7248 \n"
"    LDR     R9, =0x549 \n"
"    LDR     R10, =0x2710 \n"
"    MVN     R7, #0 \n"
"    MOV     R5, #1 \n"
"    MOV     R6, #0 \n"

"loc_FF9A96FC:\n"
"    LDR     R0, [R4, #0x30] \n"
"    MOV     R2, #0 \n"
"    ADD     R1, SP, #4 \n"
"    BL      sub_006B8568 /*_ReceiveMessageQueue*/ \n"
"    LDR     R0, [R4, #0x38] \n"
"    CMP     R0, #0 \n"
"    LDRNE   R0, [R4, #0x14] \n"
"    CMPNE   R0, #2 \n"
"    LDRNE   R0, [R4, #0x4C] \n"
"    CMPNE   R0, #6 \n"
"    BNE     loc_FF9A9850 \n"
"    LDR     R0, [SP, #4] \n"
"    LDR     R1, [R0] \n"
"    SUB     R1, R1, #2 \n"
"    CMP     R1, #0xD \n"
"    ADDCC   PC, PC, R1, LSL#2 \n"
"    B       loc_FF9A9850 \n"
"    B       loc_FF9A97C4 \n"
"    B       loc_FF9A97F0 \n"
"    B       loc_FF9A9800 \n"
"    B       loc_FF9A9808 \n"
"    B       loc_FF9A97CC \n"
"    B       loc_FF9A9810 \n"
"    B       loc_FF9A983C \n"
"    B       loc_FF9A9844 \n"
"    B       loc_FF9A97D8 \n"
"    B       loc_FF9A9850 \n"
"    B       loc_FF9A984C \n"
"    B       loc_FF9A97A0 \n"
"    B       loc_FF9A9774 \n"

"loc_FF9A9774:\n"
"    STR     R6, [R4, #0x48] \n"
"    STR     R6, [R4, #0x3C] \n"
"    STR     R7, [R4, #0xD4] \n"
"    STRH    R6, [R4, #8] \n"
"    STR     R8, [R4, #0xB4] \n"
"    LDR     R0, [R4, #0x14] \n"
"    ADD     R0, R0, #1 \n"
"    STR     R0, [R4, #0x14] \n"
"    MOV     R0, #6 \n"
"    STR     R0, [R4, #0x4C] \n"
"    B       loc_FF9A97BC \n"

"loc_FF9A97A0:\n"
"    STR     R6, [R4, #0x48] \n"
"    STR     R7, [R4, #0xD4] \n"
"    STR     R8, [R4, #0xB4] \n"
"    LDR     R0, [R4, #0x14] \n"
"    ADD     R0, R0, #1 \n"
"    STR     R0, [R4, #0x14] \n"
"    STR     R5, [R4, #0x4C] \n"

"loc_FF9A97BC:\n"
"    STR     R5, [R4, #0xC] \n"
"    B       loc_FF9A9850 \n"

"loc_FF9A97C4:\n"
"    BL      sub_FF9A8FB4 \n"
"    B       loc_FF9A9850 \n"

"loc_FF9A97CC:\n"
"    LDR     R1, [R4, #0xB4] \n"
"    BLX     R1 \n"
//begin patch
"    LDR     R0, =video_compression_rate \n" // added
"    BL      set_quality \n"                 // added
//end patch
"    B       loc_FF9A9850 \n"

"loc_FF9A97D8:\n"
"    LDR     R1, [R0, #0x18] \n"
"    LDR     R2, [R0, #0x28] \n"
"    LDR     R3, [R0, #0x24] \n"
"    LDR     R0, [R0, #4] \n"
"    BL      sub_FFAE37B0 \n"
"    B       loc_FF9A9850 \n"

"loc_FF9A97F0:\n"
"    LDR     R0, [R4, #0x4C] \n"
"    CMP     R0, #5 \n"
"    STRNE   R5, [R4, #0x3C] \n"
"    B       loc_FF9A9850 \n"

"loc_FF9A9800:\n"
"    BL      sub_FF9A8C24 \n"
"    B       loc_FF9A9850 \n"

"loc_FF9A9808:\n"
"    BL      sub_FF9A8AE4 \n"
"    B       loc_FF9A9850 \n"

"loc_FF9A9810:\n"
"    LDR     R0, =0xD0C3C \n"
"    LDR     R0, [R0, #8] \n"
"    CMP     R0, #0 \n"
"    LDRNE   R2, =0xFF9A8A04 \n"
"    LDRNE   R0, =0xFF9A8A8C \n"
"    MOVNE   R3, #0 \n"
"    MOVNE   R1, R3 \n"
"    BLNE    sub_FF86F174 \n"
"    MOV     R0, #3 \n"
"    STR     R0, [R4, #0x4C] \n"
"    B       loc_FF9A9850 \n"

"loc_FF9A983C:\n"
"    BL      sub_FF9A8978 \n"
"    B       loc_FF9A9850 \n"

"loc_FF9A9844:\n"
"    BL      sub_FF9AA050 \n"
"    B       loc_FF9A9850 \n"

"loc_FF9A984C:\n"
"    BL      sub_FF9A8854 \n"

"loc_FF9A9850:\n"
"    LDR     R1, [SP, #4] \n"
"    LDR     R3, =0xFF9A8548 /*'MovieRecorder.c'*/ \n"
"    STR     R6, [R1] \n"
"    STR     R9, [SP] \n"
"    LDR     R0, [R4, #0x34] \n"
"    MOV     R2, R10 \n"
"    BL      sub_006B7E04 /*_PostMessageQueueStrictly*/ \n"
"    B       loc_FF9A96FC \n"
);
}
