#include "stubs_asm.h"

DEF(led_table, 0x11258) //OK
DEF(physw_run, 0x1FBC) //OK
DEF(physw_status, 0x10FF0) //OK
DEF(canon_menu_active,0x8B5C) //OK


DEF(zoom_busy, 0x89178)
DEF(zoom_status, 0x7df0)


DEF(focus_busy, 0x89490) 






DEF(canon_shoot_menu_active,0x7ef4+1) // not checked
DEF(recreview_hold,     0x00086400)
DEF(some_f_for_dng,     0x000099d4)
DEF(second_ext_for_dng, 0x000099f8)
DEF(movie_status,       0x0007c98c)


DEF(playrec_mode, 0x6DA0) // "MenuIn"

DEF(sys_mempart_id, 0xea18)
