/*
 * capt_seq.c - auto-generated by CHDK code_gen.
 */
#include "lolevel.h"
#include "platform.h"
#include "core.h"

static long *nrflag = (long*)0x61B0;

#include "../../../generic/capt_seq.c"

/*************************************************************/
//** capt_seq_task @ 0xFF95ECE8 - 0xFF95EE94, length=108
void __attribute__((naked,noinline)) capt_seq_task() {
asm volatile (
"    STMFD   SP!, {R4,LR} \n"
"    SUB     SP, SP, #4 \n"
"    MOV     R4, SP \n"
"    B       loc_FF95EE60 \n"

"loc_FF95ECF8:\n"
"    LDR     R2, [SP] \n"
"    LDR     R3, [R2] \n"
"    MOV     R0, R2 \n"
"    CMP     R3, #0x14 \n"
"    LDRLS   PC, [PC, R3, LSL#2] \n"
"    B       loc_FF95EE34 \n"
"    .long   loc_FF95ED64 \n"
"    .long   loc_FF95ED84 \n"
"    .long   loc_FF95ED98 \n"
"    .long   loc_FF95EDA8 \n"
"    .long   loc_FF95EDA0 \n"
"    .long   loc_FF95EDB0 \n"
"    .long   loc_FF95EDB8 \n"
"    .long   loc_FF95EDC4 \n"
"    .long   loc_FF95EDCC \n"
"    .long   loc_FF95EDD8 \n"
"    .long   loc_FF95EDE0 \n"
"    .long   loc_FF95EDE8 \n"
"    .long   loc_FF95EDF0 \n"
"    .long   loc_FF95EDF8 \n"
"    .long   loc_FF95EE00 \n"
"    .long   loc_FF95EE0C \n"
"    .long   loc_FF95EE14 \n"
"    .long   loc_FF95EE1C \n"
"    .long   loc_FF95EE24 \n"
"    .long   loc_FF95EE2C \n"
"    .long   loc_FF95EE48 \n"

"loc_FF95ED64:\n"
"    BL      sub_FF96073C \n"

// only do quick press hack if overrides are active
"    BL      captseq_hack_override_active\n" // returns 1 if tv or sv override in effect
"    STR     R2, [SP,#-4]!\n" // push return value
"    BL      shooting_expo_param_override\n"   // +

"    BL      sub_FF95CA68 \n"
"    LDR     R3, =0x99F00 \n"

"    LDR     R2, [SP], #4\n" // pop override hack
"    CMP     R2, #1\n"     // +
"    MOVEQ   R2, #0\n"     // +
"    STREQ   R2, [R3, #0x24]\n"  // fixes overrides behavior at short shutter press
"    LDRNE   R2, [R3, #0x24]\n" // modified NE
"    CMPNE   R2, #0\n"         // modified NE

//"  LDR     R2, [R3, #0x24] \n"  // above patch makes these lines redundant
//"  CMP     R2, #0 \n"
"    BEQ     loc_FF95EE44 \n"
"    BL      sub_FF95E944_my \n"  // --> Patched. Old value = 0xFF95E944.
"    B       loc_FF95EE44 \n"

"loc_FF95ED84:\n"
"    BL      sub_FF95E860_my \n"  // --> Patched. Old value = 0xFF95E860.

"loc_FF95ED88:\n"
"    LDR     R2, =0x99F00 \n"
"    MOV     R3, #0 \n"
"    STR     R3, [R2, #0x24] \n"
"    B       loc_FF95EE44 \n"

"loc_FF95ED98:\n"
"    BL      sub_FF960ACC \n"
"    B       loc_FF95EE44 \n"

"loc_FF95EDA0:\n"
"    BL      sub_FF95F934 \n"
"    B       loc_FF95ED88 \n"

"loc_FF95EDA8:\n"
"    BL      sub_FF95FCD0 \n"
"    B       loc_FF95ED88 \n"

"loc_FF95EDB0:\n"
"    BL      sub_FF95FCE0 \n"
"    B       loc_FF95EE44 \n"

"loc_FF95EDB8:\n"
"    BL      sub_FF960820 \n"
"    BL      sub_FF95CA68 \n"
"    B       loc_FF95EE44 \n"

"loc_FF95EDC4:\n"
"    BL      sub_FF95EA18 \n"
"    B       loc_FF95EE44 \n"

"loc_FF95EDCC:\n"
"    BL      sub_FF960888 \n"
"    BL      sub_FF95CA68 \n"
"    B       loc_FF95EE44 \n"

"loc_FF95EDD8:\n"
"    BL      sub_FF95FCD0 \n"
"    B       loc_FF95EE44 \n"

"loc_FF95EDE0:\n"
"    BL      sub_FF961020 \n"
"    B       loc_FF95EE44 \n"

"loc_FF95EDE8:\n"
"    BL      sub_FF961364 \n"
"    B       loc_FF95EE44 \n"

"loc_FF95EDF0:\n"
"    BL      sub_FF9613E8 \n"
"    B       loc_FF95EE44 \n"

"loc_FF95EDF8:\n"
"    BL      sub_FF9614D8 \n"
"    B       loc_FF95EE44 \n"

"loc_FF95EE00:\n"
"    MOV     R0, #0 \n"
"    BL      sub_FF9615A0 \n"
"    B       loc_FF95EE44 \n"

"loc_FF95EE0C:\n"
"    BL      sub_FF96170C \n"
"    B       loc_FF95EE44 \n"

"loc_FF95EE14:\n"
"    BL      sub_FF9617A0 \n"
"    B       loc_FF95EE44 \n"

"loc_FF95EE1C:\n"
"    BL      sub_FF96185C \n"
"    B       loc_FF95EE44 \n"

"loc_FF95EE24:\n"
"    BL      sub_FF961948 \n"
"    B       loc_FF95EE44 \n"

"loc_FF95EE2C:\n"
"    BL      sub_FF96199C \n"
"    B       loc_FF95EE44 \n"

"loc_FF95EE34:\n"
"    MOV     R1, #0x36C \n"
"    LDR     R0, =0xFF95E5EC /*'ShootTask.c'*/ \n"
"    ADD     R1, R1, #1 \n"
"    BL      _DebugAssert \n"

"loc_FF95EE44:\n"
"    LDR     R2, [SP] \n"

"loc_FF95EE48:\n"
"    LDR     R3, =0x6F274 \n"
"    LDR     R1, [R2, #4] \n"
"    LDR     R0, [R3] \n"
"    BL      sub_FF81FD68 /*_SetEventFlag*/ \n"
"    LDR     R0, [SP] \n"
"    BL      sub_FF95E668 \n"

"loc_FF95EE60:\n"
"    LDR     R3, =0x6F278 \n"
"    MOV     R1, R4 \n"
"    LDR     R0, [R3] \n"
"    MOV     R2, #0 \n"
"    BL      sub_FF820480 /*_ReceiveMessageQueue*/ \n"
"    TST     R0, #1 \n"
"    BEQ     loc_FF95ECF8 \n"
"    MOV     R1, #0x2A4 \n"
"    LDR     R0, =0xFF95E5EC /*'ShootTask.c'*/ \n"
"    ADD     R1, R1, #3 \n"
"    BL      _DebugAssert \n"
"    BL      _ExitTask \n"
"    ADD     SP, SP, #4 \n"
"    LDMFD   SP!, {R4,PC} \n"
);
}

/*************************************************************/
//** sub_FF95E944_my @ 0xFF95E944 - 0xFF95EA10, length=52
void __attribute__((naked,noinline)) sub_FF95E944_my() {
asm volatile (
"    STR     LR, [SP, #-4]! \n"
"    LDR     R3, =0x99F00 \n"
"    LDR     R2, [R3, #0x24] \n"
"    CMP     R2, #0 \n"
"    MOV     R0, #0xC \n"
"    BEQ     loc_FF95E968 \n"
"    BL      sub_FF967048 \n"
"    TST     R0, #1 \n"
"    BNE     loc_FF95E990 \n"

"loc_FF95E968:\n"
"    BL      sub_FF99FE38 \n"
"    BL      sub_FF824ADC \n"
"    LDR     R3, =0x99E40 \n"
"    STR     R0, [R3, #4] \n"
"    MOV     R0, #0 \n"
"    BL      sub_FF96248C \n"
"    MOV     R0, #0 \n"
"    BL      sub_FF961D20_my \n"  // --> Patched. Old value = 0xFF961D20.
"    BL      capt_seq_hook_raw_here\n"   // +
"    TST     R0, #1 \n"
"    LDREQ   PC, [SP], #4 \n"

"loc_FF95E990:\n"
"    LDR     R3, =0x619C \n"
"    MOV     R2, #1 \n"
"    STR     R2, [R3] \n"
"    LDR     PC, [SP], #4 \n"

"loc_FF95E9D8:\n"
"    MOV     R0, #0 \n"
"    LDR     PC, [SP], #4 \n"

"loc_FF95EA0C:\n"
"    MOV     R0, #0 \n"
"    LDR     PC, [SP], #4 \n"
);
}

/*************************************************************/
//** sub_FF95E860_my @ 0xFF95E860 - 0xFF95E934, length=54
void __attribute__((naked,noinline)) sub_FF95E860_my() {
asm volatile (
"    STMFD   SP!, {R4,R5,LR} \n"
"    LDR     R4, [R0, #0xC] \n"
"    BL      sub_FF967028 \n"
"    CMP     R0, #0 \n"
"    BNE     loc_FF95E878 \n"
"    BL      sub_FF967034 \n"

"loc_FF95E878:\n"
"    LDR     R3, =0x99F00 \n"
"    LDR     R2, [R3, #0x24] \n"
"    CMP     R2, #0 \n"
"    BNE     loc_FF95E8AC \n"
"    MOV     R0, #0xC \n"
"    BL      sub_FF967048 \n"
"    TST     R0, #1 \n"
"    BEQ     loc_FF95E8AC \n"
"    MOV     R0, #1 \n"

"loc_FF95E89C:\n"
"    MOV     R2, R4 \n"
"    MOV     R1, #1 \n"
"    LDMFD   SP!, {R4,R5,LR} \n"
"    B       sub_FF95CF48 \n"

"loc_FF95E8AC:\n"
"    LDR     R5, =0x99F00 \n"
"    LDR     R3, [R5, #0x24] \n"
"    CMP     R3, #0 \n"
"    BNE     loc_FF95E8C8 \n"
"    MOV     R0, #2 \n"
"    BL      sub_FFAB8A90 \n"
"    LDR     R3, [R5, #0x24] \n"

"loc_FF95E8C8:\n"
"    CMP     R3, #0 \n"
"    BNE     loc_FF95E910 \n"
"    MOV     R0, R4 \n"
"    BL      sub_FF960ADC \n"
"    TST     R0, #1 \n"
"    BNE     loc_FF95E89C \n"
"    BL      sub_FF99FE38 \n"
"    BL      sub_FF824ADC \n"
"    LDR     R2, =0x99E44 \n"
"    ADD     R3, R4, R4, LSL#1 \n"
"    STR     R0, [R2, R3, LSL#5] \n"
"    MOV     R0, R4 \n"
"    BL      sub_FF96248C \n"
"    BL      sub_FF960FE0 \n"
"    BL      sub_FF960F7C \n"
"    MOV     R0, R4 \n"
"    BL      sub_FF961D20_my \n"  // --> Patched. Old value = 0xFF961D20.
"    BL      capt_seq_hook_raw_here\n"   // +
"    B       loc_FF95E924 \n"

"loc_FF95E910:\n"
"    LDR     R3, =0x619C \n"
"    LDR     R2, [R3] \n"
"    CMP     R2, #0 \n"
"    MOVNE   R0, #0x1D \n"
"    MOVEQ   R0, #0 \n"

"loc_FF95E924:\n"
"    MOV     R2, R4 \n"
"    MOV     R1, #1 \n"
"    BL      sub_FF95CF48 \n"
"    LDMFD   SP!, {R4,R5,LR} \n"
"    B       sub_FF961F18 \n"
);
}

/*************************************************************/
//** sub_FF961D20_my @ 0xFF961D20 - 0xFF961D4C, length=12
void __attribute__((naked,noinline)) sub_FF961D20_my() {
asm volatile (
"    STMFD   SP!, {R4-R6,LR} \n"
"    LDR     R3, =0x6F2EC \n"
"    LDR     R5, =0x61AC \n"
"    SUB     SP, SP, #4 \n"
"    MVN     R1, #0 \n"
"    STR     R0, [R5] \n"
"    LDR     R0, [R3] \n"
"    BL      sub_FF81FF04 /*_ClearEventFlag*/ \n"
"    LDR     R3, =0x99F00 \n"
"    LDR     R0, [R3, #0x7C] \n"
"    BL      sub_FF89E028 \n"
"    BL      sub_FF961C74 \n"
"    BL      wait_until_remote_button_is_released\n"
"    BL      capt_seq_hook_set_nr\n"
"    LDR     PC, =0xFF961D50 \n"  // Continue in firmware
);
}

/*************************************************************/
//** exp_drv_task @ 0xFF9064CC - 0xFF90690C, length=273
void __attribute__((naked,noinline)) exp_drv_task() {
asm volatile (
"    STMFD   SP!, {R4-R8,LR} \n"
"    SUB     SP, SP, #0x14 \n"
"    MOV     R7, SP \n"
"    B       loc_FF9068C8 \n"

"loc_FF9064DC:\n"
"    CMP     R2, #0x1F \n"
"    BNE     loc_FF9064F4 \n"
"    LDR     R0, [R12, #0x50] \n"
"    MOV     LR, PC \n"
"    LDR     PC, [R12, #0x4C] \n"
"    B       loc_FF906554 \n"

"loc_FF9064F4:\n"
"    CMP     R2, #0x1A \n"
"    BNE     loc_FF906508 \n"
"    MOV     R0, R12 \n"
"    BL      sub_FF9063FC \n"
"    B       loc_FF906544 \n"

"loc_FF906508:\n"
"    CMP     R2, #0x1B \n"
"    BNE     loc_FF90651C \n"
"    MOV     R0, R12 \n"
"    BL      sub_FF906438 \n"
"    B       loc_FF906544 \n"

"loc_FF90651C:\n"
"    SUB     R3, R2, #0x1C \n"
"    CMP     R3, #1 \n"
"    BHI     loc_FF906534 \n"
"    MOV     R0, R12 \n"
"    BL      sub_FF906474 \n"
"    B       loc_FF906544 \n"

"loc_FF906534:\n"
"    CMP     R2, #0x1E \n"
"    BNE     loc_FF906560 \n"
"    BL      sub_FF8B102C \n"
"    BL      sub_FF8B2E1C \n"

"loc_FF906544:\n"
"    LDR     R3, [SP] \n"
"    LDR     R0, [R3, #0x50] \n"
"    MOV     LR, PC \n"
"    LDR     PC, [R3, #0x4C] \n"

"loc_FF906554:\n"
"    LDR     R0, [SP] \n"
"    BL      sub_FF9041BC \n"
"    B       loc_FF9068C8 \n"

"loc_FF906560:\n"
"    CMP     R2, #0xD \n"
"    MOV     R8, #1 \n"
"    BNE     loc_FF9065D0 \n"
"    LDR     R1, [R12, #0x40] \n"
"    ADD     R1, R1, R1, LSL#1 \n"
"    ADD     R1, R12, R1, LSL#1 \n"
"    ADD     R6, SP, #0xC \n"
"    SUB     R1, R1, #2 \n"
"    MOV     R2, #6 \n"
"    MOV     R0, R6 \n"
"    BL      _memcpy \n"
"    LDR     R0, [SP] \n"
"    BL      sub_FF90568C \n"
"    LDR     R3, [SP] \n"
"    LDR     R1, [R3, #0x40] \n"
"    LDR     R2, [R3, #0x50] \n"
"    ADD     R0, R3, #4 \n"
"    MOV     LR, PC \n"
"    LDR     PC, [R3, #0x4C] \n"
"    LDR     R0, [SP] \n"
"    BL      sub_FF905810 \n"
"    LDR     R3, [SP] \n"
"    ADD     R0, R3, #4 \n"
"    LDR     R1, [R3, #0x40] \n"
"    LDR     R2, [R3, #0x58] \n"
"    MOV     LR, PC \n"
"    LDR     PC, [R3, #0x54] \n"
"    B       loc_FF906878 \n"

"loc_FF9065D0:\n"
"    SUB     R3, R2, #0xE \n"
"    CMP     R3, #1 \n"
"    BHI     loc_FF90668C \n"
"    ADD     R6, SP, #0xC \n"
"    ADD     R5, SP, #4 \n"
"    MOV     R0, R12 \n"
"    MOV     R1, R6 \n"
"    MOV     R2, R5 \n"
"    BL      sub_FF90588C \n"
"    MOV     R4, R0 \n"
"    CMP     R4, #5 \n"
"    CMPNE   R4, #1 \n"
"    BNE     loc_FF906624 \n"
"    LDR     R12, [SP] \n"
"    MOV     R0, R5 \n"
"    LDR     R1, [R12, #0x40] \n"
"    MOV     R2, R4 \n"
"    LDR     R3, [R12, #0x50] \n"
"    MOV     LR, PC \n"
"    LDR     PC, [R12, #0x4C] \n"
"    B       loc_FF90665C \n"

"loc_FF906624:\n"
"    CMP     R4, #6 \n"
"    CMPNE   R4, #2 \n"
"    BNE     loc_FF90666C \n"
"    LDR     R12, [SP] \n"
"    MOV     R0, R5 \n"
"    MOV     R1, R8 \n"
"    MOV     R2, R4 \n"
"    LDR     R3, [R12, #0x50] \n"
"    MOV     LR, PC \n"
"    LDR     PC, [R12, #0x4C] \n"
"    MOV     R1, R6 \n"
"    LDR     R0, [SP] \n"
"    MOV     R2, R5 \n"
"    BL      sub_FF906238 \n"

"loc_FF90665C:\n"
"    MOV     R1, R4 \n"
"    LDR     R0, [SP] \n"
"    BL      sub_FF9063DC \n"
"    B       loc_FF906878 \n"

"loc_FF90666C:\n"
"    LDR     R12, [SP] \n"
"    MOV     R2, R4 \n"
"    ADD     R0, R12, #4 \n"
"    LDR     R1, [R12, #0x40] \n"
"    LDR     R3, [R12, #0x50] \n"
"    MOV     LR, PC \n"
"    LDR     PC, [R12, #0x4C] \n"
"    B       loc_FF906878 \n"

"loc_FF90668C:\n"
"    SUB     R3, R2, #0x17 \n"
"    CMP     R3, #1 \n"
"    BHI     loc_FF9066E4 \n"
"    LDR     R1, [R12, #0x40] \n"
"    ADD     R1, R1, R1, LSL#1 \n"
"    ADD     R1, R12, R1, LSL#1 \n"
"    ADD     R6, SP, #0xC \n"
"    SUB     R1, R1, #2 \n"
"    MOV     R2, #6 \n"
"    MOV     R0, R6 \n"
"    BL      _memcpy \n"
"    LDR     R0, [SP] \n"
"    BL      sub_FF9051C0 \n"
"    LDR     R3, [SP] \n"
"    ADD     R0, R3, #4 \n"
"    LDR     R1, [R3, #0x40] \n"
"    LDR     R2, [R3, #0x50] \n"
"    MOV     LR, PC \n"
"    LDR     PC, [R3, #0x4C] \n"
"    LDR     R0, [SP] \n"
"    BL      sub_FF905390 \n"
"    B       loc_FF906878 \n"

"loc_FF9066E4:\n"
"    ADD     R6, SP, #0xC \n"
"    ADD     R1, R12, #4 \n"
"    MOV     R2, #6 \n"
"    MOV     R0, R6 \n"
"    BL      _memcpy \n"
"    LDR     R12, [SP] \n"
"    LDR     R3, [R12] \n"
"    MOV     R2, R12 \n"
"    CMP     R3, #0x19 \n"
"    LDRLS   PC, [PC, R3, LSL#2] \n"
"    B       loc_FF906864 \n"
"    .long   loc_FF906778 \n"
"    .long   loc_FF906784 \n"
"    .long   loc_FF906790 \n"
"    .long   loc_FF906790 \n"
"    .long   loc_FF906778 \n"
"    .long   loc_FF906784 \n"
"    .long   loc_FF906790 \n"
"    .long   loc_FF906790 \n"
"    .long   loc_FF9067B4 \n"
"    .long   loc_FF9067B4 \n"
"    .long   loc_FF906838 \n"
"    .long   loc_FF906844 \n"
"    .long   loc_FF906854 \n"
"    .long   loc_FF906864 \n"
"    .long   loc_FF906864 \n"
"    .long   loc_FF906864 \n"
"    .long   loc_FF90679C \n"
"    .long   loc_FF9067A8 \n"
"    .long   loc_FF9067C4 \n"
"    .long   loc_FF9067D0 \n"
"    .long   loc_FF9067F8 \n"
"    .long   loc_FF906820 \n"
"    .long   loc_FF906820 \n"
"    .long   loc_FF906864 \n"
"    .long   loc_FF906864 \n"
"    .long   loc_FF90682C \n"

"loc_FF906778:\n"
"    MOV     R0, R2 \n"
"    BL      sub_FF904760 \n"
"    B       loc_FF906860 \n"

"loc_FF906784:\n"
"    MOV     R0, R2 \n"
"    BL      sub_FF90489C \n"
"    B       loc_FF906860 \n"

"loc_FF906790:\n"
"    MOV     R0, R2 \n"
"    BL      sub_FF9049CC \n"
"    B       loc_FF906860 \n"

"loc_FF90679C:\n"
"    MOV     R0, R2 \n"
"    BL      sub_FF904BA0 \n"
"    B       loc_FF906860 \n"

"loc_FF9067A8:\n"
"    MOV     R0, R2 \n"
"    BL      sub_FF904CA8 \n"
"    B       loc_FF906860 \n"

"loc_FF9067B4:\n"
"    MOV     R0, R2 \n"
"    BL      sub_FF904D6C_my \n"  // --> Patched. Old value = 0xFF904D6C.
"    MOV     R8, #0 \n"
"    B       loc_FF906860 \n"

"loc_FF9067C4:\n"
"    MOV     R0, R2 \n"
"    BL      sub_FF904E2C \n"
"    B       loc_FF906860 \n"

"loc_FF9067D0:\n"
"    MOV     R0, R2 \n"
"    LDRH    R2, [R2, #4] \n"
"    LDR     R3, =0x4A344 \n"
"    STRH    R2, [SP, #0xC] \n"
"    LDRH    R1, [R3, #4] \n"
"    STRH    R1, [SP, #0x10] \n"
"    LDRH    R3, [R3, #2] \n"
"    STRH    R3, [SP, #0xE] \n"
"    BL      sub_FF904FB4 \n"
"    B       loc_FF906860 \n"

"loc_FF9067F8:\n"
"    LDR     R3, =0x4A344 \n"
"    LDRH    R1, [R3] \n"
"    STRH    R1, [SP, #0xC] \n"
"    MOV     R0, R2 \n"
"    LDRH    R2, [R2, #6] \n"
"    STRH    R2, [SP, #0xE] \n"
"    LDRH    R3, [R3, #4] \n"
"    STRH    R3, [SP, #0x10] \n"
"    BL      sub_FF905048 \n"
"    B       loc_FF906860 \n"

"loc_FF906820:\n"
"    MOV     R0, R2 \n"
"    BL      sub_FF9050C8 \n"
"    B       loc_FF906860 \n"

"loc_FF90682C:\n"
"    MOV     R0, R2 \n"
"    BL      sub_FF905420 \n"
"    B       loc_FF906860 \n"

"loc_FF906838:\n"
"    MOV     R0, R2 \n"
"    BL      sub_FF9054F4 \n"
"    B       loc_FF906860 \n"

"loc_FF906844:\n"
"    MOV     R0, R2 \n"
"    MOV     R1, #0 \n"
"    BL      sub_FF9055E0 \n"
"    B       loc_FF906860 \n"

"loc_FF906854:\n"
"    MOV     R0, R2 \n"
"    MOV     R1, #1 \n"
"    BL      sub_FF9055E0 \n"

"loc_FF906860:\n"
"    LDR     R12, [SP] \n"

"loc_FF906864:\n"
"    ADD     R0, R12, #4 \n"
"    LDR     R1, [R12, #0x40] \n"
"    LDR     R2, [R12, #0x50] \n"
"    MOV     LR, PC \n"
"    LDR     PC, [R12, #0x4C] \n"

"loc_FF906878:\n"
"    CMP     R8, #1 \n"
"    BNE     loc_FF9068A0 \n"
"    LDR     R1, [SP] \n"
"    LDR     R3, [R1, #0x40] \n"
"    ADD     R3, R3, R3, LSL#1 \n"
"    ADD     R1, R1, R3, LSL#1 \n"
"    MOV     R0, R6 \n"
"    SUB     R1, R1, #2 \n"
"    BL      sub_FF9045D0 \n"
"    B       loc_FF9068C0 \n"

"loc_FF9068A0:\n"
"    MOV     R0, #1 \n"
"    MOV     R1, R0 \n"
"    MOV     R2, R0 \n"
"    BL      sub_FF904574 \n"
"    MOV     R0, #1 \n"
"    MOV     R1, R0 \n"
"    MOV     R2, R0 \n"
"    BL      sub_FF90468C \n"

"loc_FF9068C0:\n"
"    LDR     R0, [SP] \n"
"    BL      sub_FF9041BC \n"

"loc_FF9068C8:\n"
"    LDR     R3, =0x4A33C \n"
"    MOV     R2, #0 \n"
"    LDR     R0, [R3] \n"
"    MOV     R1, R7 \n"
"    BL      sub_FF820480 /*_ReceiveMessageQueue*/ \n"
"    LDR     R12, [SP] \n"
"    LDR     R2, [R12] \n"
"    CMP     R2, #0x20 \n"
"    BNE     loc_FF9064DC \n"
"    MOV     R0, R12 \n"
"    BL      sub_FF9041BC \n"
"    LDR     R3, =0x4A338 \n"
"    MOV     R1, #1 \n"
"    LDR     R0, [R3] \n"
"    BL      sub_FF81FD68 /*_SetEventFlag*/ \n"
"    BL      _ExitTask \n"
"    ADD     SP, SP, #0x14 \n"
"    LDMFD   SP!, {R4-R8,PC} \n"
);
}

/*************************************************************/
//** sub_FF904D6C_my @ 0xFF904D6C - 0xFF904E1C, length=45
void __attribute__((naked,noinline)) sub_FF904D6C_my() {
asm volatile (
"    STMFD   SP!, {R4,R5,LR} \n"
"    LDR     R3, =0x4A338 \n"
"    MOV     R4, R0 \n"
"    MOV     R1, #0xE \n"
"    LDR     R0, [R3] \n"
"    BL      sub_FF81FF04 /*_ClearEventFlag*/ \n"
"    MOV     R1, #0 \n"
"    LDRSH   R0, [R4, #4] \n"
"    BL      sub_FF904298 \n"
"    MOV     R5, R0 \n"
"    LDRSH   R0, [R4, #6] \n"
"    BL      sub_FF90440C \n"
"    LDRSH   R0, [R4, #8] \n"
"    BL      sub_FF9044A8 \n"
"    LDR     R3, [R4] \n"
"    CMP     R3, #9 \n"
"    MOVEQ   R5, #0 \n"
"    CMP     R5, #1 \n"
"    LDR     R1, =0xFF9041F0 \n"
"    MOV     R2, #2 \n"
"    BNE     loc_FF904DD8 \n"
"    LDRSH   R0, [R4, #4] \n"
"    BL      sub_FFAAC288 \n"
"    LDR     R2, =0x4A364 \n"
"    MOV     R3, #0 \n"
"    STR     R3, [R2] \n"
"    B       loc_FF904DDC \n"

"loc_FF904DD8:\n"
"    BL      sub_FF904544 \n"

"loc_FF904DDC:\n"
"    STRH    R0, [R4, #4] \n"
"    LDRSH   R0, [R4, #6] \n"
"    BL      sub_FF8B0CB4_my \n"  // --> Patched. Old value = 0xFF8B0CB4.
"    LDRSH   R0, [R4, #8] \n"
"    MOV     R1, #1 \n"
"    BL      sub_FF8B29DC \n"
"    MOV     R1, #0 \n"
"    ADD     R0, R4, #8 \n"
"    BL      sub_FF8B2A9C \n"
"    CMP     R5, #1 \n"
"    MOV     R1, #2 \n"
"    MOV     R2, #0 \n"
"    LDMNEFD SP!, {R4,R5,PC} \n"
"    LDR     R3, =0x4A338 \n"
"    LDR     R0, [R3] \n"
"    LDMFD   SP!, {R4,R5,LR} \n"
"    B       sub_FF81FD58 /*_WaitForAllEventFlag*/ \n"
);
}

/*************************************************************/
//** sub_FF8B0CB4_my @ 0xFF8B0CB4 - 0xFF8B0D10, length=24
void __attribute__((naked,noinline)) sub_FF8B0CB4_my() {
asm volatile (
"    STMFD   SP!, {R4,LR} \n"
"    LDR     R3, =0x531C \n"
"    LDR     R2, [R3] \n"
"    MOV     R1, #0x114 \n"
"    MOV     R3, R0, LSL#16 \n"
"    CMP     R2, #1 \n"
"    ADD     R1, R1, #1 \n"
"    LDR     R0, =0xFF8B0730 /*'Shutter.c'*/ \n"
"    MOV     R4, R3, ASR#16 \n"
"    BEQ     loc_FF8B0CE0 \n"
"    BL      _DebugAssert \n"

"loc_FF8B0CE0:\n"
"    MOV     R1, #0x118 \n"
"    CMN     R4, #0xC00 \n"
"    LDR     R3, =0x3D19E \n"
"    LDR     R0, =0xFF8B0730 /*'Shutter.c'*/ \n"
"    ADD     R1, R1, #3 \n"
"    LDREQSH R4, [R3] \n"
"    LDRNE   R3, =0x3D19E \n"
"    CMN     R4, #0xC00 \n"
"    STRH    R4, [R3] \n"
"    BNE     loc_FF8B0D0C \n"
"    BL      _DebugAssert \n"

"loc_FF8B0D0C:\n"
"    MOV     R0, R4 \n"
"    BL      apex2us \n"  // --> Patched. Old value = _apex2us.
"    LDR     PC, =0xFF8B0D14 \n"  // Continue in firmware
);
}
