PLATFORMID=12937
PLATFORMOS=dryos
PLATFORMOSVER=54

# address where wif or diskboot code will be loaded by camera
MEMBASEADDR=0x1900

# start of firmware
ROMBASEADDR=0xff010000

# points to the start of the memory pool used by the firmware
MEMISOSTART = 0x002bebfc

# type of FI2 encoding
KEYSYS = d4f
# type of diskboot encoding
NEED_ENCODED_DISKBOOT = 12

