PLATFORMID=12993
PLATFORMOS=dryos
PLATFORMOSVER=58

# address where wif or diskboot code will be loaded by camera
MEMBASEADDR=0x1900

# start of firmware
ROMBASEADDR=0xFF810000


MAXRAMADDR=0x07ffffff

# points to the start of the memory pool used by the firmware
MEMISOSTART=0x001899d8

# type of FI2 encoding
KEYSYS = d4i
# type of diskboot encoding
NEED_ENCODED_DISKBOOT = 16

