topdir=../../../../
OBJS=boot.o stubs_min.o stubs_auto.o stubs_entry.o stubs_entry_2.o capt_seq.o
#TODO filewrite.o lib.o movie_rec.o
STUBS_AUTO_DEPS=boot.c capt_seq.c 
#TODO movie_rec.c filewrite.c 

include $(topdir)platform/makefile_sub.inc

